export const csTranslations = {
    'nav.about': 'O NÁS',
    'nav.menu': 'MENU',
    'nav.locations': 'LOKALITY',
    'nav.contact': 'KONTAKT',
    'nav.joinUs': 'PŘIPOJTE SE',
    'nav.orderNow': 'OBJEDNAT NYNÍ',
    'nav.careers': 'KARIÉRA',
    'nav.privacyPolicy': 'ZÁSADY OCHRANY OSOBNÍCH ÚDAJŮ',
    'nav.termsOfService': 'PODMÍNKY SLUŽBY',
  
    'hero.title': 'Seznamte se s Memet Kebab',
    'hero.subtitle': 'Zažijte pravý „döner“ za dostupné ceny. Přinášíme tradiční recepty do Evropy.',
    'hero.orderNow': 'Objednat Nyní',
  
    'menu.title': 'Naše Menu',
    'menu.subtitle': 'Objevte náš výběr autentických jídel, připravovaných denně čerstvě podle tradičních receptů',
    'menu.specialOffer': 'Speciální Nabídka',
    'menu.viewFull': 'Zobrazit Celé Menu',
    'menu.viewDetails': 'Zobrazit Detaily',
    'menu.search': 'Hledat v menu...',
    'menu.filter': 'Filtr',
    'menu.categories.all': 'Vše',
    'menu.categories.doner': 'Döner',
    'menu.categories.kebab': 'Kebab',
    'menu.categories.pide': 'Pide',
    'menu.categories.lahmacun': 'Lahmacun',
    'menu.categories.vegetarian': 'Vegetariánské',
    'menu.categories.desserts': 'Dezerty',
    'menu.categories.drinks': 'Nápoje',
    'menu.reviews': 'recenze',
  
    'locations.title': 'Naše Lokality',
    'locations.description': 'Najděte nejbližší restauraci Memet Kebab a zažijte autentickou kuchyni.',
    'locations.comingSoon': 'Již Brzy',
    'locations.hours': 'Otevírací Doba',
    'locations.phone': 'Telefon',
    'locations.flagship': 'Vlajková Loď Restaurace',
    'locations.dineIn': 'Možnost Konzumace v Restauraci a S Sebou',
    'locations.capacity': 'Prostorné Místa k Sezení K Dispozici',
    'locations.viewMenu': 'Zobrazit Menu',
    'locations.back': 'Zpět na Předchozí Stránku',
    'locations.expansion': 'Rosteme po Evropě',
    'locations.expansionText': 'Počínaje našimi skromnými začátky rozšiřujeme naši přítomnost po celé Evropě, abychom přinesli autentickou kuchyni do více komunit. Naše odhodlání ke kvalitě a tradici zůstává nezměněno, jak rosteme.',
    'locations.quality': 'Kvalita na Prvním Místě',
    'locations.qualityText': 'Každá lokalita udržuje naše vysoké standardy kvality potravin a vynikající služby.',
    'locations.tradition': 'Autentická Tradice',
    'locations.traditionText': 'Zachováváme naše tradiční recepty a způsoby vaření ve všech lokalitách.',
    'locations.community': 'Zaměření na Komunitu',
    'locations.communityText': 'Každá lokalita je navržena tak, aby byla příjemným místem setkávání pro místní komunitu.',
    'locations.franchiseTitle': 'Připojte se k Rodině Memet Kebab',
    'locations.franchiseDescription': 'Máte zájem přinést autentickou kuchyni do vaší komunity? Zjistěte si více o našich franšízových příležitostech.',
    'locations.franchiseContact': 'Kontaktujte Náš Franšízový Tým',
    'locations.franchiseEmail': 'franchise@memetkebab.com',
    'locations.franchisePhone': '+48 123 456 789',
  
    'about.title': 'Náš Příběh',
    'about.text1': 'Po desetiletí se zavazujeme k servírování masných pokrmů prvotřídní kvality po celé Evropě. Naše cesta začala s jednoduchou vizí: poskytovat autentické, vysoce kvalitní jídlo za rozumné ceny.',
    'about.text2': 'Dnes pokračujeme v této tradici pečlivým výběrem nejlepších kusů masa a jejich přípravou s odborností a vášní.',
    'about.meat.title': 'Maso Prémiové Kvality',
    'about.meat.description': 'Jsme hrdí na to, že můžeme získávat pouze maso nejvyšší kvality od důvěryhodných evropských dodavatelů. Naše odhodlání k dokonalosti zajišťuje, že každé jídlo, které servírujeme, splňuje naše přísné standardy.',
    'about.meat.point1': 'Prémiové kusy vybírané denně',
    'about.meat.point2': 'Certifikovaná záruka kvality',
    'about.meat.point3': 'Odborně připravené zkušenými kuchaři',
      'about.meat.detailed.description':
        'V Memet Kebab je náš základ postaven na neochvějné oddanosti masu prvotřídní kvality. ' +
        'Spolupracujeme výhradně s renomovanými evropskými dodavateli, kteří sdílejí naše odhodlání k dokonalosti. ' +
        'Naši mistři řezníci pečlivě vybírají každý kus masa a zajišťují, že splňuje naše přísná kritéria kvality, než se vůbec dostane do našich kuchyní.\n\n' +
        'Náš proces přípravy masa kombinuje tradiční evropské řeznické tradice s moderními standardy bezpečnosti potravin. ' +
        'Udržujeme přísné teplotní kontroly a hygienické protokoly v celém našem dodavatelském řetězci, od výběru až po servis. ' +
        'Tato pečlivá pozornost k detailům zajišťuje, že si každý kus masa zachová svou optimální chuť a texturu.\n\n' +
        'Věříme, že výjimečná kvalita masa není jen o řezu – jde o celou cestu od farmy na talíř. ' +
        'Proto úzce spolupracujeme s dodavateli, kteří upřednostňují etické zemědělské postupy a dodržují nejvyšší standardy dobrých životních podmínek zvířat. ' +
        'Naše odhodlání ke kvalitě přesahuje chuť a zahrnuje odpovědnost a udržitelnost v každém aspektu našeho provozu.',
      'about.meat.detailed.point1': 'Naši zkušení řezníci denně pečlivě vybírají kusy prémiové kvality a kontrolují každý kus, aby se ujistili, že splňuje naše přísné standardy kvality. Tento denní proces výběru zaručuje, že se do našich kuchyní dostanou pouze ty nejlepší kusy.',
      'about.meat.detailed.point2': 'Udržujeme komplexní opatření pro kontrolu kvality a spolupracujeme výhradně s certifikovanými evropskými dodavateli, kteří sdílejí naše odhodlání k dokonalosti. Pravidelné audity a inspekce zajišťují stálou kvalitu.',
      'about.meat.detailed.point3': 'Naši zkušení kuchaři přinášejí desítky let kombinovaných zkušeností, aby připravili každé jídlo s přesností a péčí, přičemž používají tradiční techniky, které se zdokonalovaly po generace.',
    'about.learnMore': 'Zjistěte Více o Nás',
    'about.values.title': 'Naše Hodnoty',
    'about.values.description': 'Náš základ je postaven na hodnotách, které definují každý aspekt našeho servisu a kvality.',
    'about.values.quality.title': 'Nekompromisní Kvalita',
    'about.values.quality.description': 'Vybíráme pouze maso prvotřídní kvality a nejčerstvější suroviny, přičemž spolupracujeme s důvěryhodnými evropskými dodavateli.',
    'about.values.tradition.title': 'Dědictví a Inovace',
    'about.values.tradition.description': 'Ctíme tradiční recepty, které se předávají z generace na generaci, a zároveň využíváme moderní techniky ke zlepšení vašeho stolování.',
    'about.values.community.title': 'Komunita na Prvním Místě',
    'about.values.community.description': 'Každá restaurace Memet Kebab je více než jen místo k jídlu – je to příjemné místo, kde se komunity setkávají, aby sdílely skvělé jídlo.',
    'about.values.service.title': 'Excelence ve Službách',
    'about.values.service.description': 'Věříme v to, že se ke každému zákazníkovi chováme jako k rodině a poskytujeme vřelou a pozornou službu.',
    'about.tradition.title': 'Naše Kulinářské Dědictví',
    'about.tradition.description': 'Naše historie má kořeny v generacích kulinářských znalostí, kde byly tradiční recepty pečlivě uchovávány a zdokonalovány.',
    'about.history': 'Naše Historie',
    'about.history.part1': 'Naše historie začala s jednoduchou, ale silnou vizí: přinést to nejlepší a nejautentičtější jídlo do Evropy. Počínaje jedním místem, náš zakladatel byl poháněn neochvějným závazkem ke kvalitě a autenticitě. Na rozdíl od ostatních, kteří se uchylují ke zkratkám, jsme se od prvního dne zásadně rozhodli: používat pouze skutečné maso nejvyšší kvality, připravené podle osvědčených tradic.',
    'about.history.part2': 'Tento závazek k dokonalosti znamenal osobní výběr našich dodavatelů masa, přičemž jsme si vybírali pouze ty, kteří sdíleli naše odhodlání ke kvalitě. Navázali jsme partnerství s renomovanými evropskými řezníky, kteří chápou, že skutečné jídlo vyžaduje skutečné maso - žádné plnidla, žádné kompromisy. Náš zakladatel strávil roky zdokonalováním naší charakteristické marinády a technik vaření a pracoval po boku mistrů kuchařů, aby vytvořil jídla, která by nastavila nové standardy chuti a kvality.',
    'about.history.part3': 'Dnes je Memet Kebab důkazem této původní vize. To, co začalo jako jediná restaurace, se rozrostlo v oblíbenou evropskou značku, ale naše zásady zůstávají nezměněny. Stále osobně kontrolujeme naše dodavatele masa, stále používáme stejné osvědčené recepty a stále udržujeme vysoké standardy, které z nás udělaly lídra v autentické kuchyni. Každé jídlo, které servírujeme, nese naše dědictví kulinářské dokonalosti, připravené se stejnou vášní a pozorností k detailům jako v náš první den.',
    'about.commitment': 'Náš Závazek',
    'about.commitment.part1': 'V Memet Kebab náš závazek přesahuje servírování lahodného jídla. Jsme odhodláni vytvářet příjemné prostředí, kde každý host může zažít výjimečnou pohostinnost. Od naší kuchyně až po váš stůl zajišťujeme, že každý detail splňuje naše vysoké standardy kvality a autenticity. To, co nás odlišuje, je naše neochvějné odhodlání používat v našich jídlech pouze skutečné maso prvotřídní kvality - standard, který dodržujeme od našeho založení.',
    'about.commitment.part2': 'Neustále se snažíme zlepšovat a inovovat a zároveň zůstáváme věrni našemu kulinářskému dědictví. Naše maso pochází výhradně od certifikovaných evropských dodavatelů, kteří sdílejí naše odhodlání ke kvalitě. Každý kus je pečlivě vybrán, řádně vyzrálý a odborně připravený v souladu s tradičními metodami. Nikdy nepoužíváme zpracované maso, plnidla ani umělé přísady - pouze čisté, vysoce kvalitní maso, které poskytuje autentickou chuť, kterou naši zákazníci milují.',
    'about.commitment.part3': 'Tento závazek ke kvalitě se rozšiřuje na každý aspekt našeho provozu. Naše jídla jsou připravována denně čerstvá v každé lokalitě, což zajišťuje, že každá porce splňuje vysoké standardy, které naši zákazníci očekávají. Navzdory našemu odhodlání k prvotřídním surovinám a tradičním metodám přípravy jsme i nadále odhodláni udržovat naše ceny dostupné, a tím zpřístupnit naši autentickou kuchyni všem, aniž bychom kdy slevili z kvality.',
  
    'features.quality': 'Prémiová Kvalita',
    'features.qualityDesc': '100% halal maso, čerstvá zelenina a domácí omáčky',
    'features.service': 'Rychlý Servis',
    'features.serviceDesc': 'Rychlá příprava bez kompromisů v kvalitě',
    'features.community': 'Komunita na Prvním Místě',
    'features.communityDesc': 'S hrdostí sloužíme našim místním komunitám',
  
    'app.title': 'Získejte Aplikaci Memet Kebab',
    'app.subtitle': 'Objednávejte předem, získávejte odměny a získejte exkluzivní nabídky!',
    'app.scan': 'Naskenujte pro stažení',
    'app.available': 'K dispozici pro iOS a Android',
  
    'contact.title': 'Kontaktujte Nás',
    'contact.call': 'Zavolejte Nám',
    'contact.email': 'Napište Nám E-mail',
    'contact.visit': 'Navštivte Nás',
  
    'careers.title': 'Připojte se k Našemu Týmu',
    'careers.description': 'Vždy hledáme zapálené lidi, kteří se připojí k naší rostoucí rodině. Zažijte radost ze servírování autentické kuchyně při budování své kariéry.',
    'careers.button': 'Zobrazit Otevřené Pozice',
    'careers.form.title': 'Připojte se k Našemu Týmu',
    'careers.form.fullName': 'Celé Jméno',
    'careers.form.email': 'E-mailová Adresa',
    'careers.form.phone': 'Telefonní Číslo',
    'careers.form.position': 'Pozice',
    'careers.form.selectPosition': 'Vyberte pozici',
    'careers.form.experience': 'Roky Zkušeností',
    'careers.form.message': 'Proč se chcete připojit k našemu týmu?',
    'careers.form.submit': 'Odeslat Žádost',
    'careers.form.resume': 'Životopis',
    'careers.positions.chef': 'Šéfkuchař',
    'careers.positions.kitchen': 'Kuchyňský Personál',
    'careers.positions.manager': 'Manažer Restaurace',
    'careers.positions.server': 'Číšník',
    'careers.positions.driver': 'Řidič Rozvozu',
    'careers.training.title': 'Školení a Rozvoj',
    'careers.training.description': 'Příležitosti k neustálému učení a cesty kariérního růstu',
    'careers.benefits.title': 'Skvělé Výhody',
    'careers.benefits.description': 'Konkurenceschopný plat, zdravotní pojištění a příspěvek na stravování',
    'careers.team.title': 'Úžasný Tým',
    'careers.team.description': 'Připojte se k zapálené a podpůrné pracovní rodině',
  
    'product.features.fresh': 'Vyrobeno z čerstvých surovin denně',
    'product.features.halal': 'Certifikované Halal maso',
    'product.features.made': 'Vyrobeno na objednávku',
    'product.features.chef': 'Připraveno zkušenými kuchaři',
    'product.features.traditional': 'Tradiční recepty',
    'product.orderNow': 'Objednat Nyní',
    'product.addFavorites': 'Přidat do Oblíbených',
  
    'products.classicDoner.title': 'Klasický Döner',
    'products.classicDoner.description': 'Tradiční döner s čerstvou zeleninou a speciální omáčkou',
    'products.mixedGrill.title': 'Míchaný Talíř na Grilu',
    'products.mixedGrill.description': 'Kombinace döneru, podávaná s rýží a zeleninou',
    'products.falafel.title': 'Vegetariánský Falafel',
    'products.falafel.description': 'Domácí falafel s humusem a čerstvým salátem',
    'products.iskender.title': 'Iskender',
    'products.iskender.description': 'Krájený döner na chlebu pide s jogurtem a rajčatovou omáčkou',
    'products.adanaKebab.title': 'Adana Kebab',
    'products.adanaKebab.description': 'Pikantní kebab z mletého jehněčího masa, podávaný s bulgurovým pilafem a grilovanou zeleninou',
    'products.cheesePide.title': 'Pide se Sýrem',
    'products.cheesePide.description': 'Tradiční jídlo se směsí sýrů a bylinek',
  
    'promos.familyFeast.title': 'Rodinná Hody',
    'promos.familyFeast.description': 'Ideální pro 4: Míchaný talíř na grilu, saláty, rýže a nápoje',
    'promos.studentSpecial.title': 'Studentská Speciální Nabídka',
    'promos.studentSpecial.description': 'Ukažte svůj studentský průkaz a získejte 15% slevu na jakékoli jídlo',
    'promo.firstOrder.discount': 'SLEVA 15%',
    'promo.firstOrder.text': 'Na vaši první objednávku',
  
    'stats.rating': 'Hodnocení 4.9 ★',
    'stats.downloads': '100K+ Stažení',
    'stats.install': 'Instalace Zdarma',
    'stats.platform': 'Mobilní aplikace',
  
    'stats.happyCustomers': 'Šťastní Zákazníci',
    'stats.customerRating': 'Hodnocení Zákazníků',
    'stats.locations': 'Lokality',
  
    'menu.featuredItems': 'Doporučené Položky',
    'menu.viewMenu': 'Zobrazit Menu',
    'menu.popular': 'Oblíbené',
    'menu.viewFullMenu': 'Zobrazit Celé Menu',
    'menu.specialOffers': 'Speciální Nabídky',
    'menu.limitedTime': 'Omezená Doba',
    'menu.order': 'Objednat',
    'menu.rating': '4.9',
  
      'products.classicDoner.title': 'Klasický Döner',
      'products.classicDoner.description': 'Tradiční jídlo z masa prvotřídní kvality',
      'products.mixedGrill.title': 'Míchaný Gril',
      'products.mixedGrill.description': 'Lahodný výběr grilovaných mas, podávaný s rýží a zeleninou',
      'products.falafel.title': 'Falafel Wrap',
      'products.falafel.description': 'Křupavé falafelové kuličky zabalené v čerstvém chlebu pita s tahini omáčkou',
      'products.iskender.title': 'İskender',
      'products.iskender.description': 'Krájený döner na chlebu pide s rajčatovou omáčkou a jogurtem',
  
      'promos.familyFeast.title': 'Rodinná Hody',
      'promos.familyFeast.description': 'Ideální jídlo ke sdílení pro 4-6 osob s různými kebaby a přílohami',
      'promos.studentSpecial.title': 'Studentská Speciální Nabídka',
      'promos.studentSpecial.description': 'Předložte svůj studentský průkaz a získejte exkluzivní slevy na vybrané jídla',
  
      'contact.title': 'Kontaktujte Nás',
      'contact.call': 'Zavolejte Nám',
      'contact.email': 'Napište Nám',
      'contact.visit': 'Navštivte Nás',
  
      'app.comingSoon': 'Již Brzy',
      'app.downloadNow': 'Stáhnout Nyní',
      'app.appStore': 'App Store',
      'app.googlePlay': 'Google Play',
      'app.badge.rating': 'Hodnocení 4.9',
      'app.badge.reviews': '2k+ Recenzí',
      'app.badge.downloads': '100k+',
      'app.badge.downloadsLabel': 'Stažení',
  
      'hero.badge': '#1 v Polsku',  // Verify market-specific badge
      'hero.title': 'Seznamte se s Memet Kebab',
      'hero.peoplesChoice': 'Volba Lidu',
  
      'general.back': 'Zpět',
      'general.viewDetails': 'Zobrazit Detaily',
  
      'footer.description': 'Přinášíme autentický döner na váš stůl. Zažijte chuť tradice s Memet Kebab.',
      'footer.quickLinks': 'Rychlé Odkazy',
      'footer.contact': 'Kontakt',
      'footer.followUs': 'Sledujte Nás',
      'footer.rights': 'Všechna práva vyhrazena.',
      'footer.address': 'Kebab ulice 123',
      'footer.city': 'Evropa',
      'footer.phone': '+1 (555) 123-4567',
      'footer.email': 'info@memetkebab.com',
  
      'contact.getInTouch': 'Spojte Se S Nami',
      'contact.message': 'Pošlete nám zprávu',
      'contact.form.name': 'Vaše Jméno',
      'contact.form.email': 'Váš E-mail',
      'contact.form.message': 'Vaše Zpráva',
      'contact.form.submit': 'Odeslat Zprávu',
  
      'careers.subtitle': 'Staňte se součástí naší rostoucí rodiny',
      'careers.positions': 'Otevřené Pozice',
      'careers.benefits': 'Výhody',
      'careers.benefits.health': 'Zdravotní Pojištění',
      'careers.benefits.vacation': 'Placená Dovolená',
      'careers.benefits.training': 'Profesionální Školení',
      'careers.benefits.meals': 'Strava pro Zaměstnance',
      'careers.benefits.growth': 'Kariérní Růst',
      'careers.apply': 'Aplikovat Nyní',
      'careers.noPositions': 'V současné době nejsou k dispozici žádné otevřené pozice',
  
      'privacy.title': 'Zásady Ochrany Osobních Údajů',
      'privacy.lastUpdated': 'Poslední Aktualizace',
  
      'terms.title': 'Podmínky Služby',
      'terms.lastUpdated': 'Poslední Aktualizace',
  
      'maintenance.title': 'Probíhá Údržba',
      'maintenance.message': 'Naše webové stránky a aplikace jsou v současné době aktualizovány, abychom vám mohli lépe sloužit. Brzy se vrátíme!',
      'maintenance.status': 'Probíhá',
  
      'app.subtitle': 'Stáhněte si naši mobilní aplikaci a užívejte si exkluzivní nabídky a rychlejší objednávání.',
      'app.features.fast': 'Rychlé a snadné objednávání',
      'app.features.rewards': 'Získejte odměny s každou objednávkou',
      'app.features.offline': 'Objednávejte offline pomocí QR kódů',
      'app.download.ios': 'Stáhněte si v App Store',
      'app.download.android': 'Získejte na Google Play',
  
      'careers.training.title': 'Profesionální Školení',
      'careers.training.description': 'Poskytujeme komplexní školení, abychom vám pomohli růst ve vaší roli.',
      'careers.benefits.title': 'Skvělé Výhody',
      'careers.benefits.description': 'Užijte si konkurenceschopný plat, flexibilní pracovní dobu a příležitosti kariérního růstu.',
      'careers.team.title': 'Úžasný Tým',
      'careers.team.description': 'Pracujte se zapálenými lidmi, kteří sdílejí vaši lásku k dobrému jídlu.',
      'careers.positions.chef': 'Kuchař',
      'careers.positions.kitchen': 'Kuchyňský Personál',
      'careers.positions.manager': 'Manažer Restaurace',
      'careers.positions.server': 'Číšník',
      'careers.positions.driver': 'Řidič',
      'careers.form.title': 'Aplikovat Nyní',
      'careers.form.fullName': 'Celé Jméno',
      'careers.form.email': 'E-mailová Adresa',
      'careers.form.phone': 'Telefonní Číslo',
      'careers.form.position': 'Pozice',
      'careers.form.selectPosition': 'Vyberte Pozici',
      'careers.form.experience': 'Roky Zkušeností',
      'careers.form.message': 'Řekněte Nám O Sobě',
      'careers.form.submit': 'Odeslat Žádost',
  
      'footer.company': 'Společnost',
      'footer.about': 'O Nás',
      'footer.careers': 'Kariéra',
      'footer.contact': 'Kontakt',
      'footer.legal': 'Právní Informace',
      'footer.privacy': 'Zásady Ochrany Osobních Údajů',
      'footer.terms': 'Podmínky Služby',
      'footer.follow': 'Sledujte Nás',
      'footer.newsletter': 'Zpravodaj',
      'footer.newsletterDesc': 'Přihlaste se k odběru a získejte speciální nabídky a aktualizace.',
      'footer.subscribe': 'Přihlásit Se K Odběru',
      'footer.rights': 'Všechna práva vyhrazena',
  
      'franchise.title': 'Připojte se k rodině Memet Kebab',
      'franchise.description': 'Buďte součástí našeho úspěšného příběhu. Otevřete si vlastní franšízu Memet Kebab a přineste autentickou kuchyni do vaší komunity.',
      'franchise.cta': 'Staňte se Franšízovým Partnerem',
      'franchise.years': 'Roky Zkušeností',
      'franchise.customers': 'Šťastní Zákazníci',
      'franchise.satisfaction': 'Spokojenost Partnerů',
      'franchise.support': 'Dostupná Podpora',

    // Franchise Page
    'franchise.hero.title': 'Připojte se k rodině Memet Kebab',
    'franchise.hero.subtitle': 'Zahájte své vlastní úspěšné podnikání s prověřenou značkou',
    'franchise.hero.cta': 'Stát se franchisovým partnerem',
    
    'franchise.benefits.title': 'Výhody franchisového partnerství',
    'franchise.benefits.subtitle': 'Využijte výhod našeho prověřeného obchodního modelu',
    'franchise.benefits.proven': 'Prověřený koncept',
    'franchise.benefits.provenDesc': 'Úspěšný obchodní model s prokázanou ziskovostí',
    'franchise.benefits.support': 'Komplexní podpora',
    'franchise.benefits.supportDesc': 'Průběžná podpora ve všech oblastech podnikání',
    'franchise.benefits.location': 'Výběr lokality',
    'franchise.benefits.locationDesc': 'Profesionální pomoc při výběru umístění',
    'franchise.benefits.roi': 'Vysoká návratnost',
    'franchise.benefits.roiDesc': 'Atraktivní marže a rychlá návratnost investic',
    'franchise.benefits.brand': 'Silná značka',
    'franchise.benefits.brandDesc': 'Využijte výhod zavedené značky s věrnými zákazníky',

    'franchise.steps.title': 'Cesta k franchisovému partnerství',
    'franchise.steps.subtitle': 'Pět kroků k vaší vlastní restauraci Memet Kebab',
    'franchise.steps.inquiry': 'Poptávka',
    'franchise.steps.inquiryDesc': 'Kontaktujte nás a sdělte nám svou vizi',
    'franchise.steps.evaluation': 'Vyhodnocení',
    'franchise.steps.evaluationDesc': 'Společně prozkoumáme možnosti',
    'franchise.steps.agreement': 'Smlouva',
    'franchise.steps.agreementDesc': 'Podepsání franchisové smlouvy',
    'franchise.steps.training': 'Školení',
    'franchise.steps.trainingDesc': 'Komplexní zaškolení ve všech oblastech',
    'franchise.steps.launch': 'Otevření',
    'franchise.steps.launchDesc': 'Otevření vaší vlastní restaurace',

    'franchise.investment.title': 'Investujte do své budoucnosti',
    'franchise.investment.description': 'Staňte se součástí rostoucího úspěchu v pohostinství',
    'franchise.investment.point1': 'Nízká počáteční investice ve srovnání s průměrem v odvětví',
    'franchise.investment.point2': 'Rychlá návratnost díky prověřenému obchodnímu modelu',
    'franchise.investment.point3': 'Komplexní podpora při financování',
    'franchise.investment.form.title': 'Máte zájem?',
    'franchise.investment.form.name': 'Vaše jméno',
    'franchise.investment.form.email': 'Váš e-mail',
    'franchise.investment.form.phone': 'Vaše telefonní číslo',
    'franchise.investment.form.location': 'Požadovaná lokalita',
    'franchise.investment.form.submit': 'Odeslat žádost',

    // Locations Page
    'locations.title': 'Naše pobočky',
    'locations.subtitle': 'Najděte nejbližší restauraci Memet Kebab a uspokojte své chuťové buňky',
    'locations.search.placeholder': 'Hledejte podle adresy, města nebo názvu ulice...',
    'locations.search.button': 'Najít nejbližší pobočku',
    'locations.search.finding': 'Hledání pobočky...',
    'locations.status.active': 'Otevřeno',
    'locations.status.comingSoon': 'Brzy otevřeme',
    'locations.hours': 'Otevírací doba',
    'locations.getDirections': 'Získat navigaci',
    'locations.callUs': 'Zavolejte nám',
    'locations.visitUs': 'Navštivte nás'
  };