export const deTranslations = {
    'nav.about': 'ÜBER UNS',
    'nav.menu': 'MENÜ',
    'nav.locations': 'STANDORTE',
    'nav.contact': 'KONTAKT',
    'nav.joinUs': 'MITMACHEN',
    'nav.orderNow': 'JETZT BESTELLEN',
    'nav.careers': 'KARRIERE',
    'nav.privacyPolicy': 'DATENSCHUTZBESTIMMUNGEN',
    'nav.termsOfService': 'NUTZUNGSBEDINGUNGEN',
  
    'hero.title': 'Entdecken Sie Memet Kebab',
    'hero.subtitle': 'Erleben Sie echten "Döner" zu erschwinglichen Preisen. Wir bringen traditionelle Rezepte nach Europa.',
    'hero.orderNow': 'Jetzt bestellen',
  
    'menu.title': 'Unsere Speisekarte',
    'menu.subtitle': 'Entdecken Sie unsere Auswahl an authentischen Gerichten, die täglich frisch nach traditionellen Rezepten zubereitet werden',
    'menu.specialOffer': 'Sonderangebot',
    'menu.viewFull': 'Vollständige Speisekarte ansehen',
    'menu.viewDetails': 'Details ansehen',
    'menu.search': 'Menü durchsuchen...',
    'menu.filter': 'Filtern',
    'menu.categories.all': 'Alle',
    'menu.categories.doner': 'Döner',
    'menu.categories.kebab': 'Kebab',
    'menu.categories.pide': 'Pide',
    'menu.categories.lahmacun': 'Lahmacun',
    'menu.categories.vegetarian': 'Vegetarisch',
    'menu.categories.desserts': 'Desserts',
    'menu.categories.drinks': 'Getränke',
    'menu.reviews': 'Bewertungen',
  
    'locations.title': 'Unsere Standorte',
    'locations.description': 'Finden Sie Ihr nächstgelegenes Memet Kebab Restaurant und erleben Sie authentische Küche.',
    'locations.comingSoon': 'Demnächst',
    'locations.hours': 'Öffnungszeiten',
    'locations.phone': 'Telefon',
    'locations.flagship': 'Flagship-Restaurant',
    'locations.dineIn': 'Essen vor Ort & zum Mitnehmen verfügbar',
    'locations.capacity': 'Geräumige Sitzplätze verfügbar',
    'locations.viewMenu': 'Speisekarte ansehen',
    'locations.back': 'Zurück zur vorherigen Seite',
    'locations.expansion': 'Expansion in ganz Europa',
    'locations.expansionText': 'Ausgehend von unseren bescheidenen Anfängen erweitern wir unsere Präsenz in ganz Europa, um authentische Küche in mehr Gemeinden zu bringen. Unser Engagement für Qualität und Tradition bleibt bei unserem Wachstum unverändert.',
    'locations.quality': 'Qualität geht vor',
    'locations.qualityText': 'Jeder Standort hält unsere hohen Standards für Lebensmittelqualität und Service Excellence aufrecht.',
    'locations.tradition': 'Authentische Tradition',
    'locations.traditionText': 'Wir bewahren unsere traditionellen Rezepte und Kochmethoden an allen Standorten.',
    'locations.community': 'Community-Fokus',
    'locations.communityText': 'Jeder Standort ist als einladender Treffpunkt für die lokale Gemeinschaft konzipiert.',
    'locations.franchiseTitle': 'Werden Sie Teil der Memet Kebab Familie',
    'locations.franchiseDescription': 'Interessiert daran, authentische Küche in Ihre Gemeinde zu bringen? Erfahren Sie mehr über unsere Franchise-Möglichkeiten.',
    'locations.franchiseContact': 'Kontaktieren Sie unser Franchise-Team',
    'locations.franchiseEmail': 'franchise@memetkebab.com',
    'locations.franchisePhone': '+48 123 456 789',
  
    'about.title': 'Unsere Geschichte',
    'about.text1': 'Seit Jahrzehnten sind wir bestrebt, hochwertige Fleischgerichte in ganz Europa zu servieren. Unsere Reise begann mit einer einfachen Vision: authentisches, hochwertiges Essen zu vernünftigen Preisen anzubieten.',
    'about.text2': 'Heute setzen wir diese Tradition fort, indem wir sorgfältig die besten Fleischstücke auswählen und sie mit Fachkenntnis und Leidenschaft zubereiten.',
    'about.meat.title': 'Fleisch von Premiumqualität',
    'about.meat.description': 'Wir sind stolz darauf, nur Fleisch von höchster Qualität von vertrauenswürdigen europäischen Lieferanten zu beziehen. Unser Engagement für Exzellenz stellt sicher, dass jedes Gericht, das wir servieren, unseren hohen Standards entspricht.',
    'about.meat.point1': 'Täglich ausgewählte Premium-Fleischstücke',
    'about.meat.point2': 'Zertifizierte Qualitätssicherung',
    'about.meat.point3': 'Fachmännisch zubereitet von erfahrenen Köchen',
      'about.meat.detailed.description':
        'Bei Memet Kebab basiert unser Fundament auf einem unerschütterlichen Engagement für Fleisch von Premiumqualität. ' +
        'Wir arbeiten ausschließlich mit renommierten europäischen Lieferanten zusammen, die unsere Leidenschaft für Exzellenz teilen. ' +
        'Unsere Metzgermeister wählen jeden Fleischabschnitt sorgfältig aus und stellen sicher, dass er unsere strengen Qualitätskriterien erfüllt, bevor er jemals unsere Küchen erreicht.\n\n' +
        'Unser Prozess der Fleischzubereitung kombiniert althergebrachte europäische Metzgertraditionen mit modernen Lebensmittelsicherheitsstandards. ' +
        'Wir halten strenge Temperaturkontrollen und Hygieneprotokolle in unserer gesamten Lieferkette ein, von der Auswahl bis zum Service. ' +
        'Diese sorgfältige Liebe zum Detail stellt sicher, dass jedes Fleischstück seinen optimalen Geschmack und seine Textur behält.\n\n' +
        'Wir glauben, dass außergewöhnliche Fleischqualität nicht nur etwas mit dem Schnitt zu tun hat, sondern mit der gesamten Reise vom Bauernhof bis zum Teller. ' +
        'Deshalb arbeiten wir eng mit Lieferanten zusammen, die ethische Anbaumethoden priorisieren und die höchsten Standards für das Tierwohl einhalten. ' +
        'Unser Engagement für Qualität geht über den Geschmack hinaus und umfasst Verantwortung und Nachhaltigkeit in jedem Aspekt unseres Betriebs.',
      'about.meat.detailed.point1': 'Unsere erfahrenen Metzger wählen täglich sorgfältig Premium-Fleischstücke aus und prüfen jedes Stück, um sicherzustellen, dass es unseren strengen Qualitätsstandards entspricht. Dieser tägliche Auswahlprozess garantiert, dass nur die feinsten Stücke in unsere Küchen gelangen.',
      'about.meat.detailed.point2': 'Wir pflegen umfassende Qualitätskontrollmaßnahmen und arbeiten ausschließlich mit zertifizierten europäischen Lieferanten zusammen, die unsere Leidenschaft für Exzellenz teilen. Regelmäßige Audits und Inspektionen gewährleisten eine gleichbleibende Qualität.',
      'about.meat.detailed.point3': 'Unsere erfahrenen Köche bringen jahrzehntelange Erfahrung mit, um jedes Gericht mit Präzision und Sorgfalt zuzubereiten und dabei traditionelle Techniken zu verwenden, die über Generationen hinweg verfeinert wurden.',
    'about.learnMore': 'Mehr über uns erfahren',
    'about.values.title': 'Unsere Werte',
    'about.values.description': 'Unser Fundament basiert auf Werten, die jeden Aspekt unseres Service und unserer Qualität definieren.',
    'about.values.quality.title': 'Kompromisslose Qualität',
    'about.values.quality.description': 'Wir wählen nur Fleisch von Premiumqualität und die frischesten Zutaten und arbeiten mit vertrauenswürdigen europäischen Lieferanten zusammen, die unser Engagement für Exzellenz teilen.',
    'about.values.tradition.title': 'Tradition und Innovation',
    'about.values.tradition.description': 'Wir ehren traditionelle Rezepte, die über Generationen weitergegeben wurden, und nutzen gleichzeitig moderne Techniken, um Ihr kulinarisches Erlebnis zu verbessern.',
    'about.values.community.title': 'Community First',
    'about.values.community.description': 'Jedes Memet Kebab Restaurant ist mehr als nur ein Essplatz – es ist ein einladender Ort, an dem Gemeinden zusammenkommen, um großartiges Essen zu teilen und bleibende Erinnerungen zu schaffen.',
    'about.values.service.title': 'Exzellenter Service',
    'about.values.service.description': 'Wir glauben daran, jeden Kunden wie eine Familie zu behandeln und einen warmen, aufmerksamen Service zu bieten.',
    'about.tradition.title': 'Unser kulinarisches Erbe',
    'about.tradition.description': 'Unsere Geschichte wurzelt in Generationen kulinarischen Fachwissens, in denen traditionelle Rezepte sorgfältig bewahrt und perfektioniert wurden.',
    'about.history': 'Unser Erbe',
    'about.history.part1': 'Unsere Geschichte begann mit einer einfachen, aber kraftvollen Vision: die besten und authentischsten Gerichte nach Europa zu bringen. Ausgehend von einem einzigen Standort wurde unser Gründer von einem unerschütterlichen Engagement für Qualität und Authentizität angetrieben. Im Gegensatz zu anderen, die Abstriche machen, haben wir vom ersten Tag an eine grundlegende Entscheidung getroffen: nur echtes Fleisch von Premiumqualität zu verwenden, das nach althergebrachten Traditionen zubereitet wird.',
    'about.history.part2': 'Dieses Engagement für Exzellenz bedeutete, dass wir unsere Fleischlieferanten persönlich auswählen und nur diejenigen auswählen, die unsere Hingabe an Qualität teilten. Wir haben Partnerschaften mit renommierten europäischen Metzgern aufgebaut, die verstehen, dass echte Gerichte echtes Fleisch erfordern – keine Füllstoffe, keine Kompromisse. Unser Gründer verbrachte Jahre damit, unsere charakteristische Marinade und Kochtechniken zu perfektionieren und arbeitete mit Küchenmeistern zusammen, um Gerichte zu kreieren, die neue Maßstäbe in Bezug auf Geschmack und Qualität setzen würden.',
    'about.history.part3': 'Heute ist Memet Kebab ein Beweis für diese ursprüngliche Vision. Was als einzelnes Restaurant begann, hat sich zu einer beliebten europäischen Marke entwickelt, aber unsere Prinzipien sind unverändert geblieben. Wir überprüfen immer noch persönlich unsere Fleischlieferanten, verwenden immer noch die gleichen bewährten Rezepte und halten immer noch die hohen Standards aufrecht, die uns zu einem führenden Unternehmen in der authentischen Küche gemacht haben. Jedes Gericht, das wir servieren, trägt unser Erbe kulinarischer Exzellenz in sich, zubereitet mit der gleichen Leidenschaft und Liebe zum Detail wie an unserem ersten Tag.',
    'about.commitment': 'Unser Engagement',
    'about.commitment.part1': 'Bei Memet Kebab geht unser Engagement über das Servieren köstlicher Speisen hinaus. Wir sind bestrebt, eine einladende Umgebung zu schaffen, in der jeder Gast außergewöhnliche Gastfreundschaft erleben kann. Von unserer Küche bis zu Ihrem Tisch stellen wir sicher, dass jedes Detail unseren hohen Ansprüchen an Qualität und Authentizität entspricht. Was uns auszeichnet, ist unser unerschütterliches Engagement, in unseren Gerichten nur echtes Fleisch von Premiumqualität zu verwenden - ein Standard, den wir seit unserer Gründung aufrechterhalten.',
    'about.commitment.part2': 'Wir sind ständig bestrebt, uns zu verbessern und Innovationen einzuführen, während wir unserem kulinarischen Erbe treu bleiben. Unser Fleisch wird ausschließlich von zertifizierten europäischen Lieferanten bezogen, die unser Engagement für Qualität teilen. Jedes Stück wird sorgfältig ausgewählt, richtig gereift und fachmännisch nach traditionellen Methoden zubereitet. Wir verwenden niemals verarbeitetes Fleisch, Füllstoffe oder künstliche Zusätze - nur reines, hochwertiges Fleisch, das den authentischen Geschmack liefert, den unsere Kunden lieben.',
    'about.commitment.part3': 'Dieses Engagement für Qualität erstreckt sich auf jeden Aspekt unserer Tätigkeit. Unsere Gerichte werden täglich frisch an jedem Standort zubereitet, um sicherzustellen, dass jede Portion die hohen Standards erfüllt, die unsere Kunden erwarten. Trotz unseres Engagements für erstklassige Zutaten und traditionelle Zubereitungsmethoden sind wir weiterhin bestrebt, unsere Preise erschwinglich zu halten, wodurch unsere authentische Küche für jedermann zugänglich ist, ohne jemals Kompromisse bei der Qualität einzugehen.',
  
    'features.quality': 'Premium Qualität',
    'features.qualityDesc': '100% Halal-Fleisch, frisches Gemüse und hausgemachte Saucen',
    'features.service': 'Schneller Service',
    'features.serviceDesc': 'Schnelle Zubereitung ohne Kompromisse bei der Qualität',
    'features.community': 'Gemeinschaft an erster Stelle',
    'features.communityDesc': 'Wir sind stolz darauf, unsere lokalen Gemeinschaften zu bedienen',
  
    'app.title': 'Holen Sie sich die Memet Kebab App',
    'app.subtitle': 'Bestellen Sie im Voraus, sammeln Sie Prämien und erhalten Sie exklusive Angebote!',
    'app.scan': 'Scannen zum Herunterladen',
    'app.available': 'Verfügbar für iOS und Android',
  
    'contact.title': 'Kontaktieren Sie uns',
    'contact.call': 'Rufen Sie uns an',
    'contact.email': 'Senden Sie uns eine E-Mail',
    'contact.visit': 'Besuchen Sie uns',
  
    'careers.title': 'Treten Sie unserem Team bei',
    'careers.description': 'Wir sind immer auf der Suche nach leidenschaftlichen Menschen, die sich unserer wachsenden Familie anschließen. Erleben Sie die Freude, authentische Küche zu servieren und gleichzeitig Ihre Karriere aufzubauen.',
    'careers.button': 'Offene Stellen anzeigen',
    'careers.form.title': 'Treten Sie unserem Team bei',
    'careers.form.fullName': 'Vollständiger Name',
    'careers.form.email': 'E-Mail-Addresse',
    'careers.form.phone': 'Telefonnummer',
    'careers.form.position': 'Position',
    'careers.form.selectPosition': 'Wählen Sie eine Position',
    'careers.form.experience': 'Berufserfahrung in Jahren',
    'careers.form.message': 'Warum möchten Sie unserem Team beitreten?',
    'careers.form.submit': 'Bewerbung abschicken',
    'careers.form.resume': 'Lebenslauf',
    'careers.positions.chef': 'Chefkoch',
    'careers.positions.kitchen': 'Küchenpersonal',
    'careers.positions.manager': 'Restaurantleiter',
    'careers.positions.server': 'Kellner',
    'careers.positions.driver': 'Lieferfahrer',
    'careers.training.title': 'Ausbildung & Entwicklung',
    'careers.training.description': 'Kontinuierliche Lernmöglichkeiten und Karrierewege',
    'careers.benefits.title': 'Tolle Vorteile',
    'careers.benefits.description': 'Attraktives Gehalt, Krankenversicherung und Essenszuschuss',
    'careers.team.title': 'Fantastisches Team',
    'careers.team.description': 'Treten Sie einer leidenschaftlichen und unterstützenden Arbeitsfamilie bei',
  
    'product.features.fresh': 'Täglich mit frischen Zutaten zubereitet',
    'product.features.halal': 'Zertifiziertes Halal-Fleisch',
    'product.features.made': 'Auf Bestellung zubereitet',
    'product.features.chef': 'Zubereitet von erfahrenen Köchen',
    'product.features.traditional': 'Traditionelle Rezepte',
    'product.orderNow': 'Jetzt bestellen',
    'product.addFavorites': 'Zu Favoriten hinzufügen',
  
    'products.classicDoner.title': 'Klassischer Döner',
    'products.classicDoner.description': 'Traditioneller Döner mit frischem Gemüse und spezieller Sauce',
    'products.mixedGrill.title': 'Gemischte Grillplatte',
    'products.mixedGrill.description': 'Kombination aus Döner, serviert mit Reis und Gemüse',
    'products.falafel.title': 'Vegetarischer Falafel',
    'products.falafel.description': 'Hausgemachter Falafel mit Hummus und frischem Salat',
    'products.iskender.title': 'Iskender',
    'products.iskender.description': 'Geschnittener Döner auf Pide-Brot mit Joghurt und Tomatensauce',
    'products.adanaKebab.title': 'Adana Kebab',
    'products.adanaKebab.description': 'Würziger Lammhackfleisch-Kebab, serviert mit Bulgur-Pilaw und gegrilltem Gemüse',
    'products.cheesePide.title': 'Käse Pide',
    'products.cheesePide.description': 'Traditionelles Gericht mit gemischtem Käse und Kräutern',
  
    'promos.familyFeast.title': 'Familienfest',
    'promos.familyFeast.description': 'Perfekt für 4: Gemischte Grillplatte, Salate, Reis und Getränke',
    'promos.studentSpecial.title': 'Studentenangebot',
    'promos.studentSpecial.description': 'Zeigen Sie Ihren Studentenausweis und erhalten Sie 15% Rabatt auf jede Mahlzeit',
    'promo.firstOrder.discount': '15% RABATT',
    'promo.firstOrder.text': 'Auf Ihre erste Bestellung',
  
    'stats.rating': '4.9 ★ Bewertung',
    'stats.downloads': '100K+ Downloads',
    'stats.install': 'Kostenlose Installation',
    'stats.platform': 'Mobile App',
  
    'stats.happyCustomers': 'Zufriedene Kunden',
    'stats.customerRating': 'Kundenbewertung',
    'stats.locations': 'Standorte',
  
    'menu.featuredItems': 'Empfohlene Artikel',
    'menu.viewMenu': 'Speisekarte ansehen',
    'menu.popular': 'Beliebt',
    'menu.viewFullMenu': 'Vollständige Speisekarte ansehen',
    'menu.specialOffers': 'Sonderangebote',
    'menu.limitedTime': 'Für begrenzte Zeit',
    'menu.order': 'Bestellen',
    'menu.rating': '4.9',
  
      'products.classicDoner.title': 'Klassischer Döner',
      'products.classicDoner.description': 'Traditionelles Gericht aus Fleisch von Premiumqualität',
      'products.mixedGrill.title': 'Gemischter Grill',
      'products.mixedGrill.description': 'Eine köstliche Auswahl an gegrilltem Fleisch, serviert mit Reis und Gemüse',
      'products.falafel.title': 'Falafel-Wrap',
      'products.falafel.description': 'Knusprige Falafelbällchen, eingewickelt in frisches Fladenbrot mit Tahini-Sauce',
      'products.iskender.title': 'İskender',
      'products.iskender.description': 'Geschnittener Döner auf Pide-Brot mit Tomatensauce und Joghurt',
  
      'promos.familyFeast.title': 'Familienfest',
      'promos.familyFeast.description': 'Perfektes Sharing-Meal für 4-6 Personen mit einer Vielzahl von Kebabs und Beilagen',
      'promos.studentSpecial.title': 'Studentenangebot',
      'promos.studentSpecial.description': 'Zeigen Sie Ihren Studentenausweis vor, um exklusive Rabatte auf ausgewählte Mahlzeiten zu erhalten',
  
      'contact.title': 'Kontaktieren Sie uns',
      'contact.call': 'Rufen Sie uns an',
      'contact.email': 'Senden Sie uns eine E-Mail',
      'contact.visit': 'Besuchen Sie uns',
  
      'app.comingSoon': 'Demnächst',
      'app.downloadNow': 'Jetzt Herunterladen',
      'app.appStore': 'App Store',
      'app.googlePlay': 'Google Play',
      'app.badge.rating': '4.9 Bewertung',
      'app.badge.reviews': '2k+ Bewertungen',
      'app.badge.downloads': '100k+',
      'app.badge.downloadsLabel': 'Downloads',
  
      'hero.badge': '#1 in Polen', //  Verify if this market-specific badge is needed for all languages or change to #1 in Germany
      'hero.title': 'Entdecken Sie Memet Kebab',
      'hero.peoplesChoice': 'Die Wahl des Volkes',
  
      'general.back': 'Zurück',
      'general.viewDetails': 'Details ansehen',
  
      'footer.description': 'Wir bringen authentischen Döner auf Ihren Tisch. Erleben Sie den Geschmack der Tradition mit Memet Kebab.',
      'footer.quickLinks': 'Schnelllinks',
      'footer.contact': 'Kontakt',
      'footer.followUs': 'Folgen Sie uns',
      'footer.rights': 'Alle Rechte vorbehalten.',
      'footer.address': 'Kebabstraße 123',
      'footer.city': 'Europa',
      'footer.phone': '+1 (555) 123-4567',
      'footer.email': 'info@memetkebab.com',
  
      'contact.getInTouch': 'In Kontakt treten',
      'contact.message': 'Senden Sie uns eine Nachricht',
      'contact.form.name': 'Ihr Name',
      'contact.form.email': 'Ihre E-Mail',
      'contact.form.message': 'Ihre Nachricht',
      'contact.form.submit': 'Nachricht Senden',
  
      'careers.subtitle': 'Werden Sie Teil unserer wachsenden Familie',
      'careers.positions': 'Offene Stellen',
      'careers.benefits': 'Vorteile',
      'careers.benefits.health': 'Krankenversicherung',
      'careers.benefits.vacation': 'Bezahlter Urlaub',
      'careers.benefits.training': 'Professionelle Schulung',
      'careers.benefits.meals': 'Personalessen',
      'careers.benefits.growth': 'Karrierewachstum',
      'careers.apply': 'Jetzt Bewerben',
      'careers.noPositions': 'Derzeit keine offenen Stellen',
  
      'privacy.title': 'Datenschutzbestimmungen',
      'privacy.lastUpdated': 'Letzte Aktualisierung',
  
      'terms.title': 'Nutzungsbedingungen',
      'terms.lastUpdated': 'Letzte Aktualisierung',
  
      'maintenance.title': 'Wird Gewartet',
      'maintenance.message': 'Unsere Website und App werden derzeit aktualisiert, um Ihnen einen besseren Service zu bieten. Wir sind bald zurück!',
      'maintenance.status': 'In Bearbeitung',
  
      'app.subtitle': 'Laden Sie unsere mobile App herunter, um exklusive Angebote und schnellere Bestellungen zu genießen.',
      'app.features.fast': 'Schnelle und einfache Bestellung',
      'app.features.rewards': 'Sammeln Sie mit jeder Bestellung Prämien',
      'app.features.offline': 'Offline-Bestellung mit QR-Codes',
      'app.download.ios': 'Im App Store herunterladen',
      'app.download.android': 'Auf Google Play erhältlich',
  
      'careers.training.title': 'Professionelles Training',
      'careers.training.description': 'Wir bieten umfassende Schulungen an, damit Sie in Ihrer Rolle wachsen können.',
      'careers.benefits.title': 'Tolle Vorteile',
      'careers.benefits.description': 'Profitieren Sie von wettbewerbsfähiger Bezahlung, flexiblen Arbeitszeiten und Karrieremöglichkeiten.',
      'careers.team.title': 'Fantastisches Team',
      'careers.team.description': 'Arbeiten Sie mit leidenschaftlichen Menschen zusammen, die Ihre Liebe zu gutem Essen teilen.',
      'careers.positions.chef': 'Koch',
      'careers.positions.kitchen': 'Küchenpersonal',
      'careers.positions.manager': 'Restaurantmanager',
      'careers.positions.server': 'Kellner',
      'careers.positions.driver': 'Fahrer',
      'careers.form.title': 'Jetzt Bewerben',
      'careers.form.fullName': 'Vollständiger Name',
      'careers.form.email': 'E-Mail Adresse',
      'careers.form.phone': 'Telefonnummer',
      'careers.form.position': 'Position',
      'careers.form.selectPosition': 'Position Auswählen',
      'careers.form.experience': 'Jahre Erfahrung',
      'careers.form.message': 'Erzählen Sie uns von sich',
      'careers.form.submit': 'Bewerbung Abschicken',
  
      'footer.company': 'Unternehmen',
      'footer.about': 'Über Uns',
      'footer.careers': 'Karriere',
      'footer.contact': 'Kontakt',
      'footer.legal': 'Rechtliches',
      'footer.privacy': 'Datenschutzbestimmungen',
      'footer.terms': 'Nutzungsbedingungen',
      'footer.follow': 'Folgen Sie uns',
      'footer.newsletter': 'Newsletter',
      'footer.newsletterDesc': 'Abonnieren Sie, um Sonderangebote und Updates zu erhalten.',
      'footer.subscribe': 'Abonnieren',
      'footer.rights': 'Alle Rechte vorbehalten',
  
      'franchise.title': 'Werden Sie Teil der Memet Kebab Familie',
      'franchise.description': 'Werden Sie Teil unserer Erfolgsgeschichte. Eröffnen Sie Ihr eigenes Memet Kebab Franchise und bringen Sie authentische Küche in Ihre Community.',
      'franchise.cta': 'Franchisepartner werden',
      'franchise.years': 'Jahre Erfahrung',
      'franchise.customers': 'Zufriedene Kunden',
      'franchise.satisfaction': 'Partnerzufriedenheit',
      'franchise.support': 'Verfügbare Unterstützung',

    // Franchise Page
    'franchise.hero.title': 'Werden Sie Teil der Memet Kebab Familie',
    'franchise.hero.subtitle': 'Starten Sie Ihr eigenes erfolgreiches Geschäft mit einer bewährten Marke',
    'franchise.hero.cta': 'Jetzt Franchise-Partner werden',
    
    'franchise.benefits.title': 'Ihre Vorteile als Franchise-Partner',
    'franchise.benefits.subtitle': 'Profitieren Sie von unserem bewährten Geschäftsmodell',
    'franchise.benefits.proven': 'Bewährtes Konzept',
    'franchise.benefits.provenDesc': 'Ein erfolgreiches Geschäftsmodell mit nachgewiesener Rentabilität',
    'franchise.benefits.support': 'Umfassende Unterstützung',
    'franchise.benefits.supportDesc': 'Kontinuierliche Betreuung in allen Geschäftsbereichen',
    'franchise.benefits.location': 'Standortauswahl',
    'franchise.benefits.locationDesc': 'Professionelle Unterstützung bei der Standortwahl',
    'franchise.benefits.roi': 'Hohe Rendite',
    'franchise.benefits.roiDesc': 'Attraktive Gewinnmargen und schneller ROI',
    'franchise.benefits.brand': 'Starke Marke',
    'franchise.benefits.brandDesc': 'Profitieren Sie von einer etablierten Marke mit treuer Kundschaft',

    'franchise.steps.title': 'Ihr Weg zum Franchise-Partner',
    'franchise.steps.subtitle': 'In fünf Schritten zu Ihrem eigenen Memet Kebab Restaurant',
    'franchise.steps.inquiry': 'Anfrage',
    'franchise.steps.inquiryDesc': 'Kontaktieren Sie uns und teilen Sie uns Ihre Vision mit',
    'franchise.steps.evaluation': 'Evaluierung',
    'franchise.steps.evaluationDesc': 'Wir prüfen gemeinsam die Möglichkeiten',
    'franchise.steps.agreement': 'Vereinbarung',
    'franchise.steps.agreementDesc': 'Unterzeichnung des Franchise-Vertrags',
    'franchise.steps.training': 'Schulung',
    'franchise.steps.trainingDesc': 'Umfassende Einarbeitung in alle Bereiche',
    'franchise.steps.launch': 'Eröffnung',
    'franchise.steps.launchDesc': 'Eröffnung Ihres eigenen Restaurants',

    'franchise.investment.title': 'Investieren Sie in Ihre Zukunft',
    'franchise.investment.description': 'Werden Sie Teil einer wachsenden Erfolgsgeschichte im Gastrobereich',
    'franchise.investment.point1': 'Geringe Anfangsinvestition im Vergleich zum Branchendurchschnitt',
    'franchise.investment.point2': 'Schnelle Amortisation durch bewährtes Geschäftsmodell',
    'franchise.investment.point3': 'Umfassende Unterstützung bei der Finanzierung',
    'franchise.investment.form.title': 'Interessiert?',
    'franchise.investment.form.name': 'Ihr Name',
    'franchise.investment.form.email': 'Ihre E-Mail',
    'franchise.investment.form.phone': 'Ihre Telefonnummer',
    'franchise.investment.form.location': 'Gewünschter Standort',
    'franchise.investment.form.submit': 'Jetzt bewerben',

    // Locations Page
    'locations.title': 'Unsere Standorte',
    'locations.subtitle': 'Finden Sie das nächstgelegene Memet Kebab Restaurant, um Ihre Gelüste zu befriedigen',
    'locations.search.placeholder': 'Suche nach Adresse, Stadt oder Straßenname...',
    'locations.search.button': 'Nächsten Standort finden',
    'locations.search.finding': 'Standort wird gesucht...',
    'locations.status.active': 'Geöffnet',
    'locations.status.comingSoon': 'Demnächst',
    'locations.hours': 'Öffnungszeiten',
    'locations.getDirections': 'Route berechnen',
    'locations.callUs': 'Rufen Sie uns an',
    'locations.visitUs': 'Besuchen Sie uns'
  };