export const enTranslations = {
    'nav.about': 'ABOUT',
    'nav.menu': 'MENU',
    'nav.locations': 'LOCATIONS',
    'nav.contact': 'CONTACT',
    'nav.joinUs': 'JOIN US',
    'nav.orderNow': 'Order Now',
    'nav.franchise': 'FRANCHISE',
    'nav.careers': 'CAREERS',
    'nav.privacyPolicy': 'PRIVACY POLICY',
    'nav.termsOfService': 'TERMS OF SERVICE',
    
    'hero.title': 'Meet with Memet Kebab',
    'hero.subtitle': 'Experience the real "döner" with affordable prices. Bringing traditional recipes to Europe.',
    'hero.orderNow': 'Order Now',
    
    'menu.title': 'Our Menu',
    'menu.subtitle': 'Discover our selection of authentic dishes, prepared fresh daily using traditional recipes',
    'menu.specialOffer': 'Special Offer',
    'menu.viewFull': 'View Full Menu',
    'menu.viewDetails': 'View Details',
    'menu.search': 'Search menu...',
    'menu.filter': 'Filter',
    'menu.categories.all': 'All',
    'menu.categories.doner': 'Döner',
    'menu.categories.kebab': 'Kebab',
    'menu.categories.pide': 'Pide',
    'menu.categories.lahmacun': 'Lahmacun',
    'menu.categories.vegetarian': 'Vegetarian',
    'menu.categories.desserts': 'Desserts',
    'menu.categories.drinks': 'Drinks',
    'menu.reviews': 'reviews',
    
    'locations.title': 'Our Locations',
    'locations.description': 'Find your nearest Memet Kebab restaurant and experience authentic cuisine.',
    'locations.comingSoon': 'Coming Soon',
    'locations.hours': 'Opening Hours',
    'locations.phone': 'Phone',
    'locations.flagship': 'Flagship Restaurant',
    'locations.dineIn': 'Dine-in & Takeaway Available',
    'locations.capacity': 'Spacious Seating Available',
    'locations.viewMenu': 'View Menu',
    'locations.back': 'Back to Previous Page',
    'locations.expansion': 'Growing Across Europe',
    'locations.expansionText': 'Starting from our humble beginnings, we have been expanding our presence across Europe to bring authentic cuisine to more communities. Our commitment to quality and tradition remains unwavering as we grow.',
    'locations.quality': 'Quality First',
    'locations.qualityText': 'Every location maintains our high standards of food quality and service excellence.',
    'locations.tradition': 'Authentic Tradition',
    'locations.traditionText': 'We preserve our traditional recipes and cooking methods across all locations.',
    'locations.community': 'Community Focus',
    'locations.communityText': 'Each location is designed to be a welcoming gathering place for the local community.',
    'locations.franchiseTitle': 'Join the Memet Kebab Family',
    'locations.franchiseDescription': 'Interested in bringing authentic cuisine to your community? Learn about our franchise opportunities.',
    'locations.franchiseContact': 'Contact Our Franchise Team',
    'locations.franchiseEmail': 'franchise@memetkebab.com',
    'locations.franchisePhone': '+48 123 456 789',
    
    'about.title': 'Our Story',
    'about.text1': 'For decades, we have been committed to serving premium quality meat dishes across Europe. Our journey began with a simple vision: to provide authentic, high-quality food at reasonable prices.',
    'about.text2': 'Today, we continue this tradition by carefully selecting the finest cuts of meat and preparing them with expertise and passion.',
    'about.meat.title': 'Premium Quality Meat',
    'about.meat.description': 'We take pride in sourcing only the highest quality meat from trusted European suppliers. Our commitment to excellence ensures that every dish we serve meets our exacting standards.',
    'about.meat.point1': 'Premium cuts selected daily',
    'about.meat.point2': 'Certified quality assurance',
    'about.meat.point3': 'Expertly prepared by skilled chefs',
    'about.meat.detailed.description': 
      'At Memet Kebab, our foundation is built on an unwavering commitment to premium quality meat. ' +
      'We partner exclusively with renowned European suppliers who share our dedication to excellence. ' +
      'Our master butchers meticulously select each cut of meat, ensuring it meets our stringent quality criteria before it ever reaches our kitchens.\n\n' +
      'Our meat preparation process combines time-honored European butchery traditions with modern food safety standards. ' +
      'We maintain strict temperature controls and hygiene protocols throughout our supply chain, from selection to service. ' +
      'This careful attention to detail ensures that every piece of meat maintains its optimal flavor and texture.\n\n' +
      'We believe that exceptional meat quality is not just about the cut—it’s about the entire journey from farm to plate. ' +
      'That’s why we work closely with suppliers who prioritize ethical farming practices and maintain the highest standards of animal welfare. ' +
      'Our commitment to quality extends beyond taste to encompass responsibility and sustainability in every aspect of our operation.',
    'about.meat.detailed.point1': 'Our expert butchers carefully select premium cuts daily, inspecting each piece to ensure it meets our strict quality standards. This daily selection process guarantees that only the finest cuts make it to our kitchens.',
    'about.meat.detailed.point2': 'We maintain comprehensive quality control measures and work exclusively with certified European suppliers who share our commitment to excellence. Regular audits and inspections ensure consistent quality.',
    'about.meat.detailed.point3': 'Our skilled chefs bring decades of combined expertise to prepare each dish with precision and care, using traditional techniques refined over generations.',
    'about.learnMore': 'Learn More About Us',
    'about.values.title': 'Our Values',
    'about.values.description': 'Our foundation is built on values that define every aspect of our service and quality.',
    'about.values.quality.title': 'Uncompromising Quality',
    'about.values.quality.description': 'We select only premium quality meats and the freshest ingredients, partnering with trusted European suppliers who share our commitment to excellence.',
    'about.values.tradition.title': 'Heritage & Innovation',
    'about.values.tradition.description': 'We honor traditional recipes passed down through generations while embracing modern techniques to enhance your dining experience.',
    'about.values.community.title': 'Community First',
    'about.values.community.description': 'Each Memet Kebab restaurant is more than a dining spot - it’s a welcoming place where communities come together to share great food and create lasting memories.',
    'about.values.service.title': 'Excellence in Service',
    'about.values.service.description': 'We believe in treating every customer like family, providing warm, attentive service that makes your visit special.',
    'about.tradition.title': 'Our Culinary Heritage',
    'about.tradition.description': 'Our story is rooted in generations of culinary expertise, where traditional recipes have been carefully preserved and perfected.',
    'about.history': 'Our Heritage',
    'about.history.part1': 'Our story began with a simple yet powerful vision: to bring the finest, most authentic dishes to Europe. Starting with a single location, our founder was driven by an unwavering commitment to quality and authenticity. Unlike others who cut corners, we made a fundamental decision from day one: to use only real, premium-quality meat, prepared according to time-honored traditions.',
    'about.history.part2': 'This commitment to excellence meant personally selecting our meat suppliers, choosing only those who shared our dedication to quality. We established partnerships with renowned European butchers who understand that real dishes require real meat - no fillers, no compromises. Our founder spent years perfecting our signature marinade and cooking techniques, working alongside master chefs to create dishes that would set new standards in taste and quality.',
    'about.history.part3': 'Today, Memet Kebab stands as a testament to that original vision. What started as a single restaurant has grown into a beloved European brand, but our principles remain unchanged. We still personally inspect our meat suppliers, still use the same time-tested recipes, and still maintain the exacting standards that have made us a leader in authentic cuisine. Each dish we serve carries forward our legacy of culinary excellence, prepared with the same passion and attention to detail as it was on our very first day.',
    'about.commitment': 'Our Commitment',
    'about.commitment.part1': 'At Memet Kebab, our commitment extends beyond serving delicious food. We’re dedicated to creating a welcoming environment where every guest can experience exceptional hospitality. From our kitchen to your table, we ensure every detail meets our high standards of quality and authenticity. What sets us apart is our unwavering commitment to using only real, premium-grade meat in our dishes - a standard we’ve maintained since our founding.',
    'about.commitment.part2': 'We continuously strive to improve and innovate while staying true to our culinary heritage. Our meat is sourced exclusively from certified European suppliers who share our dedication to quality. Each cut is carefully selected, properly aged, and expertly prepared according to traditional methods. We never use processed meat, fillers, or artificial additives - just pure, high-quality meat that delivers the authentic taste our customers love.',
    'about.commitment.part3': 'This commitment to quality extends to every aspect of our operation. Our dishes are prepared fresh daily in each location, ensuring that every serving maintains the high standards our customers expect. Despite our dedication to premium ingredients and traditional preparation methods, we remain committed to keeping our prices affordable, making our authentic cuisine accessible to everyone without ever compromising on quality.',
    
    'features.quality': 'Premium Quality',
    'features.qualityDesc': '100% halal meat, fresh vegetables, and homemade sauces',
    'features.service': 'Fast Service',
    'features.serviceDesc': 'Quick preparation without compromising quality',
    'features.community': 'Community First',
    'features.communityDesc': 'Proudly serving our local communities',
    
    'app.title': 'Get the Memet Kebab App',
    'app.subtitle': 'Order ahead, earn rewards, and get exclusive offers!',
    'app.scan': 'Scan to download',
    'app.available': 'Available on iOS and Android',
    
    'contact.title': 'Get in Touch',
    'contact.call': 'Call Us',
    'contact.email': 'Email Us',
    'contact.visit': 'Visit Us',
    
    'careers.title': 'Join Our Team',
    'careers.description': "We're always looking for passionate people to join our growing family. Experience the joy of serving authentic cuisine while building your career.",
    'careers.button': 'View Open Positions',
    'careers.form.title': 'Join Our Team',
    'careers.form.fullName': 'Full Name',
    'careers.form.email': 'Email Address',
    'careers.form.phone': 'Phone Number',
    'careers.form.position': 'Position',
    'careers.form.selectPosition': 'Select a position',
    'careers.form.experience': 'Years of Experience',
    'careers.form.message': 'Why do you want to join our team?',
    'careers.form.submit': 'Submit Application',
    'careers.form.resume': 'Resume',
    'careers.positions.chef': 'Senior Chef',
    'careers.positions.kitchen': 'Kitchen Staff',
    'careers.positions.manager': 'Restaurant Manager',
    'careers.positions.server': 'Server',
    'careers.positions.driver': 'Delivery Driver',
    'careers.training.title': 'Training & Development',
    'careers.training.description': 'Continuous learning opportunities and career growth paths',
    'careers.benefits.title': 'Great Benefits',
    'careers.benefits.description': 'Competitive salary, health insurance, and meal allowance',
    'careers.benefits.health': 'Health Insurance',
    'careers.benefits.vacation': 'Paid Vacation',
    'careers.benefits.training': 'Professional Training',
    'careers.benefits.meals': 'Staff Meals',
    'careers.benefits.growth': 'Career Growth',
    'careers.team.title': 'Amazing Team',
    'careers.team.description': 'Join a passionate and supportive work family',
    
    'product.features.fresh': 'Made with fresh ingredients daily',
    'product.features.halal': 'Certified Halal meat',
    'product.features.made': 'Made to order',
    'product.features.chef': 'Prepared by expert chefs',
    'product.features.traditional': 'Traditional recipes',
    'product.orderNow': 'Order Now',
    'product.addFavorites': 'Add to Favorites',
    
    'products.classicDoner.title': 'Classic Döner',
    'products.classicDoner.description': 'Traditional döner with fresh vegetables and special sauce',
    'products.mixedGrill.title': 'Mixed Grill Plate',
    'products.mixedGrill.description': 'Combination of döner, served with rice and vegetables',
    'products.falafel.title': 'Vegetarian Falafel',
    'products.falafel.description': 'Homemade falafel with hummus and fresh salad',
    'products.iskender.title': 'Iskender',
    'products.iskender.description': 'Sliced döner on pide bread with yogurt and tomato sauce',
    'products.adanaKebab.title': 'Adana Kebab',
    'products.adanaKebab.description': 'Spicy minced lamb kebab served with bulgur pilaf and grilled vegetables',
    'products.cheesePide.title': 'Cheese Pide',
    'products.cheesePide.description': 'Traditional dish with mixed cheeses and herbs',
    
    'promos.familyFeast.title': 'Family Feast',
    'promos.familyFeast.description': 'Perfect for 4: Mixed grill platter, salads, rice, and drinks',
    'promos.studentSpecial.title': 'Student Special',
    'promos.studentSpecial.description': 'Show your student ID for 15% off any meal',
    'promo.firstOrder.discount': '15% OFF',
    'promo.firstOrder.text': 'On your first order',
    
    'stats.rating': '4.9 ★ Rating',
    'stats.downloads': '100K+ Downloads',
    'stats.install': 'Free Install',
    'stats.platform': 'Mobile app',
    
    'stats.happyCustomers': 'Happy Customers',
    'stats.customerRating': 'Customer Rating',
    'stats.locations': 'Locations',
    
    'menu.featuredItems': 'Featured Items',
    'menu.viewMenu': 'View Menu',
    'menu.popular': 'Popular',
    'menu.viewFullMenu': 'View Full Menu',
    'menu.specialOffers': 'Special Offers',
    'menu.limitedTime': 'Limited Time',
    'menu.order': 'Order',
    'menu.rating': '4.9',
    
    'products.classicDoner.title': 'Classic Döner',
    'products.classicDoner.description': 'Traditional dish made with premium quality meat',
    'products.mixedGrill.title': 'Mixed Grill',
    'products.mixedGrill.description': 'A delicious selection of grilled meats served with rice and vegetables',
    'products.falafel.title': 'Falafel Wrap',
    'products.falafel.description': 'Crispy falafel balls wrapped in fresh flatbread with tahini sauce',
    'products.iskender.title': 'İskender',
    'products.iskender.description': 'Sliced döner on pide bread with tomato sauce and yogurt',
    
    'promos.familyFeast.title': 'Family Feast',
    'promos.familyFeast.description': 'Perfect sharing meal for 4-6 people with a variety of kebabs and sides',
    'promos.studentSpecial.title': 'Student Special',
    'promos.studentSpecial.description': 'Show your student ID for exclusive discounts on selected meals',
    
    'contact.title': 'Get in Touch',
    'contact.call': 'Call Us',
    'contact.email': 'Email Us',
    'contact.visit': 'Visit Us',
    
    'app.comingSoon': 'Coming Soon',
    'app.downloadNow': 'Download Now',
    'app.appStore': 'App Store',
    'app.googlePlay': 'Google Play',
    'app.badge.rating': '4.9 Rating',
    'app.badge.reviews': '2k+ Reviews',
    'app.badge.downloads': '100k+',
    'app.badge.downloadsLabel': 'Downloads',
    
    'hero.badge': '#1 in Poland',
    'hero.title': 'Meet with memet Kebab',
    'hero.peoplesChoice': 'People\'s Choice',
    
    'general.back': 'Back',
    'general.viewDetails': 'View Details',
    
    'footer.description': 'Bringing authentic döner to your table. Experience the taste of tradition with Memet Kebab.',
    'footer.quickLinks': 'Quick Links',
    'footer.contact': 'Contact',
    'footer.followUs': 'Follow Us',
    'footer.rights': 'All rights reserved.',
    'footer.address': '123 Kebab Street',
    'footer.city': 'Europe',
    'footer.phone': '+1 (555) 123-4567',
    'footer.email': 'info@memetkebab.com',
    
    'nav.careers': 'Careers',
    'nav.privacyPolicy': 'Privacy Policy',
    'nav.termsOfService': 'Terms of Service',
    
    'contact.title': 'Contact Us',
    'contact.call': 'Call Us',
    'contact.email': 'Email Us',
    'contact.visit': 'Visit Us',
     'contact.getInTouch': 'Get in Touch',
      'contact.message': 'Send us a Message',
      'contact.form.name': 'Your Name',
      'contact.form.email': 'Your Email',
      'contact.form.message': 'Your Message',
      'contact.form.submit': 'Send Message',
    
    'careers.title': 'Join Our Team',
    'careers.subtitle': 'Be part of our growing family',
    'careers.description': 'At Memet Kebab, we’re always looking for passionate individuals who share our love for authentic cuisine and exceptional service.',
    'careers.positions': 'Open Positions',
    'careers.benefits': 'Benefits',
    'careers.benefits.health': 'Health Insurance',
    'careers.benefits.vacation': 'Paid Vacation',
    'careers.benefits.training': 'Professional Training',
    'careers.benefits.meals': 'Staff Meals',
    'careers.benefits.growth': 'Career Growth',
    'careers.apply': 'Apply Now',
    'careers.noPositions': 'No open positions at the moment',
    
    'privacy.title': 'Privacy Policy',
    'privacy.lastUpdated': 'Last Updated',
    
    'terms.title': 'Terms of Service',
    'terms.lastUpdated': 'Last Updated',
    
    'maintenance.title': 'Under Maintenance',
    'maintenance.message': 'Our website and app are currently being updated to serve you better. We’ll be back soon!',
    'maintenance.status': 'In Progress',

    // Franchise Page
    'franchise.hero.title': 'Join the Memet Kebab Family',
    'franchise.hero.subtitle': 'Start your own successful business with a proven brand',
    'franchise.hero.cta': 'Become a Franchise Partner',
    
    'franchise.benefits.title': 'Franchise Partnership Benefits',
    'franchise.benefits.subtitle': 'Take advantage of our proven business model',
    'franchise.benefits.proven': 'Proven Concept',
    'franchise.benefits.provenDesc': 'Successful business model with proven profitability',
    'franchise.benefits.support': 'Complete Support',
    'franchise.benefits.supportDesc': 'Ongoing assistance in all areas of operation',
    'franchise.benefits.location': 'Location Selection',
    'franchise.benefits.locationDesc': 'Professional assistance in choosing location',
    'franchise.benefits.roi': 'High ROI',
    'franchise.benefits.roiDesc': 'Attractive margins and quick investment return',
    'franchise.benefits.brand': 'Strong Brand',
    'franchise.benefits.brandDesc': 'Leverage an established brand with loyal customers',

    'franchise.steps.title': 'Path to Franchise',
    'franchise.steps.subtitle': 'Five steps to your own Memet Kebab restaurant',
    'franchise.steps.inquiry': 'Inquiry',
    'franchise.steps.inquiryDesc': 'Contact us and share your vision',
    'franchise.steps.evaluation': 'Evaluation',
    'franchise.steps.evaluationDesc': 'We explore possibilities together',
    'franchise.steps.agreement': 'Agreement',
    'franchise.steps.agreementDesc': 'Signing of franchise agreement',
    'franchise.steps.training': 'Training',
    'franchise.steps.trainingDesc': 'Comprehensive training in all areas',
    'franchise.steps.launch': 'Launch',
    'franchise.steps.launchDesc': 'Opening your own restaurant',

    'franchise.investment.title': 'Invest in Your Future',
    'franchise.investment.description': 'Be part of a growing success story in hospitality',
    'franchise.investment.point1': 'Low initial investment compared to industry average',
    'franchise.investment.point2': 'Quick return due to proven business model',
    'franchise.investment.point3': 'Complete support in financing',
    'franchise.investment.form.title': 'Interested?',
    'franchise.investment.form.name': 'Your Name',
    'franchise.investment.form.email': 'Your Email',
    'franchise.investment.form.phone': 'Your Phone Number',
    'franchise.investment.form.location': 'Desired Location',
    'franchise.investment.form.submit': 'Submit Application',
    
    'app.title': 'Order Memet Kebab from your phone',
    'app.subtitle': 'Download our mobile app to enjoy exclusive offers and faster ordering.',
    'app.features.fast': 'Fast and easy ordering',
    'app.features.rewards': 'Earn rewards with every order',
    'app.features.offline': 'Order offline with QR codes',
    'app.download.ios': 'Download on App Store',
    'app.download.android': 'Get it on Google Play',
    
    'careers.title': 'Join Our Team',
    'careers.description': 'Be part of our growing family and help us serve authentic cuisine.',
    'careers.training.title': 'Professional Training',
    'careers.training.description': 'We provide comprehensive training to help you grow in your role.',
    'careers.benefits.title': 'Great Benefits',
    'careers.benefits.description': 'Enjoy competitive pay, flexible schedules, and career growth opportunities.',
    'careers.team.title': 'Amazing Team',
    'careers.team.description': 'Work with passionate people who share your love for great food.',
    'careers.positions.chef': 'Chef',
    'careers.positions.kitchen': 'Kitchen Staff',
    'careers.positions.manager': 'Restaurant Manager',
    'careers.positions.server': 'Server',
    'careers.positions.driver': 'Delivery Driver',
     'careers.form.title': 'Apply Now',
      'careers.form.fullName': 'Full Name',
      'careers.form.email': 'Email Address',
      'careers.form.phone': 'Phone Number',
      'careers.form.position': 'Position',
      'careers.form.selectPosition': 'Select a position',
      'careers.form.experience': 'Years of Experience',
      'careers.form.message': 'Tell us about yourself',
      'careers.form.submit': 'Submit Application',
    
    'footer.company': 'Company',
    'footer.about': 'About Us',
    'footer.careers': 'Careers',
    'footer.contact': 'Contact',
    'footer.legal': 'Legal',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.follow': 'Follow Us',
    'footer.newsletter': 'Newsletter',
    'footer.newsletterDesc': 'Subscribe to get special offers and updates.',
    'footer.subscribe': 'Subscribe',
    'footer.rights': 'All rights reserved',
    
    'franchise.title': 'Join the Memet Kebab Family',
    'franchise.description': 'Be part of our success story. Open your own Memet Kebab franchise and bring authentic cuisine to your community.',
    'franchise.cta': 'Become a Franchise Partner',
    'franchise.years': 'Years of Experience',
    'franchise.customers': 'Happy Customers',
    'franchise.satisfaction': 'Partner Satisfaction',
    'franchise.support': 'Support Available',

    // Locations Page
    'locations.title': 'Our Locations',
    'locations.subtitle': 'Find the nearest Memet Kebab restaurant to satisfy your cravings',
    'locations.search.placeholder': 'Search by address, city, or street name...',
    'locations.search.button': 'Find Nearest Location',
    'locations.search.finding': 'Finding Location...',
    'locations.status.active': 'Active',
    'locations.status.comingSoon': 'Coming Soon',
    'locations.hours': 'Opening Hours',
    'locations.getDirections': 'Get Directions',
    'locations.callUs': 'Call Us',
    'locations.visitUs': 'Visit Us'
  }