export const huTranslations = {
    'nav.about': 'RÓLUNK',
    'nav.menu': 'MENÜ',
    'nav.locations': 'HELYSZÍNEK',
    'nav.contact': 'KAPCSOLAT',
    'nav.joinUs': 'CSATLAKOZZ',
    'nav.orderNow': 'RENDELÉS MOST',
    'nav.careers': 'KARRIER',
    'nav.privacyPolicy': 'ADATVÉDELMI SZABÁLYZAT',
    'nav.termsOfService': 'SZERZŐDÉSI FELTÉTELEK',
  
    'hero.title': 'Ismerje meg a Memet Kebabot',
    'hero.subtitle': 'Tapasztalja meg az igazi "dönert" megfizethető áron. Hagyományos receptek Európában.',
    'hero.orderNow': 'Rendelés Most',
  
    'menu.title': 'Étlapunk',
    'menu.subtitle': 'Fedezze fel autentikus ételeink választékát, melyeket naponta frissen készítünk hagyományos receptek alapján',
    'menu.specialOffer': 'Különleges Ajánlat',
    'menu.viewFull': 'Teljes Étlap Megtekintése',
    'menu.viewDetails': 'Részletek Megtekintése',
    'menu.search': 'Keresés a menüben...',
    'menu.filter': 'Szűrő',
    'menu.categories.all': 'Összes',
    'menu.categories.doner': 'Döner',
    'menu.categories.kebab': 'Kebab',
    'menu.categories.pide': 'Pide',
    'menu.categories.lahmacun': 'Lahmacun',
    'menu.categories.vegetarian': 'Vegetáriánus',
    'menu.categories.desserts': 'Desszertek',
    'menu.categories.drinks': 'Italok',
    'menu.reviews': 'értékelések',
  
    'locations.title': 'Helyszíneink',
    'locations.description': 'Keresse meg a legközelebbi Memet Kebab éttermet, és tapasztalja meg az autentikus konyhát.',
    'locations.comingSoon': 'Hamarosan',
    'locations.hours': 'Nyitvatartás',
    'locations.phone': 'Telefon',
    'locations.flagship': 'Zászlóshajó Étterem',
    'locations.dineIn': 'Helyben Fogyasztás és Elvitel Lehetséges',
    'locations.capacity': 'Tágas Ülőhelyek Állnak Rendelkezésre',
    'locations.viewMenu': 'Étlap Megtekintése',
    'locations.back': 'Vissza az Előző Oldalra',
    'locations.expansion': 'Terjeszkedés Európában',
    'locations.expansionText': 'Szerény kezdetektől indulva bővítjük jelenlétünket Európa-szerte, hogy az autentikus konyhát minél több közösségbe eljuttassuk. A minőség és a hagyomány iránti elkötelezettségünk változatlan marad a növekedésünk során.',
    'locations.quality': 'Első a Minőség',
    'locations.qualityText': 'Minden helyszínünkön betartjuk a magas színvonalú ételminőségi és kiváló szolgáltatási követelményeinket.',
    'locations.tradition': 'Autentikus Hagyomány',
    'locations.traditionText': 'Megőrizzük hagyományos receptjeinket és főzési módszereinket minden helyszínünkön.',
    'locations.community': 'Közösségi Fókusz',
    'locations.communityText': 'Minden helyszínünk úgy van kialakítva, hogy a helyi közösség számára egy barátságos találkozóhely legyen.',
    'locations.franchiseTitle': 'Csatlakozzon a Memet Kebab Családhoz',
    'locations.franchiseDescription': 'Érdekli, hogy autentikus konyhát hozzon a közösségébe? Ismerje meg franchise lehetőségeinket.',
    'locations.franchiseContact': 'Vegye Fel a Kapcsolatot Franchise Csapatunkkal',
    'locations.franchiseEmail': 'franchise@memetkebab.com',
    'locations.franchisePhone': '+48 123 456 789',
  
    'about.title': 'A Mi Történetünk',
    'about.text1': 'Évtizedek óta elkötelezettek vagyunk amellett, hogy Európa-szerte prémium minőségű húsételeket szolgáljunk fel. Utunk egy egyszerű elképzeléssel kezdődött: autentikus, kiváló minőségű ételeket kínálni megfizethető áron.',
    'about.text2': 'Ma is folytatjuk ezt a hagyományt azáltal, hogy gondosan válogatjuk a legjobb húsrészeket, és szakértelemmel és szenvedéllyel készítjük el azokat.',
    'about.meat.title': 'Prémium Minőségű Hús',
    'about.meat.description': 'Büszkék vagyunk arra, hogy csak a legjobb minőségű húst szerezzük be megbízható európai beszállítóktól. A kiválóság iránti elkötelezettségünk biztosítja, hogy minden általunk felszolgált étel megfeleljen szigorú követelményeinknek.',
    'about.meat.point1': 'Naponta válogatott prémium húsrészek',
    'about.meat.point2': 'Tanúsított minőségbiztosítás',
    'about.meat.point3': 'Szakértő szakácsok által készítve',
      'about.meat.detailed.description':
        'A Memet Kebabnál alapunk a prémium minőségű hús iránti megingathatatlan elkötelezettségen alapul. ' +
        'Kizárólag neves európai beszállítókkal működünk együtt, akik osztoznak a kiválóság iránti elkötelezettségünkben. ' +
        'Mesterhenteseink aprólékosan kiválasztják a hús minden egyes darabját, biztosítva, hogy az megfeleljen szigorú minőségi követelményeinknek, mielőtt valaha is eljutna a konyhánkba.\n\n' +
        'Húselőkészítési folyamatunk a régóta bevált európai hentes hagyományokat ötvözi a modern élelmiszerbiztonsági szabványokkal. ' +
        'Szigorú hőmérséklet-szabályozást és higiéniai protokollokat tartunk fenn teljes ellátási láncunkban, a kiválasztástól a kiszolgálásig. ' +
        'Ez a gondos odafigyelés a részletekre biztosítja, hogy a hús minden darabja megőrizze optimális ízét és textúráját.\n\n' +
        'Hisszük, hogy a kivételes húsminőség nem csak a vágásról szól – a teljes útról szól a gazdaságtól a tányérig. ' +
        'Ezért szorosan együttműködünk azokkal a beszállítókkal, akik prioritásként kezelik az etikus gazdálkodási gyakorlatokat, és fenntartják a legmagasabb szintű állatjóléti követelményeket. ' +
        'A minőség iránti elkötelezettségünk túlmutat az ízen, és magában foglalja a felelősséget és a fenntarthatóságot a működésünk minden aspektusában.',
      'about.meat.detailed.point1': 'Szakértő henteseink naponta gondosan válogatják a prémium minőségű vágásokat, megvizsgálva minden darabot, hogy megbizonyosodjanak arról, hogy megfelelnek szigorú minőségi követelményeinknek. Ez a napi kiválasztási folyamat garantálja, hogy csak a legjobb vágások kerülnek a konyhánkba.',
      'about.meat.detailed.point2': 'Átfogó minőség-ellenőrzési intézkedéseket tartunk fenn, és kizárólag tanúsított európai beszállítókkal működünk együtt, akik osztoznak a kiválóság iránti elkötelezettségünkben. A rendszeres ellenőrzések és ellenőrzések biztosítják a következetes minőséget.',
      'about.meat.detailed.point3': 'Képzett szakácsaink évtizedes kombinált szakértelemmel készítenek minden ételt precízen és gondosan, generációk óta tökéletesített hagyományos technikákkal.',
    'about.learnMore': 'Tudjon Meg Többet Rólunk',
    'about.values.title': 'Értékeink',
    'about.values.description': 'Alapunk olyan értékeken nyugszik, amelyek meghatározzák szolgáltatásunk és minőségünk minden aspektusát.',
    'about.values.quality.title': 'Kompromisszumok Nélküli Minőség',
    'about.values.quality.description': 'Csak prémium minőségű húst és a legfrissebb alapanyagokat választjuk ki, és megbízható európai beszállítókkal működünk együtt.',
    'about.values.tradition.title': 'Örökség és Innováció',
    'about.values.tradition.description': 'Tiszteletben tartjuk a generációkon átörökített hagyományos recepteket, miközben modern technikákat alkalmazunk az étkezési élmény fokozása érdekében.',
    'about.values.community.title': 'A Közösség az Első',
    'about.values.community.description': 'Minden Memet Kebab étterem több, mint egy étkezőhely – ez egy barátságos hely, ahol a közösségek összegyűlnek, hogy megosszák a nagyszerű ételeket.',
    'about.values.service.title': 'Kiemelkedő Szolgáltatás',
    'about.values.service.description': 'Hiszünk abban, hogy minden ügyfelet családtagként kell kezelni, meleg és figyelmes szolgáltatást nyújtva.',
    'about.tradition.title': 'Kulináris Örökségünk',
    'about.tradition.description': 'Történetünk a kulináris szakértelem generációiban gyökerezik, ahol a hagyományos recepteket gondosan megőrizték és tökéletesítették.',
      'about.history': 'Örökségünk',
      'about.history.part1': 'Történetünk egy egyszerű, mégis erőteljes vízióval kezdődött: a legfinomabb, legautentikusabb ételeket elhozni Európába. Egyetlen helyszínről indulva alapítónkat a minőség és a hitelesség iránti megingathatatlan elkötelezettség vezérelte. Ellentétben másokkal, akik spórolnak, az első naptól kezdve alapvető döntést hoztunk: csak igazi, prémium minőségű húst használunk, amelyet a régi hagyományok szerint készítünk.',
      'about.history.part2': 'Ez a kiválóság iránti elkötelezettség a hússzállítóink személyes kiválasztását jelentette, csak azokat választva, akik osztoznak a minőség iránti elkötelezettségünkben. Partnerséget kötöttünk neves európai hentesekkel, akik megértik, hogy az igazi ételekhez igazi húsra van szükség - nincs töltelék, nincs kompromisszum. Alapítónk éveket töltött jellegzetes pácunk és főzési technikáink tökéletesítésével, mesterszakácsokkal együtt dolgozva olyan ételek megalkotásán, amelyek új mércét állítanak fel az íz és a minőség terén.',
      'about.history.part3': 'Ma a Memet Kebab ennek az eredeti elképzelésnek a bizonyítéka. Ami egyetlen étteremként indult, mára egy szeretett európai márkává nőtte ki magát, de elveink változatlanok maradtak. Továbbra is személyesen ellenőrizzük hússzállítóinkat, továbbra is ugyanazokat a bevált recepteket használjuk, és továbbra is fenntartjuk azokat a pontos szabványokat, amelyek a hiteles konyha vezetőjévé tettek bennünket. Minden általunk felszolgált étel magában hordozza kulináris kiválóságunk örökségét, amelyet ugyanazzal a szenvedéllyel és figyelemmel készítünk, mint legelső napunkon.',
      'about.commitment': 'Elkötelezettségünk',
      'about.commitment.part1': 'A Memet Kebabnál elkötelezettségünk túlmutat a finom ételek felszolgálásán. Elkötelezettek vagyunk egy barátságos környezet megteremtése mellett, ahol minden vendég kivételes vendégszeretetet tapasztalhat meg. Konyhánktól az Ön asztaláig biztosítjuk, hogy minden részlet megfeleljen magas minőségi és hitelességi követelményeinknek. Ami megkülönböztet minket, az a megingathatatlan elkötelezettségünk, hogy csak valódi, prémium minőségű húst használunk ételeinkben - ezt a szabványt alapításunk óta tartjuk fenn.',
      'about.commitment.part2': 'Folyamatosan törekszünk a fejlődésre és az innovációra, miközben hűek maradunk kulináris örökségünkhöz. Húsunkat kizárólag tanúsított európai beszállítóktól szerezzük be, akik osztoznak a minőség iránti elkötelezettségünkben. Minden darabot gondosan kiválasztunk, megfelelően érlelünk és szakszerűen készítünk el a hagyományos módszereknek megfelelően. Soha nem használunk feldolgozott húst, tölteléket vagy mesterséges adalékanyagokat - csak tiszta, kiváló minőségű húst, amely azt az autentikus ízt nyújtja, amelyet ügyfeleink szeretnek.',
      'about.commitment.part3': 'Ez a minőség iránti elkötelezettség működésünk minden aspektusára kiterjed. Ételeinket naponta frissen készítjük minden helyszínen, biztosítva, hogy minden adag megfeleljen azoknak a magas követelményeknek, amelyeket ügyfeleink elvárnak. A prémium alapanyagok és a hagyományos elkészítési módszerek iránti elkötelezettségünk ellenére továbbra is elkötelezettek vagyunk az áraink megfizethető szinten tartása mellett, így autentikus konyhánk mindenki számára elérhetővé válik anélkül, hogy valaha is kompromisszumot kötnénk a minőség terén.',
  
    'features.quality': 'Prémium Minőség',
    'features.qualityDesc': '100% halal hús, friss zöldségek és házi készítésű szószok',
    'features.service': 'Gyors Kiszolgálás',
    'features.serviceDesc': 'Gyors elkészítés a minőség feláldozása nélkül',
    'features.community': 'A Közösség Az Első',
    'features.communityDesc': 'Büszkén szolgáljuk a helyi közösségeinket',
  
    'app.title': 'Szerezze meg a Memet Kebab Appot',
    'app.subtitle': 'Rendeljen előre, szerezzen jutalmakat és kapjon exkluzív ajánlatokat!',
    'app.scan': 'Szkennelje be a letöltéshez',
    'app.available': 'Elérhető iOS és Android rendszeren',
  
    'contact.title': 'Lépjen Kapcsolatba Velünk',
    'contact.call': 'Hívjon Minket',
    'contact.email': 'Írjon Nekünk',
    'contact.visit': 'Látogasson El Hozzánk',
  
    'careers.title': 'Csatlakozzon Csapatunkhoz',
    'careers.description': 'Mindig keresünk szenvedélyes embereket, akik csatlakozhatnak növekvő családunkhoz. Tapasztalja meg az autentikus konyha felszolgálásának örömét, miközben építi karrierjét.',
    'careers.button': 'Tekintse meg a Nyitott Pozíciókat',
    'careers.form.title': 'Csatlakozzon Csapatunkhoz',
    'careers.form.fullName': 'Teljes Név',
    'careers.form.email': 'E-mail Cím',
    'careers.form.phone': 'Telefonszám',
    'careers.form.position': 'Pozíció',
    'careers.form.selectPosition': 'Válasszon pozíciót',
    'careers.form.experience': 'Éves Tapasztalat',
    'careers.form.message': 'Miért szeretne csatlakozni csapatunkhoz?',
    'careers.form.submit': 'Jelentkezés Elküldése',
    'careers.form.resume': 'Önéletrajz',
    'careers.positions.chef': 'Séf',
    'careers.positions.kitchen': 'Konyhai Személyzet',
    'careers.positions.manager': 'Étteremvezető',
    'careers.positions.server': 'Pincér',
    'careers.positions.driver': 'Kiszállító Sofőr',
    'careers.training.title': 'Képzés és Fejlesztés',
    'careers.training.description': 'Folyamatos tanulási lehetőségek és karrierépítési utak',
    'careers.benefits.title': 'Nagyszerű Juttatások',
    'careers.benefits.description': 'Versenyképes fizetés, egészségbiztosítás és étkezési támogatás',
    'careers.team.title': 'Csodálatos Csapat',
    'careers.team.description': 'Csatlakozzon egy szenvedélyes és támogató munkacsoporthoz',
  
    'product.features.fresh': 'Naponta friss alapanyagokból készül',
    'product.features.halal': 'Tanúsított Halal hús',
    'product.features.made': 'Rendelésre készül',
    'product.features.chef': 'Szakértő szakácsok által készítve',
    'product.features.traditional': 'Hagyományos receptek',
    'product.orderNow': 'Rendelés Most',
    'product.addFavorites': 'Hozzáadás a Kedvencekhez',
  
    'products.classicDoner.title': 'Klasszikus Döner',
    'products.classicDoner.description': 'Hagyományos döner friss zöldségekkel és speciális szósszal',
    'products.mixedGrill.title': 'Vegyes Grilltál',
    'products.mixedGrill.description': 'Döner kombinációja, rizzsel és zöldségekkel tálalva',
    'products.falafel.title': 'Vegetáriánus Falafel',
    'products.falafel.description': 'Házi készítésű falafel humusszal és friss salátával',
    'products.iskender.title': 'Iskender',
    'products.iskender.description': 'Szeletelt döner pide kenyéren joghurttal és paradicsomszósszal',
    'products.adanaKebab.title': 'Adana Kebab',
    'products.adanaKebab.description': 'Fűszeres darált bárány kebab bulgur piláffal és grillezett zöldségekkel tálalva',
    'products.cheesePide.title': 'Sajtos Pide',
    'products.cheesePide.description': 'Hagyományos étel vegyes sajtokkal és gyógynövényekkel',
  
    'promos.familyFeast.title': 'Családi Lakoma',
    'promos.familyFeast.description': 'Tökéletes 4 főre: Vegyes grilltál, saláták, rizs és italok',
    'promos.studentSpecial.title': 'Diák Akció',
    'promos.studentSpecial.description': 'Mutassa fel diákigazolványát, és 15% kedvezményt kap bármelyik ételre',
    'promo.firstOrder.discount': '15% KEDVEZMÉNY',
    'promo.firstOrder.text': 'Az első rendelésére',
  
    'stats.rating': '4.9 ★ Értékelés',
    'stats.downloads': '100K+ Letöltés',
    'stats.install': 'Ingyenes Telepítés',
    'stats.platform': 'Mobilalkalmazás',
  
    'stats.happyCustomers': 'Boldog Vásárlók',
    'stats.customerRating': 'Vásárlói Értékelés',
    'stats.locations': 'Helyszínek',
  
    'menu.featuredItems': 'Kiemelt Termékek',
    'menu.viewMenu': 'Étlap Megtekintése',
    'menu.popular': 'Népszerű',
    'menu.viewFullMenu': 'Teljes Étlap Megtekintése',
    'menu.specialOffers': 'Különleges Ajánlatok',
    'menu.limitedTime': 'Korlátozott Ideig',
    'menu.order': 'Rendelés',
    'menu.rating': '4.9',
  
      'products.classicDoner.title': 'Klasszikus Döner',
      'products.classicDoner.description': 'Hagyományos étel prémium minőségű húsból',
      'products.mixedGrill.title': 'Vegyes Grill',
      'products.mixedGrill.description': 'Finom válogatás grillezett húsokból rizzsel és zöldségekkel tálalva',
      'products.falafel.title': 'Falafel Wrap',
      'products.falafel.description': 'Ropogós falafel golyók friss lepénybe csomagolva tahini szósszal',
      'products.iskender.title': 'İskender',
      'products.iskender.description': 'Szeletelt döner pide kenyéren paradicsomszósszal és joghurttal',
  
      'promos.familyFeast.title': 'Családi Lakoma',
      'promos.familyFeast.description': 'Tökéletes megosztó étel 4-6 fő részére különféle kebabokkal és köretekkel',
      'promos.studentSpecial.title': 'Diák Akció',
      'promos.studentSpecial.description': 'Mutassa fel diákigazolványát, hogy exkluzív kedvezményeket kapjon a kiválasztott ételekre',
  
      'contact.title': 'Lépjen Kapcsolatba Velünk',
      'contact.call': 'Hívjon Minket',
      'contact.email': 'Írjon Nekünk',
      'contact.visit': 'Látogasson El Hozzánk',
  
      'app.comingSoon': 'Hamarosan',
      'app.downloadNow': 'Letöltés Most',
      'app.appStore': 'App Store',
      'app.googlePlay': 'Google Play',
      'app.badge.rating': 'Értékelés 4.9',
      'app.badge.reviews': '2k+ Vélemény',
      'app.badge.downloads': '100k+',
      'app.badge.downloadsLabel': 'Letöltések',
  
      'hero.badge': '#1 Lengyelországban',  // Verify market-specific badge
      'hero.title': 'Ismerje meg a Memet Kebabot',
      'hero.peoplesChoice': 'A Nép Választása',
  
      'general.back': 'Vissza',
      'general.viewDetails': 'Részletek Megtekintése',
  
      'footer.description': 'Autentikus dönert hozunk az asztalára. Tapasztalja meg a hagyományok ízét a Memet Kebabbal.',
      'footer.quickLinks': 'Gyorslinkek',
      'footer.contact': 'Kapcsolat',
      'footer.followUs': 'Kövessen Minket',
      'footer.rights': 'Minden jog fenntartva.',
      'footer.address': 'Kebab utca 123.',
      'footer.city': 'Európa',
      'footer.phone': '+1 (555) 123-4567',
      'footer.email': 'info@memetkebab.com',
  
      'contact.getInTouch': 'Lépjen Kapcsolatba',
      'contact.message': 'Küldjön nekünk üzenetet',
      'contact.form.name': 'Az Ön Neve',
      'contact.form.email': 'Az Ön E-mail Címe',
      'contact.form.message': 'Az Ön Üzenete',
      'contact.form.submit': 'Üzenet Küldése',
  
      'careers.subtitle': 'Legyen része a növekvő családunknak',
      'careers.positions': 'Nyitott Pozíciók',
      'careers.benefits': 'Juttatások',
      'careers.benefits.health': 'Egészségbiztosítás',
      'careers.benefits.vacation': 'Fizetett Szabadság',
      'careers.benefits.training': 'Szakmai Képzés',
      'careers.benefits.meals': 'Étkezés a Személyzetnek',
      'careers.benefits.growth': 'Karrierépítés',
      'careers.apply': 'Jelentkezés Most',
      'careers.noPositions': 'Jelenleg nincsenek nyitott pozíciók',
  
      'privacy.title': 'Adatvédelmi Szabályzat',
      'privacy.lastUpdated': 'Utolsó Frissítés',
  
      'terms.title': 'Szolgáltatási Feltételek',
      'terms.lastUpdated': 'Utolsó Frissítés',
  
      'maintenance.title': 'Karbantartás Alatt',
      'maintenance.message': 'Weboldalunk és alkalmazásunk jelenleg frissítés alatt áll, hogy jobban kiszolgálhassuk Önt. Hamarosan visszatérünk!',
      'maintenance.status': 'Folyamatban',
  
      'app.subtitle': 'Töltse le mobilalkalmazásunkat, hogy exkluzív ajánlatokat és gyorsabb rendelést élvezhessen.',
      'app.features.fast': 'Gyors és egyszerű rendelés',
      'app.features.rewards': 'Keressen jutalmakat minden rendelésével',
      'app.features.offline': 'Rendeljen offline QR-kódokkal',
      'app.download.ios': 'Letöltés az App Store-ból',
      'app.download.android': 'Szerezze be a Google Play-en',
  
      'careers.training.title': 'Szakmai Képzés',
      'careers.training.description': 'Átfogó képzést biztosítunk, hogy segítsük a fejlődését a szerepében.',
      'careers.benefits.title': 'Nagyszerű Juttatások',
      'careers.benefits.description': 'Élvezze a versenyképes fizetést, a rugalmas munkaidőt és a karrierépítési lehetőségeket.',
      'careers.team.title': 'Csodálatos Csapat',
      'careers.team.description': 'Dolgozzon szenvedélyes emberekkel, akik osztoznak a jó ételek iránti szeretetében.',
      'careers.positions.chef': 'Szakács',
      'careers.positions.kitchen': 'Konyhai Személyzet',
      'careers.positions.manager': 'Étteremvezető',
      'careers.positions.server': 'Pincér',
      'careers.positions.driver': 'Sofőr',
      'careers.form.title': 'Jelentkezés Most',
      'careers.form.fullName': 'Teljes Név',
      'careers.form.email': 'E-mail Cím',
      'careers.form.phone': 'Telefonszám',
      'careers.form.position': 'Pozíció',
      'careers.form.selectPosition': 'Pozíció Kiválasztása',
      'careers.form.experience': 'Éves Tapasztalat',
      'careers.form.message': 'Mondjon Nekünk Valamit Magáról',
      'careers.form.submit': 'Jelentkezés Elküldése',
  
      'footer.company': 'Vállalat',
      'footer.about': 'Rólunk',
      'footer.careers': 'Karrier',
      'footer.contact': 'Kapcsolat',
      'footer.legal': 'Jogi Tudnivalók',
      'footer.privacy': 'Adatvédelmi Szabályzat',
      'footer.terms': 'Szolgáltatási Feltételek',
      'footer.follow': 'Kövessen Minket',
      'footer.newsletter': 'Hírlevél',
      'footer.newsletterDesc': 'Iratkozzon fel, hogy különleges ajánlatokat és frissítéseket kapjon.',
      'footer.subscribe': 'Feliratkozás',
      'footer.rights': 'Minden jog fenntartva',
  
      'franchise.title': 'Csatlakozzon a Memet Kebab családhoz',
      'franchise.description': 'Legyen része sikertörténetünknek. Nyisson saját Memet Kebab franchise-t, és hozza el az autentikus konyhát a közösségébe.',
      'franchise.cta': 'Legyen Franchise Partner',
      'franchise.years': 'Éves Tapasztalat',
      'franchise.customers': 'Elégedett Ügyfelek',
      'franchise.satisfaction': 'Partneri Elégedettség',
      'franchise.support': 'Elérhető Támogatás',

    // Franchise Page
    'franchise.hero.title': 'Csatlakozzon a Memet Kebab családhoz',
    'franchise.hero.subtitle': 'Indítsa el saját sikeres vállalkozását egy bizonyított márkával',
    'franchise.hero.cta': 'Legyen franchise partner',
    
    'franchise.benefits.title': 'Franchise partnerek előnyei',
    'franchise.benefits.subtitle': 'Használja ki bizonyított üzleti modellünk előnyeit',
    'franchise.benefits.proven': 'Bizonyított koncepció',
    'franchise.benefits.provenDesc': 'Sikeres üzleti modell bizonyított jövedelmezőséggel',
    'franchise.benefits.support': 'Átfogó támogatás',
    'franchise.benefits.supportDesc': 'Folyamatos támogatás minden üzleti területen',
    'franchise.benefits.location': 'Helyszínválasztás',
    'franchise.benefits.locationDesc': 'Szakmai segítség a helyszínválasztásban',
    'franchise.benefits.roi': 'Magas megtérülés',
    'franchise.benefits.roiDesc': 'Vonzó profités gyors befektetés-megtérülés',
    'franchise.benefits.brand': 'Erős márka',
    'franchise.benefits.brandDesc': 'Használja ki egy bevezett márka előnyeit hűséges vásárlókkal',

    'franchise.steps.title': 'Útja a franchise partnerséghez',
    'franchise.steps.subtitle': 'Öt lépés a saját Memet Kebab étterméhez',
    'franchise.steps.inquiry': 'Érdeklődés',
    'franchise.steps.inquiryDesc': 'Lépjen kapcsolatba velünk és ossza meg velünk elképzeléseit',
    'franchise.steps.evaluation': 'Értékelés',
    'franchise.steps.evaluationDesc': 'Közösen megvizsgáljuk a lehetőségeket',
    'franchise.steps.agreement': 'Megállapodás',
    'franchise.steps.agreementDesc': 'Franchise szerződés aláírása',
    'franchise.steps.training': 'Képzés',
    'franchise.steps.trainingDesc': 'Átfogó képzés minden területen',
    'franchise.steps.launch': 'Nyitás',
    'franchise.steps.launchDesc': 'Saját éttermének megnyitása',

    'franchise.investment.title': 'Fektessen a jövőjébe',
    'franchise.investment.description': 'Legyen része egy növekvő sikertörténetnek a vendéglátásban',
    'franchise.investment.point1': 'Alacsony kezdeti befektetés az iparági átlaghoz képest',
    'franchise.investment.point2': 'Gyors megtérülés a bizonyított üzleti modellnek köszönhetően',
    'franchise.investment.point3': 'Átfogó támogatás a finanszírozásban',
    'franchise.investment.form.title': 'Érdekli?',
    'franchise.investment.form.name': 'Az Ön neve',
    'franchise.investment.form.email': 'Az Ön e-mail címe',
    'franchise.investment.form.phone': 'Az Ön telefonszáma',
    'franchise.investment.form.location': 'Kívánt helyszín',
    'franchise.investment.form.submit': 'Jelentkezés küldése',

    // Locations Page
    'locations.title': 'Üzleteink',
    'locations.subtitle': 'Találja meg a legközelebbi Memet Kebab éttermet és elégítse ki étvágyát',
    'locations.search.placeholder': 'Keressen cím, város vagy utcanév alapján...',
    'locations.search.button': 'Legközelebbi üzlet keresése',
    'locations.search.finding': 'Üzlet keresése...',
    'locations.status.active': 'Nyitva',
    'locations.status.comingSoon': 'Hamarosan',
    'locations.hours': 'Nyitvatartás',
    'locations.getDirections': 'Útvonaltervezés',
    'locations.callUs': 'Hívjon minket',
    'locations.visitUs': 'Látogasson meg'
  };