import React, { createContext, useContext, useState, useEffect } from 'react';
import Cookies from 'js-cookie';

type Language = 'en' | 'pl' | 'ro';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    'nav.about': 'ABOUT',
    'nav.menu': 'MENU',
    'nav.locations': 'LOCATIONS',
    'nav.contact': 'CONTACT',
    'nav.joinUs': 'JOIN US',
    'nav.orderNow': 'Order Now',
    'nav.careers': 'CAREERS',
    'nav.privacyPolicy': 'PRIVACY POLICY',
    'nav.termsOfService': 'TERMS OF SERVICE',
    
    'hero.title': 'Meet with Memet Kebab',
    'hero.subtitle': 'Experience the real "döner" with affordable prices. Bringing traditional recipes to Europe.',
    'hero.orderNow': 'Order Now',
    
    'menu.title': 'Our Menu',
    'menu.subtitle': 'Discover our selection of authentic dishes, prepared fresh daily using traditional recipes',
    'menu.specialOffer': 'Special Offer',
    'menu.viewFull': 'View Full Menu',
    'menu.viewDetails': 'View Details',
    'menu.search': 'Search menu...',
    'menu.filter': 'Filter',
    'menu.categories.all': 'All',
    'menu.categories.doner': 'Döner',
    'menu.categories.kebab': 'Kebab',
    'menu.categories.pide': 'Pide',
    'menu.categories.lahmacun': 'Lahmacun',
    'menu.categories.vegetarian': 'Vegetarian',
    'menu.categories.desserts': 'Desserts',
    'menu.categories.drinks': 'Drinks',
    'menu.reviews': 'reviews',
    
    'locations.title': 'Our Locations',
    'locations.description': 'Find your nearest Memet Kebab restaurant and experience authentic cuisine.',
    'locations.comingSoon': 'Coming Soon',
    'locations.hours': 'Opening Hours',
    'locations.phone': 'Phone',
    'locations.flagship': 'Flagship Restaurant',
    'locations.dineIn': 'Dine-in & Takeaway Available',
    'locations.capacity': 'Spacious Seating Available',
    'locations.viewMenu': 'View Menu',
    'locations.back': 'Back to Previous Page',
    'locations.expansion': 'Growing Across Europe',
    'locations.expansionText': 'Starting from our humble beginnings, we have been expanding our presence across Europe to bring authentic cuisine to more communities. Our commitment to quality and tradition remains unwavering as we grow.',
    'locations.quality': 'Quality First',
    'locations.qualityText': 'Every location maintains our high standards of food quality and service excellence.',
    'locations.tradition': 'Authentic Tradition',
    'locations.traditionText': 'We preserve our traditional recipes and cooking methods across all locations.',
    'locations.community': 'Community Focus',
    'locations.communityText': 'Each location is designed to be a welcoming gathering place for the local community.',
    'locations.franchiseTitle': 'Join the Memet Kebab Family',
    'locations.franchiseDescription': 'Interested in bringing authentic cuisine to your community? Learn about our franchise opportunities.',
    'locations.franchiseContact': 'Contact Our Franchise Team',
    'locations.franchiseEmail': 'franchise@memetkebab.com',
    'locations.franchisePhone': '+48 123 456 789',
    
    'about.title': 'Our Story',
    'about.text1': 'For decades, we have been committed to serving premium quality meat dishes across Europe. Our journey began with a simple vision: to provide authentic, high-quality food at reasonable prices.',
    'about.text2': 'Today, we continue this tradition by carefully selecting the finest cuts of meat and preparing them with expertise and passion.',
    'about.meat.title': 'Premium Quality Meat',
    'about.meat.description': 'We take pride in sourcing only the highest quality meat from trusted European suppliers. Our commitment to excellence ensures that every dish we serve meets our exacting standards.',
    'about.meat.point1': 'Premium cuts selected daily',
    'about.meat.point2': 'Certified quality assurance',
    'about.meat.point3': 'Expertly prepared by skilled chefs',
    'about.meat.detailed.description': 
      'At Memet Kebab, our foundation is built on an unwavering commitment to premium quality meat. ' +
      'We partner exclusively with renowned European suppliers who share our dedication to excellence. ' +
      'Our master butchers meticulously select each cut of meat, ensuring it meets our stringent quality criteria before it ever reaches our kitchens.\n\n' +
      'Our meat preparation process combines time-honored European butchery traditions with modern food safety standards. ' +
      'We maintain strict temperature controls and hygiene protocols throughout our supply chain, from selection to service. ' +
      'This careful attention to detail ensures that every piece of meat maintains its optimal flavor and texture.\n\n' +
      'We believe that exceptional meat quality is not just about the cut—it’s about the entire journey from farm to plate. ' +
      'That’s why we work closely with suppliers who prioritize ethical farming practices and maintain the highest standards of animal welfare. ' +
      'Our commitment to quality extends beyond taste to encompass responsibility and sustainability in every aspect of our operation.',
    'about.meat.detailed.point1': 'Our expert butchers carefully select premium cuts daily, inspecting each piece to ensure it meets our strict quality standards. This daily selection process guarantees that only the finest cuts make it to our kitchens.',
    'about.meat.detailed.point2': 'We maintain comprehensive quality control measures and work exclusively with certified European suppliers who share our commitment to excellence. Regular audits and inspections ensure consistent quality.',
    'about.meat.detailed.point3': 'Our skilled chefs bring decades of combined expertise to prepare each dish with precision and care, using traditional techniques refined over generations.',
    'about.learnMore': 'Learn More About Us',
    'about.values.title': 'Our Values',
    'about.values.description': 'Our foundation is built on values that define every aspect of our service and quality.',
    'about.values.quality.title': 'Uncompromising Quality',
    'about.values.quality.description': 'We select only premium quality meats and the freshest ingredients, partnering with trusted European suppliers who share our commitment to excellence.',
    'about.values.tradition.title': 'Heritage & Innovation',
    'about.values.tradition.description': 'We honor traditional recipes passed down through generations while embracing modern techniques to enhance your dining experience.',
    'about.values.community.title': 'Community First',
    'about.values.community.description': 'Each Memet Kebab restaurant is more than a dining spot - it’s a welcoming place where communities come together to share great food and create lasting memories.',
    'about.values.service.title': 'Excellence in Service',
    'about.values.service.description': 'We believe in treating every customer like family, providing warm, attentive service that makes your visit special.',
    'about.tradition.title': 'Our Culinary Heritage',
    'about.tradition.description': 'Our story is rooted in generations of culinary expertise, where traditional recipes have been carefully preserved and perfected.',
    'about.history': 'Our Heritage',
    'about.history.part1': 'Our story began with a simple yet powerful vision: to bring the finest, most authentic dishes to Europe. Starting with a single location, our founder was driven by an unwavering commitment to quality and authenticity. Unlike others who cut corners, we made a fundamental decision from day one: to use only real, premium-quality meat, prepared according to time-honored traditions.',
    'about.history.part2': 'This commitment to excellence meant personally selecting our meat suppliers, choosing only those who shared our dedication to quality. We established partnerships with renowned European butchers who understand that real dishes require real meat - no fillers, no compromises. Our founder spent years perfecting our signature marinade and cooking techniques, working alongside master chefs to create dishes that would set new standards in taste and quality.',
    'about.history.part3': 'Today, Memet Kebab stands as a testament to that original vision. What started as a single restaurant has grown into a beloved European brand, but our principles remain unchanged. We still personally inspect our meat suppliers, still use the same time-tested recipes, and still maintain the exacting standards that have made us a leader in authentic cuisine. Each dish we serve carries forward our legacy of culinary excellence, prepared with the same passion and attention to detail as it was on our very first day.',
    'about.commitment': 'Our Commitment',
    'about.commitment.part1': 'At Memet Kebab, our commitment extends beyond serving delicious food. We’re dedicated to creating a welcoming environment where every guest can experience exceptional hospitality. From our kitchen to your table, we ensure every detail meets our high standards of quality and authenticity. What sets us apart is our unwavering commitment to using only real, premium-grade meat in our dishes - a standard we’ve maintained since our founding.',
    'about.commitment.part2': 'We continuously strive to improve and innovate while staying true to our culinary heritage. Our meat is sourced exclusively from certified European suppliers who share our dedication to quality. Each cut is carefully selected, properly aged, and expertly prepared according to traditional methods. We never use processed meat, fillers, or artificial additives - just pure, high-quality meat that delivers the authentic taste our customers love.',
    'about.commitment.part3': 'This commitment to quality extends to every aspect of our operation. Our dishes are prepared fresh daily in each location, ensuring that every serving maintains the high standards our customers expect. Despite our dedication to premium ingredients and traditional preparation methods, we remain committed to keeping our prices affordable, making our authentic cuisine accessible to everyone without ever compromising on quality.',
    
    'features.quality': 'Premium Quality',
    'features.qualityDesc': '100% halal meat, fresh vegetables, and homemade sauces',
    'features.service': 'Fast Service',
    'features.serviceDesc': 'Quick preparation without compromising quality',
    'features.community': 'Community First',
    'features.communityDesc': 'Proudly serving our local communities',
    
    'app.title': 'Get the Memet Kebab App',
    'app.subtitle': 'Order ahead, earn rewards, and get exclusive offers!',
    'app.scan': 'Scan to download',
    'app.available': 'Available on iOS and Android',
    
    'contact.title': 'Get in Touch',
    'contact.call': 'Call Us',
    'contact.email': 'Email Us',
    'contact.visit': 'Visit Us',
    
    'careers.title': 'Join Our Team',
    'careers.description': "We're always looking for passionate people to join our growing family. Experience the joy of serving authentic cuisine while building your career.",
    'careers.button': 'View Open Positions',
    'careers.form.title': 'Join Our Team',
    'careers.form.fullName': 'Full Name',
    'careers.form.email': 'Email Address',
    'careers.form.phone': 'Phone Number',
    'careers.form.position': 'Position',
    'careers.form.selectPosition': 'Select a position',
    'careers.form.experience': 'Years of Experience',
    'careers.form.message': 'Why do you want to join our team?',
    'careers.form.submit': 'Submit Application',
    'careers.form.resume': 'Resume',
    'careers.positions.chef': 'Senior Chef',
    'careers.positions.kitchen': 'Kitchen Staff',
    'careers.positions.manager': 'Restaurant Manager',
    'careers.positions.server': 'Server',
    'careers.positions.driver': 'Delivery Driver',
    'careers.training.title': 'Training & Development',
    'careers.training.description': 'Continuous learning opportunities and career growth paths',
    'careers.benefits.title': 'Great Benefits',
    'careers.benefits.description': 'Competitive salary, health insurance, and meal allowance',
    'careers.benefits.health': 'Health Insurance',
    'careers.benefits.vacation': 'Paid Vacation',
    'careers.benefits.training': 'Professional Training',
    'careers.benefits.meals': 'Staff Meals',
    'careers.benefits.growth': 'Career Growth',
    'careers.team.title': 'Amazing Team',
    'careers.team.description': 'Join a passionate and supportive work family',
    
    'product.features.fresh': 'Made with fresh ingredients daily',
    'product.features.halal': 'Certified Halal meat',
    'product.features.made': 'Made to order',
    'product.features.chef': 'Prepared by expert chefs',
    'product.features.traditional': 'Traditional recipes',
    'product.orderNow': 'Order Now',
    'product.addFavorites': 'Add to Favorites',
    
    'products.classicDoner.title': 'Classic Döner',
    'products.classicDoner.description': 'Traditional döner with fresh vegetables and special sauce',
    'products.mixedGrill.title': 'Mixed Grill Plate',
    'products.mixedGrill.description': 'Combination of döner, served with rice and vegetables',
    'products.falafel.title': 'Vegetarian Falafel',
    'products.falafel.description': 'Homemade falafel with hummus and fresh salad',
    'products.iskender.title': 'Iskender',
    'products.iskender.description': 'Sliced döner on pide bread with yogurt and tomato sauce',
    'products.adanaKebab.title': 'Adana Kebab',
    'products.adanaKebab.description': 'Spicy minced lamb kebab served with bulgur pilaf and grilled vegetables',
    'products.cheesePide.title': 'Cheese Pide',
    'products.cheesePide.description': 'Traditional dish with mixed cheeses and herbs',
    
    'promos.familyFeast.title': 'Family Feast',
    'promos.familyFeast.description': 'Perfect for 4: Mixed grill platter, salads, rice, and drinks',
    'promos.studentSpecial.title': 'Student Special',
    'promos.studentSpecial.description': 'Show your student ID for 15% off any meal',
    'promo.firstOrder.discount': '15% OFF',
    'promo.firstOrder.text': 'On your first order',
    
    'stats.rating': '4.9 ★ Rating',
    'stats.downloads': '100K+ Downloads',
    'stats.install': 'Free Install',
    'stats.platform': 'Mobile app',
    
    'stats.happyCustomers': 'Happy Customers',
    'stats.customerRating': 'Customer Rating',
    'stats.locations': 'Locations',
    
    'menu.featuredItems': 'Featured Items',
    'menu.viewMenu': 'View Menu',
    'menu.popular': 'Popular',
    'menu.viewFullMenu': 'View Full Menu',
    'menu.specialOffers': 'Special Offers',
    'menu.limitedTime': 'Limited Time',
    'menu.order': 'Order',
    'menu.rating': '4.9',
    
    'products.classicDoner.title': 'Classic Döner',
    'products.classicDoner.description': 'Traditional dish made with premium quality meat',
    'products.mixedGrill.title': 'Mixed Grill',
    'products.mixedGrill.description': 'A delicious selection of grilled meats served with rice and vegetables',
    'products.falafel.title': 'Falafel Wrap',
    'products.falafel.description': 'Crispy falafel balls wrapped in fresh flatbread with tahini sauce',
    'products.iskender.title': 'İskender',
    'products.iskender.description': 'Sliced döner on pide bread with tomato sauce and yogurt',
    
    'promos.familyFeast.title': 'Family Feast',
    'promos.familyFeast.description': 'Perfect sharing meal for 4-6 people with a variety of kebabs and sides',
    'promos.studentSpecial.title': 'Student Special',
    'promos.studentSpecial.description': 'Show your student ID for exclusive discounts on selected meals',
    
    'contact.title': 'Get in Touch',
    'contact.call': 'Call Us',
    'contact.email': 'Email Us',
    'contact.visit': 'Visit Us',
    
    'app.comingSoon': 'Coming Soon',
    'app.downloadNow': 'Download Now',
    'app.appStore': 'App Store',
    'app.googlePlay': 'Google Play',
    'app.badge.rating': '4.9 Rating',
    'app.badge.reviews': '2k+ Reviews',
    'app.badge.downloads': '100k+',
    'app.badge.downloadsLabel': 'Downloads',
    
    'hero.badge': '#1 in Poland',
    'hero.title': 'Meet with memet Kebab',
    'hero.peoplesChoice': 'People\'s Choice',
    
    'general.back': 'Back',
    'general.viewDetails': 'View Details',
    
    'footer.description': 'Bringing authentic döner to your table. Experience the taste of tradition with Memet Kebab.',
    'footer.quickLinks': 'Quick Links',
    'footer.contact': 'Contact',
    'footer.followUs': 'Follow Us',
    'footer.rights': 'All rights reserved.',
    'footer.address': '123 Kebab Street',
    'footer.city': 'Europe',
    'footer.phone': '+1 (555) 123-4567',
    'footer.email': 'info@memetkebab.com',
    
    'nav.careers': 'Careers',
    'nav.privacyPolicy': 'Privacy Policy',
    'nav.termsOfService': 'Terms of Service',
    
    'contact.title': 'Contact Us',
    'contact.call': 'Call Us',
    'contact.email': 'Email Us',
    'contact.visit': 'Visit Us',
    'contact.getInTouch': 'Get in Touch',
    'contact.message': 'Send us a Message',
    'contact.form.name': 'Your Name',
    'contact.form.email': 'Your Email',
    'contact.form.message': 'Your Message',
    'contact.form.submit': 'Send Message',
    
    'careers.title': 'Join Our Team',
    'careers.subtitle': 'Be part of our growing family',
    'careers.description': 'At Memet Kebab, we’re always looking for passionate individuals who share our love for authentic cuisine and exceptional service.',
    'careers.positions': 'Open Positions',
    'careers.benefits': 'Benefits',
    'careers.benefits.health': 'Health Insurance',
    'careers.benefits.vacation': 'Paid Vacation',
    'careers.benefits.training': 'Professional Training',
    'careers.benefits.meals': 'Staff Meals',
    'careers.benefits.growth': 'Career Growth',
    'careers.apply': 'Apply Now',
    'careers.noPositions': 'No open positions at the moment',
    
    'privacy.title': 'Privacy Policy',
    'privacy.lastUpdated': 'Last Updated',
    
    'terms.title': 'Terms of Service',
    'terms.lastUpdated': 'Last Updated',
    
    'maintenance.title': 'Under Maintenance',
    'maintenance.message': 'Our website and app are currently being updated to serve you better. We’ll be back soon!',
    'maintenance.status': 'In Progress',
    
    'app.title': 'Order Memet Kebab from your phone',
    'app.subtitle': 'Download our mobile app to enjoy exclusive offers and faster ordering.',
    'app.features.fast': 'Fast and easy ordering',
    'app.features.rewards': 'Earn rewards with every order',
    'app.features.offline': 'Order offline with QR codes',
    'app.download.ios': 'Download on App Store',
    'app.download.android': 'Get it on Google Play',
    
    'careers.title': 'Join Our Team',
    'careers.description': 'Be part of our growing family and help us serve authentic cuisine.',
    'careers.training.title': 'Professional Training',
    'careers.training.description': 'We provide comprehensive training to help you grow in your role.',
    'careers.benefits.title': 'Great Benefits',
    'careers.benefits.description': 'Enjoy competitive pay, flexible schedules, and career growth opportunities.',
    'careers.team.title': 'Amazing Team',
    'careers.team.description': 'Work with passionate people who share your love for great food.',
    'careers.positions.chef': 'Chef',
    'careers.positions.kitchen': 'Kitchen Staff',
    'careers.positions.manager': 'Restaurant Manager',
    'careers.positions.server': 'Server',
    'careers.positions.driver': 'Delivery Driver',
    'careers.form.title': 'Apply Now',
    'careers.form.fullName': 'Full Name',
    'careers.form.email': 'Email Address',
    'careers.form.phone': 'Phone Number',
    'careers.form.position': 'Position',
    'careers.form.selectPosition': 'Select a position',
    'careers.form.experience': 'Years of Experience',
    'careers.form.message': 'Tell us about yourself',
    'careers.form.submit': 'Submit Application',
    
    'footer.company': 'Company',
    'footer.about': 'About Us',
    'footer.careers': 'Careers',
    'footer.contact': 'Contact',
    'footer.legal': 'Legal',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.follow': 'Follow Us',
    'footer.newsletter': 'Newsletter',
    'footer.newsletterDesc': 'Subscribe to get special offers and updates.',
    'footer.subscribe': 'Subscribe',
    'footer.rights': 'All rights reserved',
    
    'franchise.title': 'Join the Memet Kebab Family',
    'franchise.description': 'Be part of our success story. Open your own Memet Kebab franchise and bring authentic cuisine to your community.',
    'franchise.cta': 'Become a Franchise Partner',
    'franchise.years': 'Years of Experience',
    'franchise.customers': 'Happy Customers',
    'franchise.satisfaction': 'Partner Satisfaction',
    'franchise.support': 'Support Available',
  },
  pl: {
    'nav.about': 'O NAS',
    'nav.menu': 'MENU',
    'nav.locations': 'LOKALIZACJE',
    'nav.contact': 'KONTAKT',
    'nav.joinUs': 'DOŁĄCZ',
    'nav.orderNow': 'Zamów Teraz',
    
    'hero.title': 'Autentyczny',
    'hero.subtitle': 'Doświadcz prawdziwego smaku, przynosząc autentyczne smaki z serca Europy do całej Europy.',
    'hero.orderNow': 'Zamów Teraz',
    
    'menu.title': 'Nasze Menu',
    'menu.subtitle': 'Odkryj nasz wybór autentycznych dań, przygotowywanych codziennie według tradycyjnych przepisów',
    'menu.specialOffer': 'Promocja',
    'menu.viewFull': 'Zobacz Pełne Menu',
    'menu.viewDetails': 'Zobacz Szczegóły',
    'menu.search': 'Szukaj w menu...',
    'menu.filter': 'Filtruj',
    'menu.categories.all': 'Wszystkie',
    'menu.categories.doner': 'Döner',
    'menu.categories.kebab': 'Kebab',
    'menu.categories.pide': 'Pide',
    'menu.categories.lahmacun': 'Lahmacun',
    'menu.categories.vegetarian': 'Wegetariańskie',
    'menu.categories.desserts': 'Desery',
    'menu.categories.drinks': 'Napoje',
    'menu.reviews': 'opinii',
    
    'locations.title': 'Nasze Lokalizacje',
    'locations.description': 'Znajdź najbliższą restaurację Memet Kebab i doświadcz autentycznej kuchni.',
    'locations.comingSoon': 'Wkrótce',
    'locations.hours': 'Godziny Otwarcia',
    'locations.phone': 'Telefon',
    'locations.flagship': 'Flagowa Restauracja',
    'locations.dineIn': 'Dostępna Konsumpcja na Miejscu i na Wynos',
    'locations.capacity': 'Dostępne Przestronne Miejsca',
    'locations.viewMenu': 'Zobacz Menu',
    'locations.back': 'Powrót do Poprzedniej Strony',
    'locations.expansion': 'Rozwijamy się w Europie',
    'locations.expansionText': 'Zaczynając od naszych korzeni w Europie, rozszerzamy naszą obecność w Europie, aby przynieść autentyczną kuchnię do większej liczby społeczności. Nasze zaangażowanie w jakość i tradycję pozostaje niezmienne w miarę naszego rozwoju.',
    'locations.quality': 'Jakość Przede Wszystkim',
    'locations.qualityText': 'Każda lokalizacja utrzymuje nasze wysokie standardy jakości żywności i doskonałości obsługi.',
    'locations.tradition': 'Autentyczna Tradycja',
    'locations.traditionText': 'Zachowujemy tradycyjne przepisy i metody gotowania we wszystkich lokalizacjach.',
    'locations.community': 'Koncentracja na Społeczności',
    'locations.communityText': 'Każda lokalizacja jest zaprojektowana jako przyjazne miejsce spotkań dla lokalnej społeczności.',
    'locations.franchiseTitle': 'Dołącz do Rodziny Memet Kebab',
    'locations.franchiseDescription': 'Zainteresowany wprowadzeniem autentycznej kuchni do swojej społeczności? Dowiedz się o naszych możliwościach franczyzowych.',
    'locations.franchiseContact': 'Skontaktuj się z Naszym Zespołem Franczyzowym',
    'locations.franchiseEmail': 'franchise@memetkebab.com',
    'locations.franchisePhone': '+48 123 456 789',
    
    'about.title': 'Nasza Historia',
    'about.text1': 'Od kilku dekad jesteśmy zaangażowani w serwowanie dań mięsnych najwyższej jakości w całej Europie. Nasza podróż rozpoczęła się od prostego, ale potężnego celu: dostarczyć autentyczne, wysokiej jakości jedzenie w przystępnych cenach.',
    'about.text2': 'Dziś kontynuujemy tę tradycję, starannie wybierając najlepsze kawałki mięsa i przygotowując je z pasją i umiejętnościami.',
    'about.meat.title': 'Mięso Najwyższej Jakości',
    'about.meat.description': 'Cieszymy się, że możemy pozyskiwać mięso najwyższej jakości od zaufanych dostawców europejskich. Nasze zaangażowanie w doskonałość zapewnia, że każde danie, które serwujemy, spełnia nasze surowe standardy.',
    'about.meat.point1': 'Wybrane codziennie kawałki mięsa premium',
    'about.meat.point2': 'Certyfikowana jakość',
    'about.meat.point3': 'Przygotowane przez doświadczonych kucharzy',
    'about.meat.detailed.description': 
      'At Memet Kebab, our foundation is built on an unwavering commitment to premium quality meat. ' +
      'We partner exclusively with renowned European suppliers who share our dedication to excellence. ' +
      'Our master butchers meticulously select each cut of meat, ensuring it meets our stringent quality criteria before it ever reaches our kitchens.\n\n' +
      'Our meat preparation process combines time-honored European butchery traditions with modern food safety standards. ' +
      'We maintain strict temperature controls and hygiene protocols throughout our supply chain, from selection to service. ' +
      'This careful attention to detail ensures that every piece of meat maintains its optimal flavor and texture.\n\n' +
      'We believe that exceptional meat quality is not just about the cut—it’s about the entire journey from farm to plate. ' +
      'That’s why we work closely with suppliers who prioritize ethical farming practices and maintain the highest standards of animal welfare. ' +
      'Our commitment to quality extends beyond taste to encompass responsibility and sustainability in every aspect of our operation.',
    'about.meat.detailed.point1': 'Our expert butchers carefully select premium cuts daily, inspecting each piece to ensure it meets our strict quality standards. This daily selection process guarantees that only the finest cuts make it to our kitchens.',
    'about.meat.detailed.point2': 'We maintain comprehensive quality control measures and work exclusively with certified European suppliers who share our commitment to excellence. Regular audits and inspections ensure consistent quality.',
    'about.meat.detailed.point3': 'Our skilled chefs bring decades of combined expertise to prepare each dish with precision and care, using traditional techniques refined over generations.',
    'about.learnMore': 'Dowiedz się Więcej o Nas',
    'about.values.title': 'Nasze Wartości',
    'about.values.description': 'Nasz fundament opiera się na wartościach, które definiują każdy aspekt naszej obsługi i jakości.',
    'about.values.quality.title': 'Bezkompromisowa Jakość',
    'about.values.quality.description': 'Wybieramy tylko mięso najwyższej jakości i najświeższe składniki, współpracując z zaufanymi europejskimi dostawcami.',
    'about.values.tradition.title': 'Dziedzictwo i Innowacja',
    'about.values.tradition.description': 'Szanujemy tradycyjne przepisy przekazywane przez pokolenia, jednocześnie wprowadzając nowoczesne techniki.',
    'about.values.community.title': 'Społeczność Przede Wszystkim',
    'about.values.community.description': 'Każda restauracja Memet Kebab to więcej niż miejsce do jedzenia - to miejsce, gdzie społeczności spotykają się, by dzielić się wspaniałym jedzeniem.',
    'about.values.service.title': 'Doskonałość w Obsłudze',
    'about.values.service.description': 'Wierzymy w traktowanie każdego klienta jak rodziny, zapewniając ciepłą, uważną obsługę.',
    'about.tradition.title': 'Nasze Dziedzictwo Kulinarne',
    'about.tradition.description': 'Nasza historia jest zakorzeniona w pokoleniach kulinarnej wiedzy, gdzie tradycyjne przepisy zostały starannie zachowane i udoskonalone.',
    'about.history': 'Nasze Dziedzictwo',
    'about.history.part1': 'Nasza historia rozpoczęła się z prostą, ale potężną wizją: dostarczyć najlepsze, najbardziej autentyczne dania do Europy. Zaczynając od jednej lokalizacji, nasz założyciel kierował się niezachwianym zobowiązaniem do jakości i autentyczności. W przeciwieństwie do innych, którzy idą na skróty, od pierwszego dnia podjęliśmy fundamentalną decyzję: używać tylko prawdziwego mięsa najwyższej jakości, przygotowanego zgodnie z wieloletnimi tradycjami.',
    'about.history.part2': 'To zobowiązanie do doskonałości oznaczało osobiste wybieranie dostawców mięsa, wybierając tylko tych, którzy podzielali nasze oddanie jakości. Nawiązaliśmy współpracę z renomowanymi europejskimi rzeźnikami, którzy rozumieją, że prawdziwe dania wymagają prawdziwego mięsa - bez wypełniaczy, bez kompromisów. Nasz założyciel spędził lata na doskonaleniu naszej charakterystycznej marynaty i technik gotowania, pracując wraz z mistrzami kuchni, aby stworzyć dania, które ustali nowe standardy smaku i jakości.',
    'about.history.part3': 'Dziś Memet Kebab jest świadectwem tej pierwotnej wizji. To, co zaczęło się jako pojedyncza restauracja, rozrosło się w ukochaną europejską markę, ale nasze zasady pozostają niezmienne. Nadal osobiście kontrolujemy naszych dostawców mięsa, nadal używamy tych samych sprawdzonych przepisów, i nadal utrzymujemy wysokie standardy, które uczyniły nas liderem w autentycznej kuchni. Każde danie, które serwujemy, niesie ze sobą nasze dziedzictwo kulinarnej doskonałości, przygotowane z tą samą pasją i dbałością o szczegóły jak pierwszego dnia.',
    'about.commitment': 'Nasze Zobowiązanie',
    'about.commitment.part1': 'W Memet Kebab nasze zobowiązanie wykracza poza serwowanie pysznego jedzenia. Jesteśmy oddani tworzeniu przyjaznego środowiska, w którym każdy gość może doświadczyć wyjątkowej gościnności. Od naszej kuchni po Twój stół, dbamy o to, by każdy szczegół spełniał nasze wysokie standardy jakości i autentyczności. To, co nas wyróżnia, to nasze niezachwiane zobowiązanie do używania wyłącznie prawdziwego mięsa premium w naszych daniach - standard, który utrzymujemy od założenia.',
    'about.commitment.part2': 'Nieustannie dążymy do doskonalenia i innowacji, pozostając wiernymi naszemu dziedzictwu kulinarnemu. Nasze mięso pochodzi wyłącznie od certyfikowanych europejskich dostawców, którzy podzielają nasze oddanie jakości. Każdy kawałek jest starannie wybierany, odpowiednio sezonowany i fachowo przygotowywany zgodnie z tradycyjnymi metodami. Nigdy nie używamy przetworzonego mięsa, wypełniaczy ani sztucznych dodatków - tylko czyste, wysokiej jakości mięso, które zapewnia autentyczny smak, który kochają nasi klienci.',
    'about.commitment.part3': 'To zobowiązanie do jakości rozciąga się na każdy aspekt naszej działalności. Nasze dania są przygotowywane świeżo każdego dnia w każdej lokalizacji, zapewniając, że każda porcja utrzymuje wysokie standardy, których oczekują nasi klienci. Mimo naszego oddania premium składnikom i tradycyjnym metodom przygotowania, pozostajemy zobowiązani do utrzymywania przystępnych cen, czyniąc naszą autentyczną kuchnię dostępną dla wszystkich, nigdy nie idąc na kompromis w kwestii jakości.',
    
    'features.quality': 'Najwyższa Jakość',
    'features.qualityDesc': '100% halal mięso, świeże warzywa i domowe sosy',
    'features.service': 'Szybka Obsługa',
    'features.serviceDesc': 'Szybkie przygotowanie bez kompromisów w jakości',
    'features.community': 'Społeczność',
    'features.communityDesc': 'Z dumą służymy naszym lokalnym społecznościom',
    
    'app.title': 'Pobierz Aplikację Memet Kebab',
    'app.subtitle': 'Zamawiaj z wyprzedzeniem, zbieraj nagrody i korzystaj z ekskluzywnych ofert!',
    'app.scan': 'Zeskanuj aby pobrać',
    'app.available': 'Dostępne na iOS i Android',
    
    'contact.title': 'Skontaktuj się',
    'contact.call': 'Zadzwoń',
    'contact.email': 'Email',
    'contact.visit': 'Odwiedź nas',
    
    'careers.title': 'Dołącz do Nas',
    'careers.description': 'Zawsze szukamy pasjonatów do naszej rosnącej rodziny. Doświadcz radości serwowania autentycznej kuchni, budując swoją karierę.',
    'careers.button': 'Zobacz Oferty Pracy',
    'careers.form.title': 'Dołącz do Naszego Zespołu',
    'careers.form.fullName': 'Imię i Nazwisko',
    'careers.form.email': 'Adres Email',
    'careers.form.phone': 'Numer Telefonu',
    'careers.form.position': 'Stanowisko',
    'careers.form.experience': 'Lata Doświadczenia',
    'careers.form.message': 'Dlaczego chcesz dołączyć do naszego zespołu?',
    'careers.form.submit': 'Wyślij Aplikację',
    'careers.form.resume': 'CV',
    'careers.positions.chef': 'Starszy Kucharz',
    'careers.positions.kitchen': 'Personel Kuchni',
    'careers.positions.manager': 'Kierownik Restauracji',
    'careers.positions.server': 'Kelner',
    'careers.positions.driver': 'Kierowca Dostawczy',
    'careers.training.title': 'Szkolenia i Rozwój',
    'careers.training.description': 'Możliwości ciągłego uczenia się i ścieżki rozwoju kariery',
    'careers.benefits.title': 'Świetne Benefity',
    'careers.benefits.description': 'Konkurencyjne wynagrodzenie, ubezpieczenie zdrowotne i dodatek na posiłki',
    'careers.team.title': 'Wspaniały Zespół',
    'careers.team.description': 'Dołącz do pełnej pasji i wspierającej rodziny pracowników',
    
    'product.features.fresh': '100% Świeże Składniki',
    'product.features.halal': 'Certyfikat Halal',
    'product.features.made': 'Przygotowywane na Zamówienie',
    'product.features.chef': 'Polecane przez Szefa Kuchni',
    'product.features.traditional': 'Tradycyjna Receptura',
    'product.orderNow': 'Zamów Teraz',
    'product.addFavorites': 'Dodaj do Ulubionych',
    
    'products.classicDoner.title': 'Klasyczny Döner',
    'products.classicDoner.description': 'Tradycyjny turecki döner kebab zrobiony z mięsa najwyższej jakości',
    'products.mixedGrill.title': 'Talerz Mix Grill',
    'products.mixedGrill.description': 'Kompozycja dönera, kebaba adana i şişa z kurczaka',
    'products.falafel.title': 'Falafel Wegetariański',
    'products.falafel.description': 'Domowy falafel z hummusem i świeżą sałatką',
    'products.iskender.title': 'Kebab Iskender',
    'products.iskender.description': 'Krojony döner na chlebie pide z jogurtem i sosem pomidorowym',
    'products.adanaKebab.title': 'Kebab Adana',
    'products.adanaKebab.description': 'Pikantny kebab z mielonej jagnięciny podawany z piławem z kaszy bulgur i grillowanymi warzywami',
    'products.cheesePide.title': 'Pide z Serem',
    'products.cheesePide.description': 'Tradycyjna turecka pizza z mieszanką serów i ziołami',
    
    'promos.familyFeast.title': 'Uczta Rodzinna',
    'promos.familyFeast.description': 'Idealne dla 4: Talerz mix grill, sałatki, ryż i napoje',
    'promos.studentSpecial.title': 'Promocja Studencka',
    'promos.studentSpecial.description': 'Pokaż legitymację studencką i otrzymaj 15% zniżki',
    'promo.firstOrder.discount': '15% ZNIŻKI',
    'promo.firstOrder.text': 'Na pierwsze zamówienie',
    
    'stats.rating': 'Ocena 4.9 ★',
    'stats.downloads': '100K+ Pobrań',
    'stats.install': 'Darmowa Instalacja',
    'stats.platform': 'Aplikacja mobilna',
    
    'stats.happyCustomers': 'Zadowoleni Klienci',
    'stats.customerRating': 'Ocena Klientów',
    'stats.locations': 'Lokalizacje',
    
    'menu.featuredItems': 'Produkty Zalecane',
    'menu.viewMenu': 'Zobacz Menu',
    'menu.popular': 'Popularne',
    'menu.viewFullMenu': 'Zobacz Pełne Menu',
    'menu.specialOffers': 'Oferty Specjalne',
    'menu.limitedTime': 'Na Krótki Czas',
    'menu.order': 'Zamów',
    'menu.rating': '4.9',
    
    'products.classicDoner.title': 'Klasyczny Döner',
    'products.classicDoner.description': 'Tradycyjny turecki döner kebab zrobiony z mięsa najwyższej jakości',
    'products.mixedGrill.title': 'Talerz Mix Grill',
    'products.mixedGrill.description': 'Smaczna selekcja mięs z grilla, podawana z ryżem i warzywami',
    'products.falafel.title': 'Falafel w Pita',
    'products.falafel.description': 'Chrupsze kulki falafel zawinięte w świeży chleb pita z sosem tahini',
    'products.iskender.title': 'Kebab Iskender',
    'products.iskender.description': 'Krojony döner na chlebie pide z sosem pomidorowym i jogurtem',
    
    'promos.familyFeast.title': 'Uczta Rodzinna',
    'promos.familyFeast.description': 'Idealna uczta dla 4-6 osób z różnymi kebabami i dodatkami',
    'promos.studentSpecial.title': 'Promocja Studencka',
    'promos.studentSpecial.description': 'Pokaż legitymację studencką i otrzymaj wyłączne zniżki na wybrane posiłki',
    
    'contact.title': 'Skontaktuj się',
    'contact.call': 'Zadzwoń do Nas',
    'contact.email': 'Napisz do Nas',
    'contact.visit': 'Odwiedź Nas',
    
    'app.comingSoon': 'Wkrótce',
    'app.downloadNow': 'Pobierz Teraz',
    'app.appStore': 'App Store',
    'app.googlePlay': 'Google Play',
    'app.badge.rating': 'Ocena 4.9',
    'app.badge.reviews': '2k+ Opinii',
    'app.badge.downloads': '100k+',
    'app.badge.downloadsLabel': 'Pobrań',
    
    'hero.badge': '#1 Kebab w Europie',
    'hero.title': 'Poznaj Memet Kebab',
    'hero.peoplesChoice': 'Wybór Ludzi',
    
    'general.back': 'Wróć',
    'general.viewDetails': 'Zobacz Szczegóły',
    
    'footer.description': 'Przynosimy autentyczne smaki na Twój stół od 2010 roku. Doświadcz smaku tradycji z Memet Kebab.',
    'footer.quickLinks': 'Szybkie Linki',
    'footer.contact': 'Kontakt',
    'footer.followUs': 'Obserwuj Nas',
    'footer.rights': 'Wszelkie prawa zastrzeżone.',
    'footer.address': 'ul. Kebabowa 123',
    'footer.city': 'Europa',
    'footer.phone': '+1 (555) 123-4567',
    'footer.email': 'info@memetkebab.com',
    
    'nav.careers': 'Kariera',
    'nav.privacyPolicy': 'Polityka Prywatności',
    'nav.termsOfService': 'Warunki Użytkowania',
    
    'contact.title': 'Kontakt',
    'contact.call': 'Zadzwoń do Nas',
    'contact.email': 'Napisz do Nas',
    'contact.visit': 'Odwiedź Nas',
    'contact.getInTouch': 'Skontaktuj się',
    'contact.message': 'Wyślij Nam Wiadomość',
    'contact.form.name': 'Twoje Imię',
    'contact.form.email': 'Twój Email',
    'contact.form.message': 'Twoja Wiadomość',
    'contact.form.submit': 'Wyślij Wiadomość',
    
    'careers.title': 'Dołącz do Naszego Zespołu',
    'careers.subtitle': 'Zostań częścią naszej rosnącej rodziny',
    'careers.description': 'W Memet Kebab zawsze szukamy pasjonatów, którzy podzielają naszą miłość do autentycznej kuchni i wyjątkowej obsługi.',
    'careers.positions': 'Otwarte Stanowiska',
    'careers.benefits': 'Benefity',
    'careers.benefits.health': 'Ubezpieczenie Zdrowotne',
    'careers.benefits.vacation': 'Płatny Urlop',
    'careers.benefits.training': 'Szkolenia Zawodowe',
    'careers.benefits.meals': 'Posiłki Pracownicze',
    'careers.benefits.growth': 'Rozwój Kariery',
    'careers.apply': 'Aplikuj Teraz',
    'careers.noPositions': 'Brak otwartych stanowisk w tym momencie',
    
    'privacy.title': 'Polityka Prywatności',
    'privacy.lastUpdated': 'Ostatnia Aktualizacja',
    
    'terms.title': 'Warunki Użytkowania',
    'terms.lastUpdated': 'Ostatnia Aktualizacja',
    
    'maintenance.title': 'W Trakcie Konserwacji',
    'maintenance.message': 'Nasza strona internetowa i aplikacja są obecnie aktualizowane, aby lepiej Ci służyć. Wrócimy wkrótce!',
    'maintenance.status': 'W Toku',
    
    'product.features.fresh': 'Przygotowane ze świeżych składników',
    'product.features.halal': 'Certyfikowane mięso Halal',
    'product.features.made': 'Przygotowane na zamówienie',
    'product.features.chef': 'Przygotowane przez doświadczonych szefów kuchni',
    'product.features.traditional': 'Tradycyjne przepisy',
    'product.orderNow': 'Zamów Teraz',
    'product.addFavorites': 'Dodaj do Ulubionych',
    
    'app.title': 'Zamów Memet Kebab przez telefon',
    'app.subtitle': 'Pobierz naszą aplikację mobilną, aby korzystać z ekskluzywnych ofert i szybszego zamawiania.',
    'app.features.fast': 'Szybkie i łatwe zamawianie',
    'app.features.rewards': 'Zbieraj punkty za każde zamówienie',
    'app.features.offline': 'Zamawiaj offline z kodami QR',
    'app.download.ios': 'Pobierz z App Store',
    'app.download.android': 'Pobierz z Google Play',
    
    'careers.title': 'Dołącz do Naszego Zespołu',
    'careers.description': 'Zostań częścią naszej rosnącej rodziny i pomóż nam serwować autentyczną kuchnię.',
    'careers.training.title': 'Profesjonalne Szkolenie',
    'careers.training.description': 'Zapewniamy kompleksowe szkolenie, aby pomóc Ci rozwijać się w swojej roli.',
    'careers.benefits.title': 'Świetne Benefity',
    'careers.benefits.description': 'Korzystaj z konkurencyjnego wynagrodzenia, elastycznych godzin pracy i możliwości rozwoju kariery.',
    'careers.team.title': 'Wspaniały Zespół',
    'careers.team.description': 'Pracuj z pełnymi pasji ludźmi, którzy podzielają Twoją miłość do dobrego jedzenia.',
    'careers.positions.chef': 'Szef Kuchni',
    'careers.positions.kitchen': 'Personel Kuchni',
    'careers.positions.manager': 'Kierownik Restauracji',
    'careers.positions.server': 'Kelner',
    'careers.positions.driver': 'Kierowca Dostawczy',
    'careers.form.title': 'Aplikuj Teraz',
    'careers.form.fullName': 'Imię i Nazwisko',
    'careers.form.email': 'Adres Email',
    'careers.form.phone': 'Numer Telefonu',
    'careers.form.position': 'Stanowisko',
    'careers.form.selectPosition': 'Wybierz stanowisko',
    'careers.form.experience': 'Lata Doświadczenia',
    'careers.form.message': 'Opowiedz nam o sobie',
    'careers.form.submit': 'Wyślij Aplikację',
    
    'footer.company': 'Firma',
    'footer.about': 'O Nas',
    'footer.careers': 'Kariera',
    'footer.contact': 'Kontakt',
    'footer.legal': 'Prawne',
    'footer.privacy': 'Polityka Prywatności',
    'footer.terms': 'Regulamin',
    'footer.follow': 'Obserwuj Nas',
    'footer.newsletter': 'Newsletter',
    'footer.newsletterDesc': 'Zapisz się, aby otrzymywać specjalne oferty i aktualizacje.',
    'footer.subscribe': 'Zapisz się',
    'footer.rights': 'Wszelkie prawa zastrzeżone',
    
    'franchise.title': 'Dołącz do Rodziny Memet Kebab',
    'franchise.description': 'Bądź częścią naszej historii sukcesu. Otwórz własną franczyzę Memet Kebab i wprowadź autentyczną kuchnię do swojej społeczności.',
    'franchise.cta': 'Zostań Partnerem Franczyzowym',
    'franchise.years': 'Lat Doświadczenia',
    'franchise.customers': 'Zadowolonych Klientów',
    'franchise.satisfaction': 'Satysfakcja Partnerów',
    'franchise.support': 'Dostępne Wsparcie',
  },
  ro: {
    'nav.about': 'DESPRE',
    'nav.menu': 'MENIU',
    'nav.locations': 'LOCAȚII',
    'nav.contact': 'CONTACT',
    'nav.joinUs': 'ALĂTURĂ-TE',
    'nav.orderNow': 'Comandă Acum',
    'nav.careers': 'CARIERE',
    'nav.privacyPolicy': 'Politica de Confidențialitate',
    'nav.termsOfService': 'Termeni și Condiții',
    
    'hero.title': 'Turcesc Autentic',
    'hero.subtitle': 'Experimentează gustul autentic al Europei, aducând aromele autentice în toată Europa.',
    'hero.orderNow': 'Comandă Acum',
    
    'menu.title': 'Meniul Nostru',
    'menu.subtitle': 'Descoperă selecția noastră de preparate autentice, preparate zilnic folosind rețete tradiționale',
    'menu.specialOffer': 'Ofertă Specială',
    'menu.viewFull': 'Vezi Meniul Complet',
    'menu.viewDetails': 'Vezi Detalii',
    'menu.search': 'Caută în meniu...',
    'menu.filter': 'Filtrează',
    'menu.categories.all': 'Toate',
    'menu.categories.doner': 'Döner',
    'menu.categories.kebab': 'Kebab',
    'menu.categories.pide': 'Pide',
    'menu.categories.lahmacun': 'Lahmacun',
    'menu.categories.vegetarian': 'Vegetarian',
    'menu.categories.desserts': 'Deserturi',
    'menu.categories.drinks': 'Băuturi',
    'menu.reviews': 'recenzii',
    
    'locations.title': 'Locațiile Noastre',
    'locations.description': 'Găsește cel mai apropiat restaurant Memet Kebab și experimentează bucătăria autentică.',
    'locations.comingSoon': 'În Curând',
    'locations.hours': 'Program',
    'locations.phone': 'Telefon',
    'locations.flagship': 'Restaurant Principal',
    'locations.dineIn': 'Servire în Restaurant și La Pachet',
    'locations.capacity': 'Locuri Spațioase Disponibile',
    'locations.viewMenu': 'Vezi Meniul',
    'locations.back': 'Înapoi la Pagina Anterioară',
    'locations.expansion': 'În Expansiune în Europa',
    'locations.expansionText': 'Pornind din Europa, ne extindem prezența în Europa pentru a aduce bucătăria autentică mai multor comunități.',
    'locations.quality': 'Calitate Înainte de Toate',
    'locations.qualityText': 'Fiecare locație menține standardele noastre înalte de calitate a alimentelor și serviciilor.',
    'locations.tradition': 'Tradiție Autentică',
    'locations.traditionText': 'Păstrăm rețetele și metodele tradiționale de gătit în toate locațiile.',
    'locations.community': 'Focus pe Comunitate',
    'locations.communityText': 'Fiecare locație este concepută pentru a fi un loc primitor pentru comunitatea locală.',
    'locations.franchiseTitle': 'Alătură-te Familiei Noastre în Creștere',
    'locations.franchiseDescription': 'Ești interesat să aduci bucătăria autentică în comunitatea ta? Află despre oportunitățile noastre de franciză.',
    'locations.franchiseContact': 'Contactează Echipa de Franciză',
    'locations.franchiseEmail': 'franchise@memetkebab.com',
    'locations.franchisePhone': '+48 123 456 789',
    
    'about.title': 'Povestea Noastră',
    'about.text1': 'De câteva decenii, ne-am angajat să servim preparate din carne de înaltă calitate în toată Europa. Călătoria noastră a început cu o viziune simplă, dar puternică: să oferim mâncare autentică și de înaltă calitate la prețuri rezonabile.',
    'about.text2': 'Astăzi, continuăm această tradiție, selectând cu atenție cele mai bune bucăți de carne și preparându-le cu pasiune și pricepere.',
    'about.meat.title': 'Carne Premium',
    'about.meat.description': 'Ne mândrim cu faptul că putem obține carne de înaltă calitate de la furnizori europeni de încredere. Angajamentul nostru față de excelență asigură că fiecare fel de mâncare pe care îl servim îndeplinește standardele noastre stricte.',
    'about.meat.point1': 'Bucăți de carne premium selectate zilnic',
    'about.meat.point2': 'Asigurare a calității certificate',
    'about.meat.point3': 'Preparate de bucătari experimentați',
    'about.meat.detailed.description': 
      'At Memet Kebab, our foundation is built on an unwavering commitment to premium quality meat. ' +
      'We partner exclusively with renowned European suppliers who share our dedication to excellence. ' +
      'Our master butchers meticulously select each cut of meat, ensuring it meets our stringent quality criteria before it ever reaches our kitchens.\n\n' +
      'Our meat preparation process combines time-honored European butchery traditions with modern food safety standards. ' +
      'We maintain strict temperature controls and hygiene protocols throughout our supply chain, from selection to service. ' +
      'This careful attention to detail ensures that every piece of meat maintains its optimal flavor and texture.\n\n' +
      'We believe that exceptional meat quality is not just about the cut—it’s about the entire journey from farm to plate. ' +
      'That’s why we work closely with suppliers who prioritize ethical farming practices and maintain the highest standards of animal welfare. ' +
      'Our commitment to quality extends beyond taste to encompass responsibility and sustainability in every aspect of our operation.',
    'about.meat.detailed.point1': 'Our expert butchers carefully select premium cuts daily, inspecting each piece to ensure it meets our strict quality standards. This daily selection process guarantees that only the finest cuts make it to our kitchens.',
    'about.meat.detailed.point2': 'We maintain comprehensive quality control measures and work exclusively with certified European suppliers who share our commitment to excellence. Regular audits and inspections ensure consistent quality.',
    'about.meat.detailed.point3': 'Our skilled chefs bring decades of combined expertise to prepare each dish with precision and care, using traditional techniques refined over generations.',
    'about.learnMore': 'Află Mai Multe Despre Noi',
    'about.values.title': 'Valorile Noastre',
    'about.values.description': 'Fundația noastră este construită pe valori care definesc fiecare aspect al serviciului și calității noastre.',
    'about.values.quality.title': 'Calitate Fără Compromis',
    'about.values.quality.description': 'Selectăm doar carne de cea mai înaltă calitate și ingrediente proaspete, colaborând cu furnizori europeni de încredere.',
    'about.values.tradition.title': 'Moștenire și Inovație',
    'about.values.tradition.description': 'Onorăm rețetele tradiționale transmise prin generații, îmbrățișând în același timp tehnici moderne.',
    'about.values.community.title': 'Comunitatea pe Primul Loc',
    'about.values.community.description': 'Fiecare restaurant Memet Kebab este mai mult decât un loc pentru masă - este un loc unde comunitățile se adună pentru a împărtăși mâncare excelentă.',
    'about.values.service.title': 'Excelență în Servicii',
    'about.values.service.description': 'Credem în tratarea fiecărui client ca familie, oferind servicii călduroase și atente.',
    'about.tradition.title': 'Moștenirea Noastră Culinară',
    'about.tradition.description': 'Povestea noastră își are rădăcinile în generații de expertiză culinară, unde rețetele tradiționale au fost păstrate și perfecționate cu grijă.',
    'about.history': 'Moștenirea Noastră',
    'about.history.part1': 'Povestea noastră a început cu o viziune simplă dar puternică: să aducem cel mai bun și autentic mâncare în Europa. Începând cu o singură locație, fondatorul nostru a fost motivat de un angajament neclintit față de calitate și autenticitate. Spre deosebire de alții care fac compromisuri, am luat o decizie fundamentală din prima zi: să folosim doar carne reală, de calitate premium, preparată conform tradițiilor consacrate.',
    'about.history.part2': 'Acest angajament față de excelență a însemnat selectarea personală a furnizorilor noștri de carne, alegând doar pe cei care împărtășeau dedicarea noastră pentru calitate. Am stabilit parteneriate cu măcelari europeni renumiți care înțeleg că mâncarea reală necesită carne reală - fără umpluturi, fără compromisuri. Fondatorul nostru a petrecut ani perfecționând marinada noastră signature și tehnicile de gătit, lucrând alături de bucătari maeștri pentru a crea mâncare care să stabilească noi standarde în gust și calitate.',
    'about.history.part3': 'Astăzi, Memet Kebab este o dovadă a acelei viziuni originale. Ce a început ca un singur restaurant a crescut într-un brand european îndrăgit, dar principiile noastre rămân neschimbate. Încă ne inspectăm personal furnizorii de carne, încă folosim aceleași rețete testate în timp și încă menținem standardele exacte care ne-au făcut lideri în mâncarea autentică. Fiecare fel de mâncare pe care îl servim duce mai departe moștenirea noastră de excelență culinară, preparat cu aceeași pasiune și atenție la detalii ca în prima zi.',
    'about.commitment': 'Angajamentul Nostru',
    'about.commitment.part1': 'La Memet Kebab, angajamentul nostru se extinde dincolo de servirea mâncării delicioase. Suntem dedicați creării unui mediu primitor unde fiecare oaspete poate experimenta ospitalitate excepțională. De la bucătăria noastră până la masa ta, ne asigurăm că fiecare detaliu îndeplinește standardele noastre înalte de calitate și autenticitate. Ceea ce ne diferențiază este angajamentul nostru neclintit de a folosi doar carne reală, de calitate premium în mâncarea noastră - un standard pe care l-am menținut de la înființare.',
    'about.commitment.part2': 'Ne străduim continuu să ne îmbunătățim și să inovăm, rămânând fideli moștenirii noastre culinare. Carnea noastră provine exclusiv de la furnizori europeni certificați care împărtășesc dedicarea noastră pentru calitate. Fiecare bucată este atent selectată, maturată corespunzător și expertă preparată conform metodelor tradiționale. Nu folosim niciodată carne procesată, umpluturi sau aditivi artificiali - doar carne pură, de înaltă calitate care oferă gustul autentic pe care clienții noștri îl iubesc.',
    'about.commitment.part3': 'Acest angajament față de calitate se extinde la fiecare aspect al operațiunii noastre. Mâncarea noastră este preparată proaspăt zilnic în fiecare locație, asigurând că fiecare porție menține standardele înalte pe care clienții noștri le așteaptă. În ciuda dedicării noastre pentru ingrediente premium și metode tradiționale de preparare, rămânem dedicați menținerii prețurilor accesibile, făcând mâncarea noastră autentică accesibilă tuturor, fără a face vreodată compromisuri în privința calității.',
    
    'features.quality': 'Calitate Premium',
    'features.qualityDesc': 'Carne 100% halal, legume proaspete și sosuri făcute în casă',
    'features.service': 'Serviciu Rapid',
    'features.serviceDesc': 'Preparare rapidă fără compromisuri la calitate',
    'features.community': 'Comunitatea Primul',
    'features.communityDesc': 'Servim cu mândrie comunitățile locale',
    
    'app.title': 'Descarcă Aplicația Memet Kebab',
    'app.subtitle': 'Comandă în avans, câștigă recompense și primește oferte exclusive!',
    'app.scan': 'Scanează pentru descărcare',
    'app.available': 'Disponibil pe iOS și Android',
    
    'contact.title': 'Contactează-ne',
    'contact.call': 'Sună-ne',
    'contact.email': 'Trimite-ne un Email',
    'contact.visit': 'Vizitează-ne',
    'contact.getInTouch': 'Ia Legătura cu Noi',
    'contact.message': 'Trimite-ne un Mesaj',
    'contact.form.name': 'Numele Tău',
    'contact.form.email': 'Email-ul Tău',
    'contact.form.message': 'Mesajul Tău',
    'contact.form.submit': 'Trimite Mesaj',
    
    'careers.title': 'Alătură-te Echipei',
    'careers.subtitle': 'Fii parte din familia noastră în creștere',
    'careers.description': 'La Memet Kebab, căutăm mereu persoane pasionate care împărtășesc dragostea noastră pentru bucătăria autentică.',
    'careers.positions': 'Poziții Deschise',
    'careers.benefits': 'Beneficii',
    'careers.benefits.health': 'Asigurare de Sănătate',
    'careers.benefits.vacation': 'Concediu Plătit',
    'careers.benefits.training': 'Training Profesional',
    'careers.benefits.meals': 'Mese pentru Personal',
    'careers.benefits.growth': 'Dezvoltare în Carieră',
    'careers.apply': 'Aplică Acum',
    'careers.noPositions': 'Nu există poziții deschise momentan',
    
    'privacy.title': 'Politica de Confidențialitate',
    'privacy.lastUpdated': 'Ultima Actualizare',
    
    'terms.title': 'Termeni și Condiții',
    'terms.lastUpdated': 'Ultima Actualizare',
    
    'maintenance.title': 'În Mentenanță',
    'maintenance.message': 'Website-ul și aplicația noastră sunt în curs de actualizare pentru a vă servi mai bine. Revenim în curând!',
    'maintenance.status': 'În Desfășurare',
    
    'footer.description': 'Bucătărie autentică, servită cu pasiune și tradiție. Vino să descoperi gusturile Europei la Memet Kebab.',
    'footer.quickLinks': 'Link-uri Rapide',
    'footer.contact': 'Contact',
    'footer.followUs': 'Urmărește-ne',
    'footer.address': 'Str. Exemplu nr. 123',
    'footer.city': 'Europa',
    'footer.phone': '+40 123 456 789',
    'footer.email': 'contact@memetkebab.ro',
    'footer.rights': 'Toate drepturile rezervate.',
    
    'products.mixedGrill.title': 'Platou Mixt la Grătar',
    'products.mixedGrill.description': 'O selecție bogată de carne la grătar, inclusiv kebab, köfte și pui marinat.',
    
    'careers.form.title': 'Formular de Aplicare',
    'careers.form.fullName': 'Nume și Prenume',
    'careers.form.fullNamePlaceholder': 'Ion Popescu',
    'careers.form.email': 'Adresa de Email',
    'careers.form.emailPlaceholder': 'ion@exemplu.ro',
    'careers.form.phone': 'Număr de Telefon',
    'careers.form.phonePlaceholder': '+40 700 000 000',
    'careers.form.position': 'Poziția Dorită',
    'careers.form.selectPosition': 'Selectează Poziția',
    'careers.form.experience': 'Experiență',
    'careers.form.experiencePlaceholder': '3 ani',
    'careers.form.message': 'Mesajul Tău',
    'careers.form.messagePlaceholder': 'Spune-ne de ce dorești să te alături echipei noastre...',
    'careers.form.submit': 'Trimite Aplicația',
    
    'product.features.fresh': '100% Ingrediente Proaspete',
    'product.features.halal': 'Carne Certificată Halal',
    'product.features.made': 'Preparat la Comandă',
    'product.features.chef': 'Preparat de Bucătari Experți',
    'product.features.traditional': 'Rețete Tradiționale',
    'product.orderNow': 'Comandă Acum',
    'product.addFavorites': 'Adaugă la Favorite',
    
    'app.title': 'Comandă Memet Kebab de pe telefonul tău',
    'app.subtitle': 'Descarcă aplicația noastră mobilă pentru a beneficia de oferte exclusive și comenzi mai rapide.',
    'app.scan': 'Scanează pentru descărcare',
    'app.available': 'Disponibil pe iOS și Android',
    
    'careers.title': 'Alătură-te Echipei Noastre',
    'careers.description': 'Fii parte din familia noastră în creștere și ajută-ne să servim bucătărie autentică.',
    'careers.training.title': 'Training Profesional',
    'careers.training.description': 'Oferim training complet pentru a te ajuta să te dezvolți în rolul tău.',
    'careers.benefits.title': 'Beneficii Excelente',
    'careers.benefits.description': 'Bucură-te de salarii competitive, program flexibil și oportunități de dezvoltare a carierei.',
    'careers.team.title': 'Echipă Minunată',
    'careers.team.description': 'Lucrează cu oameni pasionați care împărtășesc dragostea ta pentru mâncarea bună.',
    'careers.positions.chef': 'Bucătar Șef',
    'careers.positions.kitchen': 'Personal Bucătărie',
    'careers.positions.manager': 'Manager Restaurant',
    'careers.positions.server': 'Ospătar',
    'careers.positions.driver': 'Șofer Livrare',
    'careers.form.title': 'Aplică Acum',
    'careers.form.fullName': 'Nume Complet',
    'careers.form.email': 'Adresă Email',
    'careers.form.phone': 'Număr Telefon',
    'careers.form.position': 'Poziție',
    'careers.form.selectPosition': 'Selectează o poziție',
    'careers.form.experience': 'Ani de Experiență',
    'careers.form.message': 'Spune-ne despre tine',
    'careers.form.submit': 'Trimite Aplicația',
    
    'footer.company': 'Companie',
    'footer.about': 'Despre Noi',
    'footer.careers': 'Cariere',
    'footer.contact': 'Contact',
    'footer.legal': 'Legal',
    'footer.privacy': 'Politica de Confidențialitate',
    'footer.terms': 'Termeni și Condiții',
    'footer.follow': 'Urmărește-ne',
    'footer.newsletter': 'Newsletter',
    'footer.newsletterDesc': 'Abonează-te pentru a primi oferte speciale și actualizări.',
    'footer.subscribe': 'Abonează-te',
    'footer.rights': 'Toate drepturile rezervate',
    
    'franchise.title': 'Alătură-te Familiei Noastre în Creștere',
    'franchise.description': 'Fii parte din povestea noastră de succes. Deschide propria franciză Memet Kebab și aduce bucătăria autentică în comunitatea ta.',
    'franchise.cta': 'Devino Partener de Franciză',
    'franchise.years': 'Ani de Experiență',
    'franchise.customers': 'Clienți Mulțumiți',
    'franchise.satisfaction': 'Satisfacția Partenerilor',
    'franchise.support': 'Suport Disponibil',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  // Get initial language from cookie or default to 'pl'
  const [language, setLanguageState] = useState<Language>(() => {
    const savedLanguage = Cookies.get('preferredLanguage') as Language;
    return savedLanguage || 'pl';
  });

  // Update cookie when language changes
  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    Cookies.set('preferredLanguage', lang, { expires: 365 }); // Cookie expires in 1 year
  };

  // Function to get translation
  const t = (key: string): string => {
    return translations[language]?.[key] || translations['en'][key] || key;
  };

  // Set initial language based on browser preference if no cookie exists
  useEffect(() => {
    if (!Cookies.get('preferredLanguage')) {
      const browserLang = navigator.language.split('-')[0];
      const supportedLangs: Language[] = ['en', 'pl', 'ro'];
      const defaultLang = supportedLangs.includes(browserLang as Language) 
        ? browserLang as Language 
        : 'pl';
      setLanguage(defaultLang);
    }
  }, []);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}