export const plTranslations = {
    'nav.about': 'O NAS',
    'nav.menu': 'MENU',
    'nav.locations': 'LOKALIZACJE',
    'nav.contact': 'KONTAKT',
    'nav.joinUs': 'DOŁĄCZ',
    'nav.orderNow': 'Zamów Teraz',
    'nav.franchise': 'FRANCZYZA',
    'nav.careers': 'KARIERA',
    'nav.privacyPolicy': 'Polityka Prywatności',
    'nav.termsOfService': 'Warunki Użytkowania',
  
    'hero.title': 'Poznaj Memet Kebab',
    'hero.subtitle': 'Doświadcz prawdziwego smaku "döner" w przystępnych cenach. Przenosimy tradycyjne przepisy do Europy.',
    'hero.orderNow': 'Zamów Teraz',
  
    'menu.title': 'Nasze Menu',
    'menu.subtitle': 'Odkryj nasz wybór autentycznych dań, przygotowywanych codziennie na świeżo według tradycyjnych receptur',
    'menu.specialOffer': 'Oferta Specjalna',
    'menu.viewFull': 'Zobacz Pełne Menu',
    'menu.viewDetails': 'Zobacz Szczegóły',
    'menu.search': 'Szukaj w menu...',
    'menu.filter': 'Filtruj',
    'menu.categories.all': 'Wszystkie',
    'menu.categories.doner': 'Döner',
    'menu.categories.kebab': 'Kebab',
    'menu.categories.pide': 'Pide',
    'menu.categories.lahmacun': 'Lahmacun',
    'menu.categories.vegetarian': 'Wegetariańskie',
    'menu.categories.desserts': 'Desery',
    'menu.categories.drinks': 'Napoje',
    'menu.reviews': 'opinii',
  
    'locations.title': 'Nasze Lokalizacje',
    'locations.description': 'Znajdź najbliższą restaurację Memet Kebab i doświadcz autentycznej kuchni.',
    'locations.comingSoon': 'Wkrótce',
    'locations.hours': 'Godziny Otwarcia',
    'locations.phone': 'Telefon',
    'locations.flagship': 'Restauracja Flagowa',
    'locations.dineIn': 'Dostępne Dania na Miejscu i na Wynos',
    'locations.capacity': 'Przestronne Miejsca Siedzące',
    'locations.viewMenu': 'Zobacz Menu',
    'locations.back': 'Powrót do Poprzedniej Strony',
    'locations.expansion': 'Rozwijamy Się w Europie',
    'locations.expansionText': 'Rozpoczynając od skromnych początków, rozszerzamy naszą obecność w Europie, aby dostarczyć autentyczną kuchnię większej liczbie społeczności. Nasze zaangażowanie w jakość i tradycję pozostaje niezachwiane w miarę naszego rozwoju.',
    'locations.quality': 'Jakość Przede Wszystkim',
    'locations.qualityText': 'Każda lokalizacja utrzymuje nasze wysokie standardy jakości jedzenia i doskonałej obsługi.',
    'locations.tradition': 'Autentyczna Tradycja',
    'locations.traditionText': 'Utrzymujemy nasze tradycyjne przepisy i metody gotowania we wszystkich lokalizacjach.',
    'locations.community': 'Skupienie na Społeczności',
    'locations.communityText': 'Każda lokalizacja jest zaprojektowana jako przyjazne miejsce spotkań dla lokalnej społeczności.',
    'locations.franchiseTitle': 'Dołącz do Rodziny Memet Kebab',
    'locations.franchiseDescription': 'Jesteś zainteresowany wprowadzeniem autentycznej kuchni do swojej społeczności? Dowiedz się więcej o naszych możliwościach franczyzowych.',
    'locations.franchiseContact': 'Skontaktuj Się z Naszym Zespołem ds. Franczyzy',
    'locations.franchiseEmail': 'franchise@memetkebab.com',
    'locations.franchisePhone': '+48 123 456 789',
  
    'about.title': 'Nasza Historia',
    'about.text1': 'Od dziesięcioleci jesteśmy oddani serwowaniu dań mięsnych najwyższej jakości w całej Europie. Nasza podróż rozpoczęła się z prostą wizją: dostarczanie autentycznego, wysokiej jakości jedzenia w rozsądnych cenach.',
    'about.text2': 'Dziś kontynuujemy tę tradycję, starannie wybierając najlepsze kawałki mięsa i przygotowując je z fachowością i pasją.',
    'about.meat.title': 'Mięso Najwyższej Jakości',
    'about.meat.description': 'Jesteśmy dumni z pozyskiwania wyłącznie mięsa najwyższej jakości od zaufanych europejskich dostawców. Nasze zaangażowanie w doskonałość zapewnia, że każde serwowane przez nas danie spełnia nasze wymagające standardy.',
    'about.meat.point1': 'Codziennie Wybierane Kawałki Premium',
    'about.meat.point2': 'Certyfikowana Gwarancja Jakości',
    'about.meat.point3': 'Fachowo Przygotowane przez Wykwalifikowanych Szefów Kuchni',
      'about.meat.detailed.description':
        'W Memet Kebab nasza fundacja opiera się na niezachwianym zaangażowaniu w mięso najwyższej jakości. ' +
        'Współpracujemy wyłącznie z renomowanymi europejskimi dostawcami, którzy podzielają nasze dążenie do doskonałości. ' +
        'Nasi mistrzowie rzeźnictwa skrupulatnie wybierają każdy kawałek mięsa, zapewniając, że spełnia on nasze rygorystyczne kryteria jakości, zanim trafi do naszych kuchni.\n\n' +
        'Nasz proces przygotowania mięsa łączy w sobie sprawdzone europejskie tradycje rzeźnickie z nowoczesnymi standardami bezpieczeństwa żywności. ' +
        'Utrzymujemy ścisłą kontrolę temperatury i protokoły higieny w całym naszym łańcuchu dostaw, od selekcji po obsługę. ' +
        'Ta staranna dbałość o szczegóły zapewnia, że każdy kawałek mięsa zachowuje swój optymalny smak i teksturę.\n\n' +
        'Wierzymy, że wyjątkowa jakość mięsa to nie tylko kawałek — to cała podróż od farmy do talerza. ' +
        'Dlatego ściśle współpracujemy z dostawcami, którzy priorytetowo traktują etyczne praktyki rolnicze i utrzymują najwyższe standardy dobrostanu zwierząt. ' +
        'Nasze zaangażowanie w jakość wykracza poza smak i obejmuje odpowiedzialność i zrównoważony rozwój w każdym aspekcie naszej działalności.',
      'about.meat.detailed.point1': 'Nasi doświadczeni rzeźnicy codziennie starannie wybierają kawałki premium, sprawdzając każdy kawałek, aby upewnić się, że spełnia nasze surowe standardy jakości. Ten codzienny proces selekcji gwarantuje, że tylko najlepsze kawałki trafiają do naszych kuchni.',
      'about.meat.detailed.point2': 'Utrzymujemy kompleksowe środki kontroli jakości i współpracujemy wyłącznie z certyfikowanymi europejskimi dostawcami, którzy podzielają nasze zaangażowanie w doskonałość. Regularne audyty i inspekcje zapewniają stałą jakość.',
      'about.meat.detailed.point3': 'Nasi wykwalifikowani szefowie kuchni wnoszą dziesiątki lat połączonej wiedzy, aby przygotować każde danie z precyzją i starannością, stosując tradycyjne techniki udoskonalane przez pokolenia.',
    'about.learnMore': 'Dowiedz Się Więcej o Nas',
    'about.values.title': 'Nasze Wartości',
    'about.values.description': 'Nasze fundamenty opierają się na wartościach, które definiują każdy aspekt naszych usług i jakości.',
    'about.values.quality.title': 'Bezkompromisowa Jakość',
    'about.values.quality.description': 'Wybieramy tylko mięso najwyższej jakości i najświeższe składniki, współpracując z zaufanymi europejskimi dostawcami, którzy podzielają nasze zaangażowanie w doskonałość.',
    'about.values.tradition.title': 'Dziedzictwo i Innowacja',
    'about.values.tradition.description': 'Szanujemy tradycyjne przepisy przekazywane z pokolenia na pokolenie, a jednocześnie wykorzystujemy nowoczesne techniki, aby ulepszyć Twoje doświadczenia kulinarne.',
    'about.values.community.title': 'Społeczność na Pierwszym Miejscu',
    'about.values.community.description': 'Każda restauracja Memet Kebab to coś więcej niż tylko miejsce do jedzenia – to przyjazne miejsce, w którym społeczności spotykają się, aby dzielić się wspaniałym jedzeniem i tworzyć trwałe wspomnienia.',
    'about.values.service.title': 'Doskonałość w Obsłudze',
    'about.values.service.description': 'Wierzymy w traktowanie każdego klienta jak rodzinę, zapewniając ciepłą i troskliwą obsługę, która sprawia, że Twoja wizyta jest wyjątkowa.',
    'about.tradition.title': 'Nasze Kulinarne Dziedzictwo',
    'about.tradition.description': 'Nasza historia ma korzenie w wielopokoleniowej wiedzy kulinarnej, gdzie tradycyjne przepisy były starannie zachowywane i udoskonalane.',
    'about.history': 'Nasze Dziedzictwo',
    'about.history.part1': 'Nasza historia rozpoczęła się z prostą, ale potężną wizją: sprowadzić najlepsze, najbardziej autentyczne dania do Europy. Zaczynając od jednej lokalizacji, nasz założyciel był kierowany niezachwianym zaangażowaniem w jakość i autentyczność. W przeciwieństwie do innych, którzy idą na skróty, od samego początku podjęliśmy fundamentalną decyzję: używać tylko prawdziwego, najwyższej jakości mięsa, przygotowanego zgodnie z wieloletnią tradycją.',
    'about.history.part2': 'To zaangażowanie w doskonałość oznaczało osobisty wybór naszych dostawców mięsa, wybierając tylko tych, którzy podzielali nasze poświęcenie dla jakości. Nawiązaliśmy współpracę z renomowanymi europejskimi rzeźnikami, którzy rozumieją, że prawdziwe dania wymagają prawdziwego mięsa - bez wypełniaczy, bez kompromisów. Nasz założyciel spędził lata doskonaląc naszą firmową marynatę i techniki gotowania, pracując u boku mistrzów kuchni, aby stworzyć dania, które wyznaczą nowe standardy smaku i jakości.',
    'about.history.part3': 'Dziś Memet Kebab jest świadectwem tej pierwotnej wizji. To, co zaczęło się jako pojedyncza restauracja, rozrosło się w uwielbianą europejską markę, ale nasze zasady pozostają niezmienione. Nadal osobiście sprawdzamy naszych dostawców mięsa, nadal używamy tych samych sprawdzonych przepisów i nadal utrzymujemy wysokie standardy, które uczyniły nas liderem w autentycznej kuchni. Każde danie, które serwujemy, niesie ze sobą nasze dziedzictwo kulinarnej doskonałości, przygotowane z tą samą pasją i dbałością o szczegóły, jak w naszym pierwszym dniu.',
    'about.commitment': 'Nasze Zaangażowanie',
    'about.commitment.part1': 'W Memet Kebab nasze zaangażowanie wykracza poza serwowanie pysznego jedzenia. Jesteśmy oddani tworzeniu przyjaznego środowiska, w którym każdy gość może doświadczyć wyjątkowej gościnności. Od naszej kuchni po Twój stół, zapewniamy, że każdy szczegół spełnia nasze wysokie standardy jakości i autentyczności. Tym, co nas wyróżnia, jest nasze niezachwiane zaangażowanie w używanie wyłącznie prawdziwego mięsa premium w naszych daniach - standard, który utrzymujemy od początku.',
    'about.commitment.part2': 'Nieustannie dążymy do ulepszania i wprowadzania innowacji, pozostając wiernymi naszemu dziedzictwu kulinarnemu. Nasze mięso pochodzi wyłącznie od certyfikowanych europejskich dostawców, którzy podzielają nasze poświęcenie dla jakości. Każdy kawałek jest starannie wybierany, odpowiednio sezonowany i fachowo przygotowywany zgodnie z tradycyjnymi metodami. Nigdy nie używamy mięsa przetworzonego, wypełniaczy ani sztucznych dodatków - tylko czyste, wysokiej jakości mięso, które zapewnia autentyczny smak, który kochają nasi klienci.',
    'about.commitment.part3': 'To zaangażowanie w jakość rozciąga się na każdy aspekt naszej działalności. Nasze dania są przygotowywane świeżo każdego dnia w każdej lokalizacji, zapewniając, że każda porcja utrzymuje wysokie standardy, których oczekują nasi klienci. Pomimo naszego poświęcenia dla wysokiej jakości składników i tradycyjnych metod przygotowywania, pozostajemy zaangażowani w utrzymywanie naszych cen na przystępnym poziomie, dzięki czemu nasza autentyczna kuchnia jest dostępna dla każdego, bez kompromisów w kwestii jakości.',
  
    'features.quality': 'Najwyższa Jakość',
    'features.qualityDesc': 'Mięso w 100% halal, świeże warzywa i domowe sosy',
    'features.service': 'Szybka Obsługa',
    'features.serviceDesc': 'Szybkie przygotowanie bez kompromisów w jakości',
    'features.community': 'Społeczność na Pierwszym Miejscu',
    'features.communityDesc': 'Z dumą obsługujemy nasze lokalne społeczności',
  
    'app.title': 'Pobierz Aplikację Memet Kebab',
    'app.subtitle': 'Zamawiaj z wyprzedzeniem, zdobywaj nagrody i korzystaj z ekskluzywnych ofert!',
    'app.scan': 'Zeskanuj, aby pobrać',
    'app.available': 'Dostępne na iOS i Android',
  
    'contact.title': 'Skontaktuj Się z Nami',
    'contact.call': 'Zadzwoń do Nas',
    'contact.email': 'Wyślij Nam E-mail',
    'contact.visit': 'Odwiedź Nas',
  
    'careers.title': 'Dołącz do Naszego Zespołu',
    'careers.description': 'Zawsze szukamy pełnych pasji ludzi, którzy dołączą do naszej rosnącej rodziny. Doświadcz radości serwowania autentycznej kuchni, budując swoją karierę.',
    'careers.button': 'Zobacz Dostępne Stanowiska',
    'careers.form.title': 'Dołącz do Naszego Zespołu',
    'careers.form.fullName': 'Imię i Nazwisko',
    'careers.form.email': 'Adres E-mail',
    'careers.form.phone': 'Numer Telefonu',
    'careers.form.position': 'Stanowisko',
    'careers.form.selectPosition': 'Wybierz stanowisko',
    'careers.form.experience': 'Lata Doświadczenia',
    'careers.form.message': 'Dlaczego chcesz dołączyć do naszego zespołu?',
    'careers.form.submit': 'Wyślij Aplikację',
    'careers.form.resume': 'CV',
    'careers.positions.chef': 'Starszy Szef Kuchni',
    'careers.positions.kitchen': 'Personel Kuchenny',
    'careers.positions.manager': 'Kierownik Restauracji',
    'careers.positions.server': 'Kelner',
    'careers.positions.driver': 'Kierowca Dostawczy',
    'careers.training.title': 'Szkolenia i Rozwój',
    'careers.training.description': 'Możliwości ciągłego uczenia się i ścieżki rozwoju kariery',
    'careers.benefits.title': 'Świetne Benefity',
    'careers.benefits.description': 'Konkurencyjne wynagrodzenie, ubezpieczenie zdrowotne i dodatek na posiłki',
    'careers.team.title': 'Wspaniały Zespół',
    'careers.team.description': 'Dołącz do pełnej pasji i wspierającej rodziny pracowników',
  
    'product.features.fresh': 'Przygotowywane codziennie ze świeżych składników',
    'product.features.halal': 'Certyfikowane mięso Halal',
    'product.features.made': 'Przygotowywane na zamówienie',
    'product.features.chef': 'Przygotowane przez doświadczonych szefów kuchni',
    'product.features.traditional': 'Tradycyjne przepisy',
    'product.orderNow': 'Zamów Teraz',
    'product.addFavorites': 'Dodaj do Ulubionych',
  
    'products.classicDoner.title': 'Klasyczny Döner',
    'products.classicDoner.description': 'Tradycyjne danie z mięsa najwyższej jakości',
    'products.mixedGrill.title': 'Mieszany Grill',
    'products.mixedGrill.description': 'Pyszny wybór grillowanych mięs podawany z ryżem i warzywami',
    'products.falafel.title': 'Falafel Wrap',
    'products.falafel.description': 'Chrupiące kulki falafel zawinięte w świeży chleb pita z sosem tahini',
    'products.iskender.title': 'İskender',
    'products.iskender.description': 'Krojony döner na chlebie pide z sosem pomidorowym i jogurtem',
  
    'products.donerDurum.title': 'Döner Dürüm',
    'products.donerDurum.description': 'Pyszny döner zawinięty w cienki chleb lawasz ze świeżymi warzywami',
    'products.donerWithKetchup.title': 'Döner z Ketchupem',
    'products.donerWithKetchup.description': 'Tradycyjny döner podawany ze specjalnym sosem ketchupowym i świeżymi składnikami',
    'products.wrap.title': 'Wrap',
    'products.wrap.description': 'Aromatyczny wrap wypełniony przyprawionym mięsem i chrupiącymi warzywami',
    'products.singleDonerMenu.title': 'Menu z Dönerem',
    'products.singleDonerMenu.description': 'Pełny posiłek z pysznym dönerem, frytkami i napojem',
    'products.sandvic.title': 'Kanapka',
    'products.sandvic.description': 'Świeża kanapka z delikatnym mięsem, warzywami i naszym firmowym sosem',
    'products.menuDurum.title': 'Menu Dürüm',
    'products.menuDurum.description': 'Pełne menu z naszym firmowym dürümem, dodatkiem i orzeźwiającym napojem',
  
    'promos.familyFeast.title': 'Uczta Rodzinna',
    'promos.familyFeast.description': 'Idealne dla 4 osób: talerz mieszanych grillowanych mięs, sałatki, ryż i napoje',
    'promos.studentSpecial.title': 'Oferta dla Studentów',
    'promos.studentSpecial.description': 'Pokaż legitymację studencką i otrzymaj 15% zniżki na dowolny posiłek',
    'promo.firstOrder.discount': '15% ZNIŻKI',
    'promo.firstOrder.text': 'Na Twoje pierwsze zamówienie',
  
    'stats.rating': 'Ocena 4.9 ★',
    'stats.downloads': 'Ponad 100 tys. Pobrań',
    'stats.install': 'Darmowa Instalacja',
    'stats.platform': 'Aplikacja mobilna',
  
    'stats.happyCustomers': 'Zadowoleni Klienci',
    'stats.customerRating': 'Ocena Klientów',
    'stats.locations': 'Lokalizacje',
  
    'menu.featuredItems': 'Polecane Pozycje',
    'menu.viewMenu': 'Zobacz Menu',
    'menu.popular': 'Popularne',
    'menu.viewFullMenu': 'Zobacz Pełne Menu',
    'menu.specialOffers': 'Oferty Specjalne',
    'menu.limitedTime': 'Ograniczony Czas',
    'menu.order': 'Zamów',
    'menu.rating': '4.9',
  
    'contact.title': 'Skontaktuj Się',
    'contact.call': 'Zadzwoń do Nas',
    'contact.email': 'Napisz do Nas',
    'contact.visit': 'Odwiedź Nas',
  
    'app.comingSoon': 'Wkrótce',
    'app.downloadNow': 'Pobierz Teraz',
    'app.appStore': 'App Store',
    'app.googlePlay': 'Google Play',
    'app.badge.rating': 'Ocena 4.9',
    'app.badge.reviews': '2k+ Recenzji',
    'app.badge.downloads': '100k+',
    'app.badge.downloadsLabel': 'Pobrania',
  
    'hero.badge': '#1 w Polsce',
    'hero.title': 'Poznaj Memet Kebab',
    'hero.peoplesChoice': 'Wybór Ludzi',
  
    'general.back': 'Wstecz',
    'general.viewDetails': 'Zobacz Szczegóły',
  
    'footer.description': 'Przynosimy autentyczny döner na Twój stół. Doświadcz smaku tradycji z Memet Kebab.',
    'footer.quickLinks': 'Szybkie Linki',
    'footer.contact': 'Kontakt',
    'footer.followUs': 'Obserwuj Nas',
    'footer.rights': 'Wszelkie prawa zastrzeżone.',
    'footer.address': 'ul. Kebabowa 123',
    'footer.city': 'Europa',
    'footer.phone': '+1 (555) 123-4567',
    'footer.email': 'info@memetkebab.com',
  
    'contact.getInTouch': 'Skontaktuj się',
    'contact.message': 'Wyślij nam wiadomość',
    'contact.form.name': 'Twoje Imię',
    'contact.form.email': 'Twój E-mail',
    'contact.form.message': 'Twoja Wiadomość',
    'contact.form.submit': 'Wyślij Wiadomość',
  
    'careers.subtitle': 'Bądź częścią naszej rozwijającej się rodziny',
    'careers.positions': 'Otwarte Stanowiska',
    'careers.benefits': 'Benefity',
    'careers.benefits.health': 'Ubezpieczenie Zdrowotne',
    'careers.benefits.vacation': 'Płatny Urlop',
    'careers.benefits.training': 'Szkolenia Zawodowe',
    'careers.benefits.meals': 'Posiłki Pracownicze',
    'careers.benefits.growth': 'Rozwój Kariery',
    'careers.apply': 'Aplikuj Teraz',
    'careers.noPositions': 'Obecnie brak otwartych stanowisk',
  
    'privacy.title': 'Polityka Prywatności',
    'privacy.lastUpdated': 'Ostatnia Aktualizacja',
  
    'terms.title': 'Warunki Korzystania z Usługi',
    'terms.lastUpdated': 'Ostatnia Aktualizacja',
  
    'maintenance.title': 'W trakcie konserwacji',
    'maintenance.message': 'Nasza strona i aplikacja są obecnie aktualizowane, aby zapewnić Ci lepszą obsługę. Wkrótce wrócimy!',
    'maintenance.status': 'W trakcie',
  
    'app.subtitle': 'Pobierz naszą aplikację mobilną, aby korzystać z ekskluzywnych ofert i szybszego zamawiania.',
    'app.features.fast': 'Szybkie i łatwe zamawianie',
    'app.features.rewards': 'Zdobywaj nagrody za każde zamówienie',
    'app.features.offline': 'Zamawiaj offline za pomocą kodów QR',
    'app.download.ios': 'Pobierz w App Store',
    'app.download.android': 'Pobierz z Google Play',
  
    'careers.training.title': 'Szkolenie Zawodowe',
    'careers.training.description': 'Zapewniamy kompleksowe szkolenie, aby pomóc Ci rozwijać się w swojej roli.',
    'careers.benefits.title': 'Wspaniałe Benefity',
    'careers.benefits.description': 'Ciesz się konkurencyjnym wynagrodzeniem, elastycznym harmonogramem i możliwościami rozwoju kariery.',
    'careers.team.title': 'Niesamowity Zespół',
    'careers.team.description': 'Pracuj z pełnymi pasji ludźmi, którzy podzielają Twoją miłość do dobrego jedzenia.',
    'careers.positions.chef': 'Szef Kuchni',
    'careers.positions.kitchen': 'Pracownik Kuchni',
    'careers.positions.manager': 'Kierownik Restauracji',
    'careers.positions.server': 'Kelner',
    'careers.positions.driver': 'Kierowca Dostawczy',
    'careers.form.title': 'Aplikuj Teraz',
    'careers.form.fullName': 'Imię i Nazwisko',
    'careers.form.email': 'Adres E-mail',
    'careers.form.phone': 'Numer Telefonu',
    'careers.form.position': 'Stanowisko',
    'careers.form.selectPosition': 'Wybierz Stanowisko',
    'careers.form.experience': 'Lata Doświadczenia',
    'careers.form.message': 'Powiedz Nam Coś o Sobie',
    'careers.form.submit': 'Wyślij Aplikację',
  
    'footer.company': 'Firma',
    'footer.about': 'O Nas',
    'footer.careers': 'Kariera',
    'footer.contact': 'Kontakt',
    'footer.legal': 'Informacje Prawne',
    'footer.privacy': 'Polityka Prywatności',
    'footer.terms': 'Warunki Korzystania',
    'footer.follow': 'Obserwuj Nas',
    'footer.newsletter': 'Newsletter',
    'footer.newsletterDesc': 'Zapisz się, aby otrzymywać specjalne oferty i aktualizacje.',
    'footer.subscribe': 'Zapisz się',
    'footer.rights': 'Wszelkie prawa zastrzeżone',
  
    'franchise.title': 'Dołącz do Rodziny Memet Kebab',
    'franchise.description': 'Bądź częścią naszej historii sukcesu. Otwórz własną franczyzę Memet Kebab i wprowadź autentyczną kuchnię do swojej społeczności.',
    'franchise.cta': 'Zostań Partnerem Franczyzowym',
    'franchise.years': 'Lata Doświadczenia',
    'franchise.customers': 'Zadowoleni Klienci',
    'franchise.satisfaction': 'Zadowolenie Partnerów',
    'franchise.support': 'Dostępne Wsparcie',

    // Franchise Page
    'franchise.hero.title': 'Dołącz do rodziny Memet Kebab',
    'franchise.hero.subtitle': 'Rozpocznij własny biznes z sprawdzoną marką',
    'franchise.hero.cta': 'Zostań partnerem franczyzowym',
    
    'franchise.benefits.title': 'Korzyści z franczyzy',
    'franchise.benefits.subtitle': 'Skorzystaj z naszego sprawdzonego modelu biznesowego',
    'franchise.benefits.proven': 'Sprawdzona koncepcja',
    'franchise.benefits.provenDesc': 'Skuteczny model biznesowy z udowodnioną rentownością',
    'franchise.benefits.support': 'Kompleksowe wsparcie',
    'franchise.benefits.supportDesc': 'Ciągłe wsparcie we wszystkich obszarach biznesu',
    'franchise.benefits.location': 'Wybór lokalizacji',
    'franchise.benefits.locationDesc': 'Profesjonalna pomoc w wyborze lokalizacji',
    'franchise.benefits.roi': 'Wysoka stopa zwrotu',
    'franchise.benefits.roiDesc': 'Atrakcyjne marże i szybki zwrot z inwestycji',
    'franchise.benefits.brand': 'Silna marka',
    'franchise.benefits.brandDesc': 'Skorzystaj z rozpoznawalnej marki z lojalnymi klientami',

    'franchise.steps.title': 'Droga do franczyzy',
    'franchise.steps.subtitle': 'Pięć kroków do własnej restauracji Memet Kebab',
    'franchise.steps.inquiry': 'Zapytanie',
    'franchise.steps.inquiryDesc': 'Skontaktuj się z nami i podziel się swoją wizją',
    'franchise.steps.evaluation': 'Ocena',
    'franchise.steps.evaluationDesc': 'Wspólnie przeanalizujemy możliwości',
    'franchise.steps.agreement': 'Umowa',
    'franchise.steps.agreementDesc': 'Podpisanie umowy franczyzowej',
    'franchise.steps.training': 'Szkolenie',
    'franchise.steps.trainingDesc': 'Kompleksowe szkolenie we wszystkich obszarach',
    'franchise.steps.launch': 'Otwarcie',
    'franchise.steps.launchDesc': 'Otwarcie własnej restauracji',

    'franchise.investment.title': 'Zainwestuj w swoją przyszłość',
    'franchise.investment.description': 'Dołącz do rosnącej historii sukcesu w branży gastronomicznej',
    'franchise.investment.point1': 'Niska inwestycja początkowa w porównaniu ze średnią branżową',
    'franchise.investment.point2': 'Szybki zwrot dzięki sprawdzonemu modelowi biznesowemu',
    'franchise.investment.point3': 'Kompleksowe wsparcie w finansowaniu',
    'franchise.investment.form.title': 'Zainteresowany?',
    'franchise.investment.form.name': 'Twoje imię',
    'franchise.investment.form.email': 'Twój e-mail',
    'franchise.investment.form.phone': 'Twój numer telefonu',
    'franchise.investment.form.location': 'Preferowana lokalizacja',
    'franchise.investment.form.submit': 'Wyślij zgłoszenie',

    // Locations Page
    'locations.title': 'Nasze lokalizacje',
    'locations.subtitle': 'Znajdź najbliższą restaurację Memet Kebab i zaspokój swoje pragnienia',
    'locations.search.placeholder': 'Szukaj według adresu, miasta lub nazwy ulicy...',
    'locations.search.button': 'Znajdź najbliższą lokalizację',
    'locations.search.finding': 'Szukanie lokalizacji...',
    'locations.status.active': 'Otwarte',
    'locations.status.comingSoon': 'Wkrótce',
    'locations.hours': 'Godziny otwarcia',
    'locations.getDirections': 'Jak dojechać',
    'locations.callUs': 'Zadzwoń do nas',
    'locations.visitUs': 'Odwiedź nas'
  };