export const roTranslations = {
    "nav.about": "DESPRE",
    "nav.menu": "MENIU",
    "nav.locations": "LOCAȚII",
    "nav.contact": "CONTACT",
    "nav.joinUs": "ALĂTURĂ-TE",
    "nav.orderNow": "Comandă Acum",
    "nav.franchise": "FRANCIZĂ",
    "nav.careers": "CARIERE",
    "nav.privacyPolicy": "Politica de Confidențialitate",
    "nav.termsOfService": "Termeni și Condiții",
    "hero.title": "Turcesc Autentic",
    "hero.subtitle": "Experimentează gustul autentic al Europei, aducând aromele autentice în toată Europa.",
    "hero.orderNow": "Comandă Acum",
    "menu.title": "Meniul Nostru",
    "menu.subtitle": "Descoperă selecția noastră de preparate autentice, preparate zilnic folosind rețete tradiționale",
    "menu.specialOffer": "Ofertă Specială",
    "menu.viewFull": "Vezi Meniul Complet",
    "menu.viewDetails": "Vezi Detalii",
    "menu.search": "Caută în meniu...",
    "menu.filter": "Filtrează",
    "menu.categories.all": "Toate",
    "menu.categories.doner": "Döner",
    "menu.categories.kebab": "Kebab",
    "menu.categories.pide": "Pide",
    "menu.categories.lahmacun": "Lahmacun",
    "menu.categories.vegetarian": "Vegetarian",
    "menu.categories.desserts": "Deserturi",
    "menu.categories.drinks": "Băuturi",
    "menu.reviews": "recenzii",
    "locations.title": "Locațiile Noastre",
    "locations.subtitle": "Găsește cel mai apropiat restaurant Memet Kebab pentru a-ți satisface poftele",
    "locations.search.placeholder": "Caută după adresă, oraș sau nume de stradă...",
    "locations.search.button": "Găsește cea mai apropiată locație",
    "locations.search.finding": "Căutare locație...",
    "locations.status.active": "Deschis",
    "locations.status.comingSoon": "În curând",
    "locations.hours": "Program",
    "locations.getDirections": "Obține indicații",
    "locations.callUs": "Sună-ne",
    "locations.visitUs": "Vizitează-ne",
    "locations.description": "Găsește cel mai apropiat restaurant Memet Kebab și experimentează bucătăria autentică.",
    "locations.comingSoon": "În Curând",
    "locations.hours": "Program",
    "locations.phone": "Telefon",
    "locations.flagship": "Restaurant Principal",
    "locations.dineIn": "Servire în Restaurant și La Pachet",
    "locations.capacity": "Locuri Spațioase Disponibile",
    "locations.viewMenu": "Vezi Meniul",
    "locations.back": "Înapoi la Pagina Anterioară",
    "locations.expansion": "În Expansiune în Europa",
    "locations.expansionText": "Pornind din Europa, ne extindem prezența în Europa pentru a aduce bucătăria autentică mai multor comunități.",
    "locations.quality": "Calitate Înainte de Toate",
    "locations.qualityText": "Fiecare locație menține standardele noastre înalte de calitate a alimentelor și serviciilor.",
    "locations.tradition": "Tradiție Autentică",
    "locations.traditionText": "Păstrăm rețetele și metodele tradiționale de gătit în toate locațiile.",
    "locations.community": "Focus pe Comunitate",
    "locations.communityText": "Fiecare locație este concepută pentru a fi un loc primitor pentru comunitatea locală.",
    "locations.franchiseTitle": "Alătură-te Familiei Noastre în Creștere",
    "locations.franchiseDescription": "Ești interesat să aduci bucătăria autentică în comunitatea ta? Află despre oportunitățile noastre de franciză.",
    "locations.franchiseContact": "Contactează Echipa de Franciză",
    "locations.franchiseEmail": "franchise@memetkebab.com",
    "locations.franchisePhone": "+48 123 456 789",
    "about.title": "Povestea Noastră",
    "about.text1": "De câteva decenii, ne-am angajat să servim preparate din carne de înaltă calitate în toată Europa. Călătoria noastră a început cu o viziune simplă, dar puternică: să oferim mâncare autentică și de înaltă calitate la prețuri rezonabile.",
    "about.text2": "Astăzi, continuăm această tradiție, selectând cu atenție cele mai bune bucăți de carne și preparându-le cu pasiune și pricepere.",
    "about.meat.title": "Carne Premium",
    "about.meat.description": "Ne mândrim cu faptul că putem obține carne de înaltă calitate de la furnizori europeni de încredere. Angajamentul nostru față de excelență asigură că fiecare fel de mâncare pe care îl servim îndeplinește standardele noastre stricte.",
    "about.meat.point1": "Bucăți de carne premium selectate zilnic",
    "about.meat.point2": "Asigurare a calității certificate",
    "about.meat.point3": "Preparate de bucătari experimentați",
    "about.meat.detailed.description": "At Memet Kebab, our foundation is built on an unwavering commitment to premium quality meat. We partner exclusively with renowned European suppliers who share our dedication to excellence. Our master butchers meticulously select each cut of meat, ensuring it meets our stringent quality criteria before it ever reaches our kitchens.\n\nOur meat preparation process combines time-honored European butchery traditions with modern food safety standards. We maintain strict temperature controls and hygiene protocols throughout our supply chain, from selection to service. This careful attention to detail ensures that every piece of meat maintains its optimal flavor and texture.\n\nWe believe that exceptional meat quality is not just about the cut—it’s about the entire journey from farm to plate. That’s why we work closely with suppliers who prioritize ethical farming practices and maintain the highest standards of animal welfare. Our commitment to quality extends beyond taste to encompass responsibility and sustainability in every aspect of our operation.",
    "about.meat.detailed.point1": "Our expert butchers carefully select premium cuts daily, inspecting each piece to ensure it meets our strict quality standards. This daily selection process guarantees that only the finest cuts make it to our kitchens.",
    "about.meat.detailed.point2": "We maintain comprehensive quality control measures and work exclusively with certified European suppliers who share our commitment to excellence. Regular audits and inspections ensure consistent quality.",
    "about.meat.detailed.point3": "Our skilled chefs bring decades of combined expertise to prepare each dish with precision and care, using traditional techniques refined over generations.",
    "about.learnMore": "Află Mai Multe Despre Noi",
    "about.values.title": "Valorile Noastre",
    "about.values.description": "Fundația noastră este construită pe valori care definesc fiecare aspect al serviciului și calității noastre.",
    "about.values.quality.title": "Calitate Fără Compromis",
    "about.values.quality.description": "Selectăm doar carne de cea mai înaltă calitate și ingrediente proaspete, colaborând cu furnizori europeni de încredere.",
    "about.values.tradition.title": "Moștenire și Inovație",
    "about.values.tradition.description": "Onorăm rețetele tradiționale transmise prin generații, îmbrățișând în același timp tehnici moderne.",
    "about.values.community.title": "Comunitatea pe Primul Loc",
    "about.values.community.description": "Fiecare restaurant Memet Kebab este mai mult decât un loc pentru masă - este un loc unde comunitățile se adună pentru a împărtăși mâncare excelentă.",
    "about.values.service.title": "Excelență în Servicii",
    "about.values.service.description": "Credem în tratarea fiecărui client ca familie, oferind servicii călduroase și atente.",
    "about.tradition.title": "Moștenirea Noastră Culinară",
    "about.tradition.description": "Povestea noastră își are rădăcinile în generații de expertiză culinară, unde rețetele tradiționale au fost păstrate și perfecționate cu grijă.",
    "about.history": "Moștenirea Noastră",
    "about.history.part1": "Povestea noastră a început cu o viziune simplă dar puternică: să aducem cel mai bun și autentic mâncare în Europa. Începând cu o singură locație, fondatorul nostru a fost motivat de un angajament neclintit față de calitate și autenticitate. Spre deosebire de alții care fac compromisuri, am luat o decizie fundamentală din prima zi: să folosim doar carne reală, de calitate premium, preparată conform tradițiilor consacrate.",
    "about.history.part2": "Acest angajament față de excelență a însemnat selectarea personală a furnizorilor noștri de carne, alegând doar pe cei care împărtășeau dedicarea noastră pentru calitate. Am stabilit parteneriate cu măcelari europeni renumiți care înțeleg că mâncarea reală necesită carne reală - fără umpluturi, fără compromisuri. Fondatorul nostru a petrecut ani perfecționând marinada noastră signature și tehnicile de gătit, lucrând alături de bucătari maeștri pentru a crea mâncare care să stabilească noi standarde în gust și calitate.",
    "about.history.part3": "Astăzi, Memet Kebab este o dovadă a acelei viziuni originale. Ce a început ca un singur restaurant a crescut într-un brand european îndrăgit, dar principiile noastre rămân neschimbate. Încă ne inspectăm personal furnizorii de carne, încă folosim aceleași rețete testate în timp și încă menținem standardele exacte care ne-au făcut lideri în mâncarea autentică. Fiecare fel de mâncare pe care îl servim duce mai departe moștenirea noastră de excelență culinară, preparat cu aceeași pasiune și atenție la detalii ca în prima zi.",
    "about.commitment": "Angajamentul Nostru",
    "about.commitment.part1": "La Memet Kebab, angajamentul nostru se extinde dincolo de servirea mâncării delicioase. Suntem dedicați creării unui mediu primitor unde fiecare oaspete poate experimenta ospitalitate excepțională. De la bucătăria noastră până la masa ta, ne asigurăm că fiecare detaliu îndeplinește standardele noastre înalte de calitate și autenticitate. Ceea ce ne diferențiază este angajamentul nostru neclintit de a folosi doar carne reală, de calitate premium în mâncarea noastră - un standard pe care l-am menținut de la înființare.",
    "about.commitment.part2": "Ne străduim continuu să ne îmbunătățim și să inovăm, rămânând fideli moștenirii noastre culinare. Carnea noastră provine exclusiv de la furnizori europeni certificați care împărtășesc dedicarea noastră pentru calitate. Fiecare bucată este atent selectată, maturată corespunzător și expertă preparată conform metodelor tradiționale. Nu folosim niciodată carne procesată, umpluturi sau aditivi artificiali - doar carne pură, de înaltă calitate care oferă gustul autentic pe care clienții noștri îl iubesc.",
    "about.commitment.part3": "Acest angajament față de calitate se extinde la fiecare aspect al operațiunii noastre. Mâncarea noastră este preparată proaspăt zilnic în fiecare locație, asigurând că fiecare porție menține standardele înalte pe care clienții noștri le așteaptă. În ciuda dedicării noastre pentru ingrediente premium și metode tradiționale de preparare, rămânem dedicați menținerii prețurilor accesibile, făcând mâncarea noastră autentică accesibilă tuturor, fără a face vreodată compromisuri în privința calității.",
    "franchise.hero.title": "Alăturați-vă familiei Memet Kebab",
    "franchise.hero.subtitle": "Începeți propria afacere de succes cu un brand dovedit",
    "franchise.hero.cta": "Deveniți partener de franciză",
    "franchise.benefits.title": "Beneficiile parteneriatului de franciză",
    "franchise.benefits.subtitle": "Profitați de modelul nostru de afaceri dovedit",
    "franchise.benefits.proven": "Concept dovedit",
    "franchise.benefits.provenDesc": "Model de afaceri de succes cu profitabilitate dovedită",
    "franchise.benefits.support": "Suport complet",
    "franchise.benefits.supportDesc": "Asistență continuă în toate domeniile afacerii",
    "franchise.benefits.location": "Alegerea locației",
    "franchise.benefits.locationDesc": "Asistență profesională în alegerea locației",
    "franchise.benefits.roi": "Rentabilitate ridicată",
    "franchise.benefits.roiDesc": "Marje atractive și recuperare rapidă a investiției",
    "franchise.benefits.brand": "Brand puternic",
    "franchise.benefits.brandDesc": "Beneficiați de un brand consacrat cu clienți fideli",
    "franchise.steps.title": "Drumul spre franciză",
    "franchise.steps.subtitle": "Cinci pași spre propriul restaurant Memet Kebab",
    "franchise.steps.inquiry": "Solicitare",
    "franchise.steps.inquiryDesc": "Contactați-ne și împărtășiți-ne viziunea dumneavoastră",
    "franchise.steps.evaluation": "Evaluare",
    "franchise.steps.evaluationDesc": "Explorăm împreună posibilitățile",
    "franchise.steps.agreement": "Contract",
    "franchise.steps.agreementDesc": "Semnarea contractului de franciză",
    "franchise.steps.training": "Instruire",
    "franchise.steps.trainingDesc": "Instruire completă în toate domeniile",
    "franchise.steps.launch": "Deschidere",
    "franchise.steps.launchDesc": "Deschiderea propriului restaurant",
    "franchise.investment.title": "Investiți în viitorul dumneavoastră",
    "franchise.investment.description": "Faceți parte dintr-o poveste de succes în creștere în domeniul ospitalității",
    "franchise.investment.point1": "Investiție inițială scăzută comparativ cu media din industrie",
    "franchise.investment.point2": "Recuperare rapidă datorită modelului de afaceri dovedit",
    "franchise.investment.point3": "Suport complet în finanțare",
    "franchise.investment.form.title": "Sunteți interesat?",
    "franchise.investment.form.name": "Numele dumneavoastră",
    "franchise.investment.form.email": "Email-ul dumneavoastră",
    "franchise.investment.form.phone": "Numărul dumneavoastră de telefon",
    "franchise.investment.form.location": "Locația dorită",
    "franchise.investment.form.submit": "Trimiteți cererea",
    "features.quality": "Calitate Premium",
    "features.qualityDesc": "Carne 100% halal, legume proaspete și sosuri făcute în casă",
    "features.service": "Serviciu Rapid",
    "features.serviceDesc": "Preparare rapidă fără compromisuri la calitate",
    "features.community": "Comunitatea Primul",
    "features.communityDesc": "Servim cu mândrie comunitățile locale",
    "app.title": "Descarcă Aplicația Memet Kebab",
    "app.subtitle": "Comandă în avans, câștigă recompense și primește oferte exclusive!",
    "app.scan": "Scanează pentru descărcare",
    "app.available": "Disponibil pe iOS și Android",
    "contact.title": "Contactează-ne",
    "contact.call": "Sună-ne",
    "contact.email": "Trimite-ne un Email",
    "contact.visit": "Vizitează-ne",
    "contact.getInTouch": "Ia Legătura cu Noi",
    "contact.message": "Trimite-ne un Mesaj",
    "contact.form.name": "Numele Tău",
    "contact.form.email": "Email-ul Tău",
    "contact.form.message": "Mesajul Tău",
    "contact.form.submit": "Trimite Mesaj",
    "careers.title": "Alătură-te Echipei",
    "careers.subtitle": "Fii parte din familia noastră în creștere",
    "careers.description": "La Memet Kebab, căutăm mereu persoane pasionate care împărtășesc dragostea noastră pentru bucătăria autentică.",
    "careers.positions": "Poziții Deschise",
    "careers.benefits": "Beneficii",
    "careers.benefits.health": "Asigurare de Sănătate",
    "careers.benefits.vacation": "Concediu Plătit",
    "careers.benefits.training": "Training Profesional",
    "careers.benefits.meals": "Mese pentru Personal",
    "careers.benefits.growth": "Dezvoltare în Carieră",
    "careers.apply": "Aplică Acum",
    "careers.noPositions": "Nu există poziții deschise momentan",
    "privacy.title": "Politica de Confidențialitate",
    "privacy.lastUpdated": "Ultima Actualizare",
    "terms.title": "Termeni și Condiții",
    "terms.lastUpdated": "Ultima Actualizare",
    "maintenance.title": "În Mentenanță",
    "maintenance.message": "Website-ul și aplicația noastră sunt în curs de actualizare pentru a vă servi mai bine. Revenim în curând!",
    "maintenance.status": "În Desfășurare",
    "footer.description": "Bucătărie autentică, servită cu pasiune și tradiție. Vino să descoperi gusturile Europei la Memet Kebab.",
    "footer.quickLinks": "Link-uri Rapide",
    "footer.contact": "Contact",
    "footer.followUs": "Urmărește-ne",
    "footer.address": "Str. Exemplu nr. 123",
    "footer.city": "Europa",
    "footer.phone": "+40 123 456 789",
    "footer.email": "contact@memetkebab.ro",
    "footer.rights": "Toate drepturile rezervate.",
    "products.mixedGrill.title": "Platou Mixt la Grătar",
    "products.mixedGrill.description": "O selecție bogată de carne la grătar, inclusiv kebab, köfte și pui marinat.",
    "careers.form.title": "Formular de Aplicare",
    "careers.form.fullName": "Nume și Prenume",
    "careers.form.fullNamePlaceholder": "Ion Popescu",
    "careers.form.email": "Adresa de Email",
    "careers.form.emailPlaceholder": "ion@exemplu.ro",
    "careers.form.phone": "Număr de Telefon",
    "careers.form.phonePlaceholder": "+40 700 000 000",
    "careers.form.position": "Poziția Dorită",
    "careers.form.selectPosition": "Selectează Poziția",
    "careers.form.experience": "Experiență",
    "careers.form.experiencePlaceholder": "3 ani",
    "careers.form.message": "Mesajul Tău",
    "careers.form.messagePlaceholder": "Spune-ne de ce dorești să te alături echipei noastre...",
    "careers.form.submit": "Trimite Aplicația",
    "product.features.fresh": "100% Ingrediente Proaspete",
    "product.features.halal": "Carne Certificată Halal",
    "product.features.made": "Preparat la Comandă",
    "product.features.chef": "Preparat de Bucătari Experți",
    "product.features.traditional": "Rețete Tradiționale",
    "product.orderNow": "Comandă Acum",
    "product.addFavorites": "Adaugă la Favorite",
    "app.title": "Comandă Memet Kebab de pe telefonul tău",
    "app.subtitle": "Descarcă aplicația noastră mobilă pentru a beneficia de oferte exclusive și comenzi mai rapide.",
    "app.scan": "Scanează pentru descărcare",
    "app.available": "Disponibil pe iOS și Android",
    "careers.title": "Alătură-te Echipei Noastre",
    "careers.description": "Fii parte din familia noastră în creștere și ajută-ne să servim bucătărie autentică.",
    "careers.training.title": "Training Profesional",
    "careers.training.description": "Oferim training complet pentru a te ajuta să te dezvolți în rolul tău.",
    "careers.benefits.title": "Beneficii Excelente",
    "careers.benefits.description": "Bucură-te de salarii competitive, program flexibil și oportunități de dezvoltare a carierei.",
    "careers.team.title": "Echipă Minunată",
    "careers.team.description": "Lucrează cu oameni pasionați care împărtășesc dragostea ta pentru mâncarea bună.",
    "careers.positions.chef": "Bucătar Șef",
    "careers.positions.kitchen": "Personal Bucătărie",
    "careers.positions.manager": "Manager Restaurant",
    "careers.positions.server": "Ospătar",
    "careers.positions.driver": "Șofer Livrare",
    "careers.form.title": "Aplică Acum",
    "careers.form.fullName": "Nume Complet",
    "careers.form.email": "Adresă Email",
    "careers.form.phone": "Număr Telefon",
    "careers.form.position": "Poziție",
    "careers.form.selectPosition": "Selectează o poziție",
    "careers.form.experience": "Ani de Experiență",
    "careers.form.message": "Spune-ne despre tine",
    "careers.form.submit": "Trimite Aplicația",
    "footer.company": "Companie",
    "footer.about": "Despre Noi",
    "footer.careers": "Cariere",
    "footer.contact": "Contact",
    "footer.legal": "Legal",
    "footer.privacy": "Politica de Confidențialitate",
    "footer.terms": "Termeni și Condiții",
    "footer.follow": "Urmărește-ne",
    "footer.newsletter": "Newsletter",
    "footer.newsletterDesc": "Abonează-te pentru a primi oferte speciale și actualizări.",
    "footer.subscribe": "Abonează-te",
    "footer.rights": "Toate drepturile rezervate",
    "franchise.title": "Alătură-te Familiei Noastre în Creștere",
    "franchise.description": "Fii parte din povestea noastră de succes. Deschide propria franciză Memet Kebab și aduce bucătăria autentică în comunitatea ta.",
    "franchise.cta": "Devino Partener de Franciză",
    "franchise.years": "Ani de Experiență",
    "franchise.customers": "Clienți Mulțumiți",
    "franchise.satisfaction": "Satisfacția Partenerilor",
    "franchise.support": "Suport Disponibil",
    "franchise.hero.title": "Alăturați-vă familiei Memet Kebab",
    "franchise.hero.subtitle": "Începeți propria afacere de succes cu un brand dovedit",
    "franchise.hero.cta": "Deveniți partener de franciză",
    "franchise.benefits.title": "Avantajele francizei",
    "franchise.benefits.subtitle": "Profitați de modelul nostru de afaceri dovedit",
    "franchise.benefits.proven": "Concept Dovedit",
    "franchise.benefits.provenDesc": "Model de afaceri de succes cu profitabilitate dovedită",
    "franchise.benefits.support": "Suport Complet",
    "franchise.benefits.supportDesc": "Suport continuu în toate aspectele afacerii",
    "franchise.benefits.location": "Alegerea Locației",
    "franchise.benefits.locationDesc": "Asistență profesională în alegerea locației",
    "franchise.benefits.roi": "Rentabilitate Ridicată",
    "franchise.benefits.roiDesc": "Marje atractive și recuperare rapidă a investiției",
    "franchise.benefits.brand": "Brand Puternic",
    "franchise.benefits.brandDesc": "Beneficiază de avantajele unui brand cunoscut cu clienți fideli",
    "franchise.steps.title": "Drumul spre Franciză",
    "franchise.steps.subtitle": "Cinci pași spre propriul tău restaurant Memet Kebab",
    "franchise.steps.inquiry": "Solicitare",
    "franchise.steps.inquiryDesc": "Contactați-ne și împărtășește-ne viziunea ta",
    "franchise.steps.evaluation": "Evaluare",
    "franchise.steps.evaluationDesc": "Explorăm împreună oportunitățile",
    "franchise.steps.agreement": "Contract",
    "franchise.steps.agreementDesc": "Semnarea contractului de franciză",
    "franchise.steps.training": "Training",
    "franchise.steps.trainingDesc": "Training comprehensiv în toate domeniile",
    "franchise.steps.launch": "Deschidere",
    "franchise.steps.launchDesc": "Deschiderea propriului tău restaurant",
    "franchise.investment.title": "Investește în Viitorul Tău",
    "franchise.investment.description": "Devino parte din povestea noastră de succes în creștere în industria ospitalității",
    "franchise.investment.point1": "Investiție inițială scăzută comparativ cu media din industrie",
    "franchise.investment.point2": "Recuperare rapidă datorită modelului de afaceri dovedit",
    "franchise.investment.point3": "Suport complet în finanțare",
    "franchise.investment.form.title": "Interesat?",
    "franchise.investment.form.name": "Numele tău",
    "franchise.investment.form.email": "Email-ul tău",
    "franchise.investment.form.phone": "Numărul tău de telefon",
    "franchise.investment.form.location": "Locația dorită",
    "franchise.investment.form.submit": "Trimite cererea",
    "locations.search.finding": "Căutare locație...",
    "locations.status.active": "Deschis",
    "locations.status.comingSoon": "În curând",
    "locations.hours": "Program",
    "locations.getDirections": "Obține indicații",
    "locations.callUs": "Sună-ne",
    "locations.visitUs": "Vizitează-ne"
  };