export const slTranslations = {
  "nav.about": "O NAS",
  "nav.menu": "MENI",
  "nav.locations": "LOKACIJE",
  "nav.contact": "KONTAKT",
  "nav.joinUs": "PRIDRUŽI SE",
  "nav.orderNow": "NAROČI ZDAJ",
  "nav.franchise": "FRANŠIZA",
  "nav.careers": "KARIERE",
  "nav.privacyPolicy": "POLITIKA ZASEBNOSTI",
  "nav.termsOfService": "POGOJI UPORABE",
  "hero.title": "Spoznajte Memet Kebab",
  "hero.subtitle": "Doživite pravi \"döner\" po dostopnih cenah. Tradicionalni recepti v Evropi.",
  "hero.orderNow": "Naroči Zdaj",
  "menu.title": "Naš Meni",
  "menu.subtitle": "Odkrijte našo izbiro avtentičnih jedi, pripravljenih sveže vsak dan po tradicionalnih receptih",
  "menu.specialOffer": "Posebna Ponudba",
  "menu.viewFull": "Poglej Celoten Meni",
  "menu.viewDetails": "Poglej Podrobnosti",
  "menu.search": "Išči po meniju...",
  "menu.filter": "Filter",
  "menu.categories.all": "Vse",
  "menu.categories.doner": "Döner",
  "menu.categories.kebab": "Kebab",
  "menu.categories.pide": "Pide",
  "menu.categories.lahmacun": "Lahmacun",
  "menu.categories.vegetarian": "Vegetarijansko",
  "menu.categories.desserts": "Sladice",
  "menu.categories.drinks": "Pijače",
  "menu.reviews": "ocene",
  "locations.title": "Naše Lokacije",
  "locations.description": "Poiščite najbližjo restavracijo Memet Kebab in doživite avtentično kulinariko.",
  "locations.comingSoon": "Kmalu",
  "locations.hours": "Odpiralni Čas",
  "locations.phone": "Telefon",
  "locations.flagship": "Glavna Restavracija",
  "locations.dineIn": "Možnost Jedilnice in Odvzema",
  "locations.capacity": "Prostorna Sedežna Mesta na Voljo",
  "locations.viewMenu": "Poglej Meni",
  "locations.back": "Nazaj na Prejšnjo Stran",
  "locations.expansion": "Širimo se po Evropi",
  "locations.expansionText": "Začenši z našimi skromnimi začetki, širimo svojo prisotnost po Evropi, da bi avtentično kulinariko prinesli v več skupnosti. Naša zavezanost kakovosti in tradiciji ostaja neomajna, ko rastemo.",
  "locations.quality": "Kakovost na Prvem Mestu",
  "locations.qualityText": "Vsaka lokacija ohranja naše visoke standarde kakovosti hrane in odličnosti storitev.",
  "locations.tradition": "Avtentična Tradicija",
  "locations.traditionText": "Ohranjamo naše tradicionalne recepte in načine kuhanja na vseh lokacijah.",
  "locations.community": "Osredotočenost na Skupnost",
  "locations.communityText": "Vsaka lokacija je zasnovana tako, da je prijetno zbirališče za lokalno skupnost.",
  "locations.franchiseTitle": "Pridružite se Družini Memet Kebab",
  "locations.franchiseDescription": "Vas zanima, da bi v svojo skupnost prinesli avtentično kulinariko? Spoznajte naše možnosti franšize.",
  "locations.franchiseContact": "Kontaktirajte Našo Ekipo za Franšize",
  "locations.franchiseEmail": "franchise@memetkebab.com",
  "locations.franchisePhone": "+48 123 456 789",
  "about.title": "Naša Zgodba",
  "about.text1": "Že desetletja smo zavezani k strežbi mesnih jedi vrhunske kakovosti po vsej Evropi. Naša pot se je začela s preprosto vizijo: zagotoviti avtentično, visokokakovostno hrano po razumnih cenah.",
  "about.text2": "Danes nadaljujemo to tradicijo s skrbno izbiro najboljših kosov mesa in njihovo pripravo s strokovnim znanjem in strastjo.",
  "about.meat.title": "Meso Premium Kakovosti",
  "about.meat.description": "Ponosni smo, da lahko pridobivamo samo meso najvišje kakovosti od zaupanja vrednih evropskih dobaviteljev. Naša zavezanost odličnosti zagotavlja, da vsaka jed, ki jo postrežemo, izpolnjuje naše stroge standarde.",
  "about.meat.point1": "Premium kosi izbrani dnevno",
  "about.meat.point2": "Certificirano zagotavljanje kakovosti",
  "about.meat.point3": "Strokovno pripravljeno s strani usposobljenih kuharjev",
  "about.meat.detailed.description": "V Memet Kebabu naša osnova temelji na neomajni zavezanosti mesu vrhunske kakovosti. Partnerstvo imamo izključno z uglednimi evropskimi dobavitelji, ki delijo našo predanost odličnosti. Naši mojstri mesarji natančno izberejo vsak kos mesa in zagotovijo, da ustreza našim strogim merilom kakovosti, preden sploh pride v naše kuhinje.\n\nNaš postopek priprave mesa združuje preverjene evropske mesarske tradicije s sodobnimi standardi varnosti hrane. V celotni naši dobavni verigi vzdržujemo strog nadzor temperature in higienske protokole, od izbire do strežbe. Ta skrbna pozornost do detajlov zagotavlja, da vsak kos mesa ohrani svoj optimalni okus in teksturo.\n\nVerjamemo, da izjemna kakovost mesa ni samo kos – gre za celotno pot od kmetije do krožnika. Zato tesno sodelujemo z dobavitelji, ki dajejo prednost etičnim kmetijskim praksam in ohranjajo najvišje standarde za dobro počutje živali. Naša zavezanost kakovosti sega dlje od okusa in zajema odgovornost in trajnost v vseh vidikih našega delovanja.",
  "about.meat.detailed.point1": "Naši strokovni mesarji vsak dan skrbno izberejo kose premium razreda, pri čemer pregledajo vsak kos, da zagotovijo, da ustreza našim strogim standardom kakovosti. Ta dnevni postopek izbire zagotavlja, da samo najboljši kosi pridejo v naše kuhinje.",
  "about.meat.detailed.point2": "Vzdržujemo obsežne ukrepe za nadzor kakovosti in sodelujemo izključno s certificiranimi evropskimi dobavitelji, ki delijo našo zavezanost odličnosti. Redne revizije in inšpekcije zagotavljajo dosledno kakovost.",
  "about.meat.detailed.point3": "Naši usposobljeni kuharji prinašajo desetletja združenega strokovnega znanja, da vsako jed pripravijo natančno in skrbno, pri čemer uporabljajo tradicionalne tehnike, izpopolnjene skozi generacije.",
  "about.learnMore": "Izvedite Več o Nas",
  "about.values.title": "Naše Vrednote",
  "about.values.description": "Naši temelji so zgrajeni na vrednotah, ki opredeljujejo vsak vidik naše storitve in kakovosti.",
  "about.values.quality.title": "Brezkompromisna Kakovost",
  "about.values.quality.description": "Izbiramo samo meso vrhunske kakovosti in najsvežje sestavine, pri tem pa sodelujemo z zaupanja vrednimi evropskimi dobavitelji.",
  "about.values.tradition.title": "Dediščina & Inovacije",
  "about.values.tradition.description": "Spoštujemo tradicionalne recepte, ki so se prenašali iz roda v rod, hkrati pa sprejemamo sodobne tehnike, da izboljšamo vašo jedilno izkušnjo.",
  "about.values.community.title": "Skupnost na Prvem Mestu",
  "about.values.community.description": "Vsaka restavracija Memet Kebab je več kot le prostor za jedilnico – je prijeten prostor, kjer se skupnosti srečujejo, da si delijo odlično hrano.",
  "about.values.service.title": "Odličnost v Storitvah",
  "about.values.service.description": "Verjamemo v to, da vsako stranko obravnavamo kot družino, zagotavljamo pa toplo in pozorno storitev.",
  "about.tradition.title": "Naša Kulinarična Dediščina",
  "about.tradition.description": "Naša zgodba ima korenine v generacijah kulinaričnega znanja, kjer so bili tradicionalni recepti skrbno ohranjeni in izpopolnjeni.",
  "about.history": "Naša Dediščina",
  "about.history.part1": "Naša zgodba se je začela s preprosto, a močno vizijo: pripeljati najboljše in najbolj pristne jedi v Evropo. Začenši z eno lokacijo, je našega ustanovitelja vodila neomajna zavezanost kakovosti in pristnosti. Za razliko od drugih, ki se poslužujejo bližnjic, smo se že od prvega dne odločili: uporabljati samo pravo, vrhunsko meso, pripravljeno po preizkušenih tradicijah.",
  "about.history.part2": "Ta zavezanost odličnosti je pomenila osebno izbiro naših dobaviteljev mesa, pri čemer smo izbrali samo tiste, ki so delili našo predanost kakovosti. Vzpostavili smo partnerstva s priznanimi evropskimi mesarji, ki razumejo, da prave jedi zahtevajo pravo meso - brez polnil, brez kompromisov. Naš ustanovitelj je leta izpopolnjeval našo značilno marinado in tehnike kuhanja ter sodeloval z mojstri kuharji, da bi ustvaril jedi, ki bi postavile nove standarde okusa in kakovosti.",
  "about.history.part3": "Danes Memet Kebab stoji kot dokaz te prvotne vizije. Kar se je začelo kot ena sama restavracija, je preraslo v priljubljeno evropsko blagovno znamko, vendar naša načela ostajajo nespremenjena. Še vedno osebno pregledujemo naše dobavitelje mesa, še vedno uporabljamo iste preizkušene recepte in še vedno ohranjamo natančne standarde, ki so nas naredili vodilnega v avtentični kulinariki. Vsaka jed, ki jo postrežemo, nosi našo zapuščino kulinarične odličnosti, pripravljena z enako strastjo in pozornostjo do detajlov kot na naš prvi dan.",
  "about.commitment": "Naša Zaveza",
  "about.commitment.part1": "Pri Memet Kebab se naša zaveza razteza dlje od strežbe okusne hrane. Predani smo ustvarjanju prijetnega okolja, kjer lahko vsak gost doživi izjemno gostoljubnost. Od naše kuhinje do vaše mize zagotavljamo, da vsaka podrobnost ustreza našim visokim standardom kakovosti in pristnosti. To, kar nas ločuje, je naša neomajna zavezanost uporabi samo pravega, vrhunskega mesa v naših jedeh - standard, ki ga ohranjamo že od naše ustanovitve.",
  "about.commitment.part2": "Nenehno si prizadevamo za izboljšave in inovacije, pri tem pa ostajamo zvesti naši kulinarični dediščini. Naše meso pridobivamo izključno od certificiranih evropskih dobaviteljev, ki delijo našo predanost kakovosti. Vsak kos je skrbno izbran, pravilno staran in strokovno pripravljen v skladu s tradicionalnimi metodami. Nikoli ne uporabljamo predelanega mesa, polnil ali umetnih dodatkov - samo čisto, visokokakovostno meso, ki zagotavlja pristen okus, ki ga naše stranke obožujejo.",
  "about.commitment.part3": "Ta zavezanost kakovosti se razteza na vsak vidik našega delovanja. Naše jedi so pripravljene sveže vsak dan v vsaki lokaciji.",
  "franchise.hero.title": "Pridružite se družini Memet Kebab",
  "franchise.hero.subtitle": "Začnite svoj uspešen posel s preverjeno blagovno znamko",
  "franchise.hero.cta": "Postanite franšizni partner",
  "franchise.benefits.title": "Prednosti franšiznega partnerstva",
  "franchise.benefits.subtitle": "Izkoristite naš preverjen poslovni model",
  "franchise.benefits.proven": "Preverjen koncept",
  "franchise.benefits.provenDesc": "Uspešen poslovni model z dokazano donosnostjo",
  "franchise.benefits.support": "Celostna podpora",
  "franchise.benefits.supportDesc": "Stalna podpora na vseh področjih poslovanja",
  "franchise.benefits.location": "Izbira lokacije",
  "franchise.benefits.locationDesc": "Strokovna pomoč pri izbiri lokacije",
  "franchise.benefits.roi": "Visoka donosnost",
  "franchise.benefits.roiDesc": "Privlačne marže in hitra povrnitev naložbe",
  "franchise.benefits.brand": "Močna blagovna znamka",
  "franchise.benefits.brandDesc": "Izkoristite prednosti uveljavljene znamke z zvestimi strankami",
  "franchise.steps.title": "Pot do franšize",
  "franchise.steps.subtitle": "Pet korakov do vaše lastne restavracije Memet Kebab",
  "franchise.steps.inquiry": "Povpraševanje",
  "franchise.steps.inquiryDesc": "Kontaktirajte nas in delite svojo vizijo",
  "franchise.steps.evaluation": "Ocena",
  "franchise.steps.evaluationDesc": "Skupaj raziščemo možnosti",
  "franchise.steps.agreement": "Pogodba",
  "franchise.steps.agreementDesc": "Podpis franšizne pogodbe",
  "franchise.steps.training": "Usposabljanje",
  "franchise.steps.trainingDesc": "Celostno usposabljanje na vseh področjih",
  "franchise.steps.launch": "Odprtje",
  "franchise.steps.launchDesc": "Odprtje vaše lastne restavracije",
  "franchise.investment.title": "Investirajte v svojo prihodnost",
  "franchise.investment.description": "Postanite del rastoče zgodbe o uspehu v gostinstvu",
  "franchise.investment.point1": "Nizka začetna investicija v primerjavi s povprečjem v panogi",
  "franchise.investment.point2": "Hitra povrnitev zaradi preverjenega poslovnega modela",
  "franchise.investment.point3": "Celostna podpora pri financiranju",
  "franchise.investment.form.title": "Vas zanima?",
  "franchise.investment.form.name": "Vaše ime",
  "franchise.investment.form.email": "Vaš e-poštni naslov",
  "franchise.investment.form.phone": "Vaša telefonska številka",
  "franchise.investment.form.location": "Želena lokacija",
  "franchise.investment.form.submit": "Pošljite prijavo",
  "features.quality": "Vrhunska Kakovost",
  "features.qualityDesc": "100% halal meso, sveža zelenjava in domače omake",
  "features.service": "Hitra Storitev",
  "features.serviceDesc": "Hitra priprava brez ogrožanja kakovosti",
  "features.community": "Skupnost na Prvem Mestu",
  "features.communityDesc": "S ponosom služimo našim lokalnim skupnostim",
  "app.title": "Prenesite Aplikacijo Memet Kebab",
  "app.subtitle": "Naročite vnaprej, zaslužite nagrade in pridobite ekskluzivne ponudbe!",
  "app.scan": "Skenirajte za prenos",
  "app.available": "Na voljo za iOS in Android",
  "contact.title": "Stopite v Stik z Nami",
  "contact.call": "Pokličite Nas",
  "contact.email": "Pišite Nam",
  "contact.visit": "Obiščite Nas",
  "careers.title": "Pridružite se Naši Ekipi",
  "careers.description": "Vedno iščemo strastne ljudi, ki bi se pridružili naši rastoči družini. Doživite veselje ob strežbi avtentične kulinarike, medtem ko gradite svojo kariero.",
  "careers.button": "Poglejte Odprta Delovna Mesta",
  "careers.form.title": "Pridružite se Naši Ekipi",
  "careers.form.fullName": "Polno Ime",
  "careers.form.email": "E-poštni Naslov",
  "careers.form.phone": "Telefonska Številka",
  "careers.form.position": "Delovno Mesto",
  "careers.form.selectPosition": "Izberite delovno mesto",
  "careers.form.experience": "Leta Izkušenj",
  "careers.form.message": "Zakaj se želite pridružiti naši ekipi?",
  "careers.form.submit": "Oddajte Prijavo",
  "careers.form.resume": "Življenjepis",
  "careers.positions.chef": "Glavni Kuhar",
  "careers.positions.kitchen": "Kuhinjsko Osebje",
  "careers.positions.manager": "Vodja Restavracije",
  "careers.positions.server": "Natakar",
  "careers.positions.driver": "Voznik Dostave",
  "careers.training.title": "Usposabljanje in Razvoj",
  "careers.training.description": "Neprekinjene možnosti učenja in poti karierne rasti",
  "careers.benefits.title": "Odlične Ugodnosti",
  "careers.benefits.description": "Konkurenčna plača, zdravstveno zavarovanje in dodatek za obroke",
  "careers.team.title": "Izjemna Ekipa",
  "careers.team.description": "Pridružite se strastni in podporni delovni družini",
  "product.features.fresh": "Narejeno s svežimi sestavinami dnevno",
  "product.features.halal": "Certificirano Halal meso",
  "product.features.made": "Narejeno po naročilu",
  "product.features.chef": "Pripravljeno s strani strokovnih kuharjev",
  "product.features.traditional": "Tradicionalni recepti",
  "product.orderNow": "Naroči Zdaj",
  "product.addFavorites": "Dodaj med Priljubljene",
  "products.classicDoner.title": "Klasični Döner",
  "products.classicDoner.description": "Tradicionalni döner s svežo zelenjavo in posebno omako",
  "products.mixedGrill.title": "Mešani Žar Krožnik",
  "products.mixedGrill.description": "Kombinacija dönerja, postrežena z rižem in zelenjavo",
  "products.falafel.title": "Vegetarijanski Falafel",
  "products.falafel.description": "Domači falafel s humusom in svežo solato",
  "products.iskender.title": "Iskender",
  "products.iskender.description": "Narezan döner na kruhu pide z jogurtom in paradižnikovo omako",
  "products.adanaKebab.title": "Adana Kebab",
  "products.adanaKebab.description": "Začinjen kebab iz mlete jagnjetine, postrežen z bulgurjevim pilavom in zelenjavo z žara",
  "products.cheesePide.title": "Pide s Sirom",
  "products.cheesePide.description": "Tradicionalna jed z mešanimi siri in zelišči",
  "promos.familyFeast.title": "Družinska Gostija",
  "promos.familyFeast.description": "Popolno za 4: Mešani krožnik z žara, solate, riž in pijače",
  "promos.studentSpecial.title": "Študentska Posebna Ponudba",
  "promos.studentSpecial.description": "Pokažite svojo študentsko izkaznico za 15 % popust na vsak obrok",
  "promo.firstOrder.discount": "15% POPUST",
  "promo.firstOrder.text": "Pri vašem prvem naročilu",
  "stats.rating": "Ocena 4.9 ★",
  "stats.downloads": "100K+ Prenosov",
  "stats.install": "Brezplačna Namestitev",
  "stats.platform": "Mobilna aplikacija",
  "stats.happyCustomers": "Zadovoljne Stranke",
  "stats.customerRating": "Ocena Strank",
  "stats.locations": "Lokacije",
  "menu.featuredItems": "Izbrane Jedilniške Postavke",
  "menu.viewMenu": "Poglej Meni",
  "menu.popular": "Priljubljeno",
  "menu.viewFullMenu": "Poglej Celoten Meni",
  "menu.specialOffers": "Posebne Ponudbe",
  "menu.limitedTime": "Omejen Čas",
  "menu.order": "Naročilo",
  "menu.rating": "4.9",
  "products.classicDoner.title": "Klasični Döner",
  "products.classicDoner.description": "Tradicionalna jed iz mesa vrhunske kakovosti",
  "products.mixedGrill.title": "Mešani Žar",
  "products.mixedGrill.description": "Okusen izbor mesa z žara, postrežen z rižem in zelenjavo",
  "products.falafel.title": "Falafel Wrap",
  "products.falafel.description": "Hrustljave kroglice falafela, zavite v svežo lepinjo s tahini omako",
  "products.iskender.title": "İskender",
  "products.iskender.description": "Narezan döner na kruhu pide s paradižnikovo omako in jogurtom",
  "promos.familyFeast.title": "Družinska Gostija",
  "promos.familyFeast.description": "Popoln obrok za 4-6 oseb z različnimi kebabi in prilogami",
  "promos.studentSpecial.title": "Študentska Posebna Ponudba",
  "promos.studentSpecial.description": "Pokažite svojo študentsko izkaznico in pridobite ekskluzivne popuste na izbrane obroke",
  "contact.title": "Stopite v Stik z Nami",
  "contact.call": "Pokličite Nas",
  "contact.email": "Pišite Nam",
  "contact.visit": "Obiščite Nas",
  "app.comingSoon": "Kmalu",
  "app.downloadNow": "Prenesite Zdaj",
  "app.appStore": "App Store",
  "app.googlePlay": "Google Play",
  "app.badge.rating": "Ocena 4.9",
  "app.badge.reviews": "2k+ Ocene",
  "app.badge.downloads": "100k+",
  "app.badge.downloadsLabel": "Prenosi",
  "hero.badge": "#1 v Poljski",
  "hero.title": "Spoznajte Memet Kebab",
  "hero.peoplesChoice": "Izbira Ljudi",
  "general.back": "Nazaj",
  "general.viewDetails": "Poglej Podrobnosti",
  "footer.description": "Pripeljemo avtentični döner na vašo mizo. Doživite okus tradicije z Memet Kebab.",
  "footer.quickLinks": "Hitre Povezave",
  "footer.contact": "Kontakt",
  "footer.followUs": "Sledite Nam",
  "footer.rights": "Vse pravice pridržane.",
  "footer.address": "Kebab ulica 123",
  "footer.city": "Evropa",
  "footer.phone": "+1 (555) 123-4567",
  "footer.email": "info@memetkebab.com",
  "contact.getInTouch": "Stopite v Stik",
  "contact.message": "Pošljite nam sporočilo",
  "contact.form.name": "Vaše Ime",
  "contact.form.email": "Vaš E-poštni Naslov",
  "contact.form.message": "Vaše Sporočilo",
  "contact.form.submit": "Pošlji Sporočilo",
  "careers.subtitle": "Bodite del naše rastoče družine",
  "careers.positions": "Odprta Delovna Mesta",
  "careers.benefits": "Ugodnosti",
  "careers.benefits.health": "Zdravstveno Zavarovanje",
  "careers.benefits.vacation": "Plačan Dopust",
  "careers.benefits.training": "Profesionalno Usposabljanje",
  "careers.benefits.meals": "Obroki za Osebje",
  "careers.benefits.growth": "Karierna Rast",
  "careers.apply": "Prijavite se Zdaj",
  "careers.noPositions": "Trenutno ni odprtih delovnih mest",
  "privacy.title": "Politika Zasebnosti",
  "privacy.lastUpdated": "Zadnja Posodobitev",
  "terms.title": "Pogoji Storitve",
  "terms.lastUpdated": "Zadnja Posodobitev",
  "maintenance.title": "Vzdrževanje v Teku",
  "maintenance.message": "Naša spletna stran in aplikacija se trenutno posodabljata, da bi vam bolje služili. Kmalu se vrnemo!",
  "maintenance.status": "V Teeku",
  "app.subtitle": "Prenesite našo mobilno aplikacijo, da uživate v ekskluzivnih ponudbah in hitrejšem naročanju.",
  "app.features.fast": "Hitro in enostavno naročanje",
  "app.features.rewards": "Zaslužite nagrade z vsakim naročilom",
  "app.features.offline": "Naročanje brez povezave s QR kodami",
  "app.download.ios": "Prenesite v App Store",
  "app.download.android": "Pridobite jo v Google Play",
  "careers.training.title": "Profesionalno Usposabljanje",
  "careers.training.description": "Zagotavljamo celovito usposabljanje, ki vam bo pomagalo rasti v vaši vlogi.",
  "careers.benefits.title": "Odlične Ugodnosti",
  "careers.benefits.description": "Uživajte v konkurenčni plači, prilagodljivem urniku in možnostih kariernega razvoja.",
  "careers.team.title": "Izjemna Ekipa",
  "careers.team.description": "Delajte s strastnimi ljudmi, ki delijo vašo ljubezen do odlične hrane.",
  "careers.positions.chef": "Kuhar",
  "careers.positions.kitchen": "Kuhinjsko Osebje",
  "careers.positions.manager": "Vodja Restavracije",
  "careers.positions.server": "Natakar",
  "careers.positions.driver": "Voznik Dostave",
  "careers.form.title": "Prijavite se Zdaj",
  "careers.form.fullName": "Polno Ime",
  "careers.form.email": "E-poštni Naslov",
  "careers.form.phone": "Telefonska Številka",
  "careers.form.position": "Delovno Mesto",
  "careers.form.selectPosition": "Izberite Delovno Mesto",
  "careers.form.experience": "Leta Izkušenj",
  "careers.form.message": "Povejte nam kaj o sebi",
  "careers.form.submit": "Oddajte Prijavo",
  "footer.company": "Podjetje",
  "footer.about": "O Nas",
  "footer.careers": "Kariere",
  "footer.contact": "Kontakt",
  "footer.legal": "Pravno",
  "footer.privacy": "Politika Zasebnosti",
  "footer.terms": "Pogoji Storitve",
  "footer.follow": "Sledite Nam",
  "footer.newsletter": "E-novice",
  "footer.newsletterDesc": "Prijavite se, da prejmete posebne ponudbe in posodobitve.",
  "footer.subscribe": "Naročite se",
  "footer.rights": "Vse pravice pridržane",
  "franchise.title": "Pridružite se Družini Memet Kebab",
  "franchise.description": "Bodite del naše zgodbe o uspehu. Odprite svojo franšizo Memet Kebab in prinesite avtentično kulinariko v svojo skupnost.",
  "franchise.cta": "Postanite Partner Franšize",
  "franchise.years": "Leta Izkušenj",
  "franchise.customers": "Zadovoljne Stranke",
  "franchise.satisfaction": "Zadovoljstvo Partnerjev",
  "franchise.support": "Podpora na Voljo",
  "locations.title": "Naše lokacije",
  "locations.subtitle": "Najdite najbližjo restavracijo Memet Kebab in zadovoljite svoje želje",
  "locations.search.placeholder": "Iščite po naslovu, mestu ali imenu ulice...",
  "locations.search.button": "Najdi najbližjo lokacijo",
  "locations.search.finding": "Iskanje lokacije...",
  "locations.status.active": "Odprto",
  "locations.status.comingSoon": "Kmalu",
  "locations.hours": "Delovni čas",
  "locations.getDirections": "Navodila za pot",
  "locations.callUs": "Pokličite nas",
  "locations.visitUs": "Obiščite nas"
};